//! Card data: resolving a [`CardId`] to its immutable characteristics.
//!
//! The engine performs no I/O. The card snapshot is a JSON file embedded at
//! compile time with [`include_str!`] and parsed in memory; there is no
//! filesystem or network access here. serde is permitted for exactly this
//! purpose — see `docs/decisions/0006-serde-in-engine.md`.
//!
//! A card is a **functional definition** ([`CardData`], ADR 0018 §2): the
//! printing-independent rules object for one card, authored by hand under a stable
//! [`FunctionalId`](crate::id::FunctionalId) and versioned by [`SCHEMA_VERSION`]. It holds only what the
//! engine executes or a presentation layer derives from — never an upstream
//! presentation asset (flavor text, image URI, artist, frame), and **no rules prose
//! of any kind**: the text a player reads is generated by the server from the ability
//! IR below (ADR 0018 §7), so it cannot drift from what the card actually does. That
//! prohibition is structural, not a convention: [`CardData`] and [`PrintingEntry`]
//! both reject unknown fields, so such a field fails the load instead of being
//! ignored. The authored schema is documented in `docs/card-schema.md`.

mod aura;
mod card_data;
mod catalog;
mod database;
mod error;
mod helpers;
mod keyword;
mod printing;
mod rarity;
#[cfg(test)]
mod tests;

pub use crate::catalog::SCHEMA_VERSION;
pub use aura::AuraGrant;
pub use card_data::CardData;
pub use database::CardDatabase;
pub use error::CatalogError;
pub use helpers::abilities_of;
pub use keyword::Keyword;
pub use printing::{Printing, PrintingDatabase};
pub use rarity::Rarity;

// Re-export for internal use: spell_effects_of and apply_enters_replacements are crate-visible only
pub(crate) use helpers::{apply_enters_replacements, spell_effects_of};
