//! Copying objects (CR 707): what a copy *is*, and what it is a copy **of**.
//!
//! Copying is the earliest thing the layer system does — CR 613.1a/613.2a put copy
//! effects at layer 1, ahead of control, ahead of ability grants, ahead of power and
//! toughness — and that ordering is the whole reason this module exists apart from
//! [`characteristics`](crate::characteristics). A copy is not "a permanent with some
//! characteristics overwritten": it is a permanent whose *printed seed* is a different
//! object's, with everything the engine already does applied on top. A copied creature
//! with two `+1/+1` counters is the copied power plus two, because layer 1 decides the
//! power the counters are then added to.
//!
//! Three rules of CR 707 are load-bearing here, and each is a shape rather than a check:
//!
//! - **Copiable values are the printed ones** (CR 707.2) — name, mana cost, colors,
//!   types, rules text, power, toughness, loyalty — *as modified by other copy effects
//!   and by "as … enters" choices*, and by nothing else. Counters, damage, control
//!   changes, and every other continuous effect are explicitly not copied. So a snapshot
//!   of copiable values is exactly a [`Printed`]: a card and the face that is up, or a
//!   token's own characteristics. Nothing else has to be captured, because nothing else
//!   is copiable.
//! - **The snapshot is taken once** (CR 707.2b, CR 707.2c) — changing the original's
//!   copiable values afterwards does not change the copy, and a copy effect generated by
//!   a *static* ability determines its values only when the effect first starts to
//!   apply. [`copiable_values_of`] is called at that moment and never again, and because
//!   a card's printed face is immutable the stored [`Printed`] is a snapshot with nothing
//!   to keep fresh.
//! - **A copy of a copy is a copy of the same thing** (CR 707.3) — the copiable values a
//!   copy hands on are the ones it copied, not the ones printed on its own card. The
//!   chain is resolved *as the snapshot is taken*, so a stored [`CopiedValues`] is always
//!   one hop from a real printed face.
//!
//! ## Which face (CR 707.8)
//!
//! Copying a transforming double-faced permanent uses **the copiable values of the face
//! that is currently up**. A copy of a permanent that has turned over therefore has the
//! back face's name, types, power, toughness, and rules text — and, per CR 712.8e, mana
//! value **0**, because a back face has no mana cost of its own and the copy has no front
//! face to borrow one from. That last part is the one place a copy and its original
//! disagree about a characteristic, and it falls out of reading the back face's own
//! (empty) mana cost rather than the card's.
//!
//! What is *not* built: CR 707.8a's transforming **token** copy — a token copy of a
//! transforming permanent that has both faces and can turn over. Nothing here creates a
//! token as a copy at all, so the copy of a transformed permanent is single-faced and
//! stays on the face it copied.

use serde::Deserialize;

use crate::id::PermanentId;
use crate::state::{GameState, Permanent};
use crate::token::Printed;

/// Which permanents a copy effect may be pointed at, when its controller names one **as
/// the copying permanent enters** (CR 614.12).
///
/// A closed selector naming a *class*, evaluated relative to the entering permanent's
/// controller — the same shape [`ObservedPermanent`](crate::ability::ObservedPermanent)
/// and [`StaticAffects`](crate::ability::StaticAffects) take. Deliberately **not** a
/// [`TargetSpec`](crate::TargetSpec): this is a choice, not a target (CR 115.1), so
/// hexproof and shroud have nothing to say about it and no slot is filled at
/// announcement.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CopyClass {
    /// Any creature on the battlefield, whoever controls it — `choose a creature`.
    AnyCreature,
    /// A creature the choosing player controls — `a creature you control`.
    CreatureYouControl,
}

impl CopyClass {
    /// Whether `candidate` is one of the permanents this class names, for a choice made
    /// by `chooser`.
    ///
    /// Reads the **printed** face for the creature test, like every other type question
    /// the selectors ask, and the *computed* controller (CR 613 layer 2), like every
    /// other possessive one — so a creature someone has stolen is a creature *they*
    /// control.
    #[must_use]
    fn matches(
        self,
        state: &GameState,
        candidate: &Permanent,
        chooser: crate::id::PlayerId,
        db: &crate::CardDatabase,
    ) -> bool {
        let is_creature = candidate
            .printed
            .face(db)
            .is_some_and(|face| face.has_type(crate::card_type::CardType::Creature));
        if !is_creature {
            return false;
        }
        match self {
            Self::AnyCreature => true,
            Self::CreatureYouControl => {
                crate::characteristics::controller_of(state, candidate) == chooser
            }
        }
    }
}

/// **What** a copy effect fixed as a permanent entered applies to.
///
/// Two printed shapes, one mechanism. `You may have this creature enter as a copy of a
/// creature you control` makes the entering permanent the copy (CR 707.5); `As this Aura
/// enters, choose a creature. Enchanted creature is a copy of the chosen creature` makes
/// its *host* one, continuously, for as long as the Aura is attached (CR 707.2c). Both
/// record the same snapshot on the permanent that made the choice; only who reads it back
/// differs, which is what this says.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CopySubject {
    /// The permanent that made the choice is itself the copy (CR 707.5) — the default,
    /// and what every `enters as a copy` card says.
    #[default]
    This,
    /// The permanent this one is **attached to** is the copy, for as long as it stays
    /// attached (CR 707.2c). Derived on every read rather than written onto the host, so
    /// the host stops being a copy the instant the Aura leaves or moves, with nothing to
    /// prune (ADR 0005 §1).
    Attached,
}

/// The copiable values one permanent has taken from another (CR 707.2), and what they
/// apply to.
///
/// **Raw stored state, not a derivation** (ADR 0005 §1), and it has to be: which
/// permanent was named is a player's answer, and the values are frozen at the moment the
/// copy effect began (CR 707.2b/707.2c) — neither is recoverable from a snapshot of the
/// board, and recomputing the second would be the retroactive copy the rules forbid.
///
/// It is written exactly once, at the battlefield-entry seam, and never again.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CopiedValues {
    /// The printed face the copied characteristics are read from — the snapshot in full.
    ///
    /// A [`Printed`] rather than an unpacked bundle of name/types/power/… because that is
    /// exactly what "copiable values" means (CR 707.2) and because a card's printed face
    /// never changes: storing the handle *is* storing the values, with no second copy to
    /// keep in step. Chains are already resolved (CR 707.3), so this always names a real
    /// printed face rather than another copy.
    pub printed: Printed,
    /// Whether the recording permanent is the copy, or its host is.
    pub subject: CopySubject,
}

/// The copiable values of the permanent `id` right now (CR 707.2), resolved through any
/// copy effect already applying to it (CR 707.3).
///
/// The snapshot half of the model, and the *only* place one is taken. `None` when there
/// is no such permanent.
///
/// It reads the layer-1 answer rather than the stored face, which is the whole of
/// CR 707.3: a permanent that is already a copy hands on the values it copied, not the
/// ones printed on its own card. Because the chain is followed here, at snapshot time,
/// every stored [`CopiedValues`] is one hop from a printed face and no read path has to
/// walk a chain that could, in principle, be cyclic.
#[must_use]
pub(crate) fn copiable_values_of(state: &GameState, id: PermanentId) -> Option<Printed> {
    let perm = state.battlefield.iter().find(|p| p.id == id)?;
    Some(copiable_printed(state, perm).clone())
}

/// The printed face a permanent's characteristics are computed **from** — CR 613 layer 1
/// (CR 613.2a), the copiable values.
///
/// This is the layer, and it is one function: everything else in
/// [`characteristics`](crate::characteristics) already starts from a
/// [`Printed`](crate::Printed) and simply gets a different one. Nothing is overwritten
/// afterwards, so a copy's power really is the copied power *before* counters and pumps
/// are folded in at layer 7 — which is what makes "a copy with two `+1/+1` counters is
/// the copy's P/T plus two" true by construction rather than by ordering.
///
/// Two source lists, walked into one ordered set — the shape ADR 0017 established:
///
/// - the permanent's **own** recorded choice, when it named itself the subject
///   ([`CopySubject::This`]), timestamped by the permanent's own object id (CR 613.7d —
///   it received that timestamp when it entered);
/// - every permanent **attached to** it whose recorded choice named its host
///   ([`CopySubject::Attached`]), timestamped by the attachment's object id (CR 613.7a/e).
///
/// With more than one, the latest timestamp wins (CR 613.7): a copy effect replaces the
/// copiable values outright, so the last one to speak is the answer and the ones under it
/// are simply the values it was applied to. An Aura always enters after its host, so an
/// Aura's copy effect beats the host's own — which is what a Metamorphic Alteration
/// placed on a Mirror Image should do.
///
/// Reads **stored** fields only, so it is safe to call from inside the characteristics
/// computation — the same property that lets [`controller_of`](crate::characteristics::controller_of)
/// and [`loses_all_abilities`](crate::characteristics::loses_all_abilities) be read there.
#[must_use]
pub(crate) fn copiable_printed<'a>(state: &'a GameState, perm: &'a Permanent) -> &'a Printed {
    let mut best: Option<(u64, &Printed)> = None;
    let mut consider = |timestamp: u64, printed: &'a Printed| {
        if best.is_none_or(|(seen, _)| timestamp >= seen) {
            best = Some((timestamp, printed));
        }
    };
    if let Some(copied) = &perm.copied {
        if copied.subject == CopySubject::This {
            consider(perm.id.0, &copied.printed);
        }
    }
    for attachment in &state.battlefield {
        if attachment.attached_to != Some(perm.id) {
            continue;
        }
        if let Some(copied) = &attachment.copied {
            if copied.subject == CopySubject::Attached {
                consider(attachment.id.0, &copied.printed);
            }
        }
    }
    best.map_or(&perm.printed, |(_, printed)| printed)
}

/// The **printed face** a permanent's characteristics are read from after CR 613 layer 1
/// — its own, or the one it is a copy of (CR 707.2).
///
/// The public form of [`copiable_printed`], for the projection: a copy is drawn as the
/// thing it copies, so the view reads its name, cost, types, and rules text off this
/// rather than off the card the permanent physically is. `None` for a card handle the
/// database does not know, exactly as [`Printed::face`] is.
#[must_use]
pub fn copiable_face<'a>(
    state: &'a GameState,
    perm: &'a Permanent,
    db: &'a crate::CardDatabase,
) -> Option<crate::token::PrintedFace<'a>> {
    copiable_printed(state, perm).face(db)
}

/// The permanents `class` currently offers a chooser in seat `chooser`, in battlefield
/// order.
///
/// Recomputed from the state on every read — the counterpart of
/// [`choice_candidates`](crate::choice_candidates) for a permanent — so an answer is
/// validated against the set that exists *now*. It can afford to be: while the question
/// is owed nothing else in the game is legal, so the board under it cannot move.
///
/// Empty is a real answer: a `choose a creature` with no creature on the battlefield
/// chooses nothing, and the permanent enters as itself.
#[must_use]
pub fn copy_choice_candidates(
    state: &GameState,
    class: CopyClass,
    chooser: crate::id::PlayerId,
    db: &crate::CardDatabase,
) -> Vec<PermanentId> {
    state
        .battlefield
        .iter()
        .filter(|perm| class.matches(state, perm, chooser, db))
        .map(|perm| perm.id)
        .collect()
}
