/**
 * RUNE protocol — the TypeScript mirror of the `rune-protocol` crate.
 *
 * These are the wire shapes the server and every client share (see
 * `docs/protocol.md` and `crates/rune-protocol/src/lib.rs`). The client is a dumb
 * renderer: it displays a {@link GameView} and echoes back a `ChooseAction` with
 * the `id` of one issued {@link ValidAction}. It never computes legality, cost,
 * or effect — all displayed characteristics are server-computed.
 *
 * Any change to these shapes is a contract change: it must update the Rust crate
 * and `docs/protocol.md` in the same PR.
 */

/** Opaque player identity (server-assigned). */
export type PlayerId = string;

/** Opaque per-game entity id: a card, permanent, or stack object. */
export type EntityId = string;

/**
 * A card object, shown only to a player entitled to see it. All characteristics
 * are server-computed; the client never derives them.
 */
export interface CardView {
  /** Entity id of this card instance. */
  id: EntityId;
  /** Display name. */
  name: string;
  /** e.g. `"Creature — Elf Warrior"`. */
  type_line: string;
  /** Displayed mana cost string, e.g. `"{1}{G}"`. Absent for cards without one. */
  mana_cost?: string;
  /**
   * The card's rules text, generated by the server from the card's ability IR
   * (ADR 0018). Never computed here: the client renders this string and never
   * derives, formats, or infers a card's rules. Omitted (defaults to `""`) when the
   * card has no rules.
   */
  rules_text?: string;
  /**
   * The card's stable presentation identity — the same string for every copy of a
   * card, in every game, across server rebuilds (unlike {@link CardView.id}, which is
   * a per-game entity handle). Reserved for a future *client-local* cache that could
   * enrich presentation by identity; nothing renders from it today, and a client that
   * ignores it presents the card completely from `rules_text`.
   */
  functional_id?: string;
  /** Displayed power (a string so `*` round-trips). Present only for creatures. */
  power?: string;
  /** Displayed toughness; see {@link CardView.power}. Present only for creatures. */
  toughness?: string;
  /**
   * The card's keyword abilities as lowercase wire names (e.g. `"flying"`,
   * `"first_strike"`), server-computed for display. The client renders badges and
   * never derives them. Omitted (treated as empty) when the card has none.
   */
  keywords?: string[];
}

/**
 * What the receiving player may know about an opponent: hidden zones are reduced
 * to counts, public state is exact.
 */
export interface OpponentView {
  /** Which opponent this describes. */
  player_id: PlayerId;
  /** Number of cards in hand (contents hidden). */
  hand_size: number;
  /** Current life total. */
  life: number;
  /** Number of cards left in library. */
  library_size: number;
  /** Number of cards in the graveyard. */
  graveyard_size: number;
  /** Free-form status labels (e.g. `"monarch"`) for display only. */
  statuses?: string[];
  /** Whether this opponent has been eliminated — they left the game (CR 800.4a,
   * issue #342/#345). Omitted (treated as `false`) in a two-player game. */
  eliminated?: boolean;
}

/**
 * The receiver's own public stats — the self-counterpart of {@link OpponentView}.
 * Hand contents ride in {@link GameView.my_hand} and mana in
 * {@link GameView.mana_pool}; this carries the two public numbers those omit — the
 * receiver's life total and library size — so a player can read their own life, not
 * only their opponents'. No hidden information (a player's own life and library size
 * are public). An older server may omit it; {@link normalizeGameView} defaults it.
 */
export interface SelfView {
  /** The receiver's current life total. */
  life: number;
  /** Number of cards left in the receiver's library. */
  library_size: number;
}

/** A named counter on a permanent. */
export interface Counter {
  /** Counter name, e.g. `"+1/+1"` or `"loyalty"`. */
  kind: string;
  /** How many of this counter are present. */
  count: number;
}

/** A permanent on the battlefield with its server-computed characteristics. */
export interface Permanent {
  /** Entity id of this permanent. */
  id: EntityId;
  /** Player who currently controls it. */
  controller: PlayerId;
  /** Player who owns it (matters when control changes). */
  owner: PlayerId;
  /** The permanent's current (computed) card face. */
  card: CardView;
  /** Whether the permanent is tapped. Omitted (defaults to `false`) when untapped. */
  tapped?: boolean;
  /**
   * Whether this permanent is currently attacking — declared as an attacker this
   * combat (CR 508). Server-computed; the client displays it and never derives it.
   * Omitted (treated as `false`) when it is not attacking.
   */
  attacking?: boolean;
  /**
   * The defending player this permanent is attacking (CR 508.1a) as their
   * {@link EntityId} — the multiplayer generalization of {@link attacking} (issue
   * #341/#345). Omitted when not attacking; a two-player client may ignore it since
   * the sole opponent is the only defender. Server-computed; never derived.
   */
  attacking_player?: EntityId;
  /**
   * The permanent this one is blocking, if it was declared as a blocker this combat
   * (CR 509): the attacker's {@link EntityId}. Omitted when it is not blocking.
   * Several blockers may name the same attacker. Server-computed; the client renders
   * the relationship and derives no legality from it.
   */
  blocking?: EntityId;
  /**
   * Marked combat damage on this permanent this turn (CR 120.3), the value the
   * server compares against toughness. Server-computed; the client displays it
   * verbatim and never predicts it. Omitted (treated as `0`) when none is marked.
   */
  damage?: number;
  /**
   * The host permanent this one is attached to, if any (CR 303.4): an Aura names
   * the object it enchants, as that host's {@link EntityId} — the same reference
   * shape {@link Permanent.blocking} uses. Omitted for an unattached permanent.
   * The client clusters the attachment with its host and derives no rules from it.
   */
  attached_to?: EntityId;
  /** Named counters and their quantities. */
  counters?: Counter[];
}

/**
 * One object on the stack — a spell or an ability. Ability entries carry their
 * source permanent so the client can point back at it.
 */
export interface StackItem {
  /** Entity id of this stack object. */
  id: EntityId;
  /** Player who controls it (chooses targets/resolution). */
  controller: PlayerId;
  /** Spell name or ability text as it should be displayed. */
  description: string;
  /** Source permanent for an ability; absent for a spell. */
  source?: EntityId;
}

/** A public, ordered pile owned by one player (graveyard or exile). */
export interface ZonePile {
  /** Player who owns the pile. */
  player_id: PlayerId;
  /** Cards in zone order (top last). */
  cards: CardView[];
}

/** A named entity reference carried by a structured log event. */
export interface LogEntity {
  /** Opaque entity id. */
  id: EntityId;
  /** Server-supplied display name. */
  name: string;
}

/** One declared blocker assignment. */
export interface LogBlock {
  /** Blocking permanent. */
  blocker: LogEntity;
  /** Attacked permanent. */
  attacker: LogEntity;
}

/** What a `damage_dealt` event was dealt to: a player or a permanent. */
export type LogDamageTarget =
  { kind: 'player'; player: PlayerId } | { kind: 'permanent'; permanent: LogEntity };

/** A structured, receiver-safe game-history event. */
export type GameLogEvent =
  | { type: 'spell_cast'; player: PlayerId; card: LogEntity }
  | { type: 'spell_resolved'; player: PlayerId; card: LogEntity }
  | { type: 'spell_countered'; player: PlayerId; card: LogEntity }
  | { type: 'spell_fizzled'; player: PlayerId; card: LogEntity }
  | { type: 'attackers_declared'; player: PlayerId; attackers: LogEntity[] }
  | { type: 'blockers_declared'; player: PlayerId; blocks: LogBlock[] }
  | { type: 'mulligan'; player: PlayerId }
  | { type: 'hand_kept'; player: PlayerId }
  | { type: 'life_changed'; player: PlayerId; amount: number }
  | { type: 'damage_dealt'; target: LogDamageTarget; amount: number }
  | { type: 'cards_drawn'; player: PlayerId; count: number }
  | { type: 'permanent_died'; permanent: LogEntity }
  | { type: 'step_changed'; turn: number; active_player: PlayerId; phase: Phase }
  | { type: 'player_eliminated'; player: PlayerId; reason: GameOverReason }
  | { type: 'game_over'; result: GameResult };

/** One sequence-numbered entry in the authoritative recent game-history window. */
export interface GameLogEntry {
  /** Monotonically increasing server sequence number. */
  sequence: number;
  /** Event payload rendered as client-local prose. */
  event: GameLogEvent;
}

/**
 * Every `Phase` value in turn order, for runtime validation of the wire. This is
 * the single source of truth: the {@link Phase} union is derived from it, so a
 * value added here can never drift out of the type (and vice versa). Mirrors the
 * `Phase` enum's snake_case serde encoding in `crates/rune-protocol/src/lib.rs`.
 */
export const PHASES = [
  'untap',
  'upkeep',
  'draw',
  'precombat_main',
  'begin_combat',
  'declare_attackers',
  'declare_blockers',
  'combat_damage',
  'end_combat',
  'postcombat_main',
  'end',
  'cleanup',
] as const;

/** The current turn step; one of {@link PHASES}. */
export type Phase = (typeof PHASES)[number];

/**
 * One choice step of a multi-step {@link ValidAction}: a single target slot the
 * player must fill, listing exactly the legal candidates the server computed. The
 * client renders the prompt, highlights the candidates, and computes NO legality
 * of its own (ADR 0009 §Client) — it only ever offers these ids.
 */
export interface TargetRequirement {
  /** Opaque slot id the client echoes back as {@link TargetChoice.slot}. */
  slot: string;
  /** Human-readable prompt describing what to choose, e.g. `"target creature"`. */
  prompt: string;
  /**
   * The legal candidate entity ids for this slot — the **only** choices the
   * client may offer. Enumerated O(N) per slot by the server; the client never
   * derives or filters them. Omitted (treated as empty) when there is none.
   */
  candidates?: EntityId[];
}

/** One named choice of a {@link OptionPrompt} slot: an opaque `id` the client
 * echoes back and a human-readable `label` to render. */
export interface PromptOption {
  /** Opaque id echoed back as the slot's chosen value. Never parsed. */
  id: string;
  /** Human-readable label to render for this choice. */
  label: string;
}

/**
 * Pick exactly one of N named choices — the clean shape for a modal choice or a
 * yes/no (e.g. the mulligan keep/take-another decision). Answered with the chosen
 * {@link PromptOption.id} as the slot's single {@link TargetChoice.chosen} entry.
 */
export interface OptionPrompt {
  /** Discriminator. */
  kind: 'option';
  /** Opaque slot id the client echoes back as {@link TargetChoice.slot}. */
  slot: string;
  /** Human-readable prompt describing the decision. */
  prompt: string;
  /** The named choices — the only answers the client may submit. */
  options?: PromptOption[];
}

/**
 * Pick {@link SelectFromZonePrompt.count} entity ids from a zone (cleanup
 * discard-to-max, mulligan bottoming, future tutors). Answered with the selected
 * ids in {@link TargetChoice.chosen}; each must be one of `candidates`.
 */
export interface SelectFromZonePrompt {
  /** Discriminator. */
  kind: 'select_from_zone';
  /** Opaque slot id the client echoes back as {@link TargetChoice.slot}. */
  slot: string;
  /** Human-readable prompt describing what to select. */
  prompt: string;
  /** The zone the cards come from, e.g. `"hand"` (display context; free-form). */
  zone: string;
  /** The player who owns the zone being selected from. */
  owner: PlayerId;
  /** Exactly how many ids must be chosen. */
  count: number;
  /** The legal candidate entity ids — the only ids the client may pick. */
  candidates?: EntityId[];
}

/**
 * Arrange N items into an order (ordering simultaneous triggers, scry). Answered
 * with all of {@link OrderPrompt.items} in the chosen order in
 * {@link TargetChoice.chosen} (a permutation of `items`).
 */
export interface OrderPrompt {
  /** Discriminator. */
  kind: 'order';
  /** Opaque slot id the client echoes back as {@link TargetChoice.slot}. */
  slot: string;
  /** Human-readable prompt describing what to order. */
  prompt: string;
  /** The items to arrange, in their initial order. */
  items?: EntityId[];
}

/**
 * A non-target choice slot a {@link ValidAction} may pose, a generalization of the
 * {@link TargetRequirement} slot pattern (slot + prompt + candidates, bound by the
 * action's content {@link ValidAction.token}, ADR 0009) to three richer shapes.
 * The `kind` tag discriminates the shape on the wire; every shape is answered by a
 * {@link TargetChoice} keyed by `slot` and submitted atomically. Clients tolerate
 * an unknown future `kind`.
 */
export type Prompt = OptionPrompt | SelectFromZonePrompt | OrderPrompt;

/**
 * One entry of {@link GameView.valid_actions}: the only source of interactivity.
 * `subject` names the entities an action belongs to so the client can render it
 * ON the entity rather than in a global bar (ADR 0004).
 *
 * A multi-step action (a targeted spell/ability) also carries an ordered
 * {@link ValidAction.requirements} list, and/or a {@link ValidAction.prompts} list
 * of the non-target choice shapes, that the client walks as one prompt queue, plus
 * a content-binding {@link ValidAction.token} it echoes verbatim in the answer
 * (ADR 0009 §Protocol). All are absent for a plain, no-choice action.
 */
export interface ValidAction {
  /** Opaque id the client echoes back in a {@link ChooseAction} to take it. */
  id: string;
  /**
   * Coarse action category (e.g. `"pass_priority"`, `"activate_ability"`). A
   * free-form string, not a union, so new kinds do not break older clients.
   */
  type: string;
  /** Human-readable label to render for this action. */
  label: string;
  /** Entity ids this action belongs to; empty for global actions. */
  subject?: EntityId[];
  /**
   * Whether this action activates a **mana ability** (CR 605): it targets
   * nothing, does not use the stack, and only produces mana. Server-computed so
   * the client can offer a lighter gesture — one-click tap-for-mana (ADR 0025)
   * — for exactly these actions without ever classifying abilities itself.
   * Omitted when false.
   */
  mana_ability?: boolean;
  /**
   * Ordered choice steps this action requires before it can be taken — one per
   * target slot. The client walks them as a prompt queue and answers every slot
   * **atomically** in a single {@link ChooseAction}, never a stateful
   * multi-message handshake. Absent/empty for a plain action.
   */
  requirements?: TargetRequirement[];
  /**
   * Non-target choice slots this action poses (option / select_from_zone / order,
   * issue #156), a generalization of {@link ValidAction.requirements}. The client
   * walks them as part of the same prompt queue and answers each slot with a
   * {@link TargetChoice} keyed by `slot`. Absent for a plain action.
   */
  prompts?: Prompt[];
  /**
   * Content-binding token: an opaque server-issued value bound to this action's
   * exact content (subject + requirements + prompts). The client echoes it back
   * **verbatim** in {@link ChooseAction.token} and never parses or derives it; the
   * server rejects an answer whose token does not match. Absent only for a legacy
   * unbound action.
   */
  token?: string;
}

/**
 * Every {@link GameOverReason} value, mirroring the `GameOverReason` enum's
 * snake_case serde encoding in `crates/rune-protocol/src/lib.rs`. This is the
 * single source of truth: the {@link GameOverReason} union is derived from it and
 * {@link isGameOverReason} validates a wire value against it, so a reason added
 * here can never drift out of the type (and vice versa).
 */
export const GAME_OVER_REASONS = ['life_zero', 'decked', 'concede'] as const;

/**
 * Why a game ended (CR 104.3 / CR 704.5), a closed snake_case enum; one of
 * {@link GAME_OVER_REASONS}:
 * - `life_zero` — a player was reduced to 0 or less life (CR 704.5a).
 * - `decked` — a player attempted to draw from an empty library (CR 704.5c).
 * - `concede` — a player conceded (CR 104.3a).
 */
export type GameOverReason = (typeof GAME_OVER_REASONS)[number];

/** Whether a wire value is a known {@link GameOverReason}. */
export function isGameOverReason(value: unknown): value is GameOverReason {
  return typeof value === 'string' && (GAME_OVER_REASONS as readonly string[]).includes(value);
}

/**
 * The terminal outcome of a game (CR 104.2a), present on a {@link GameView} only
 * once the game is over. While the game is live the field is omitted entirely (the
 * empty-optional convention), so its mere presence signals game over to a client.
 * The client renders this; it never decides a winner or terminality itself.
 */
export interface GameResult {
  /**
   * The winning player (CR 104.2a). Absent for a draw, where every remaining
   * player lost at once (CR 104.4a).
   */
  winner?: PlayerId;
  /** The players who lost, in seat order. */
  losers: PlayerId[];
  /** Why the game ended. */
  reason: GameOverReason;
}

/**
 * The personalized state the server sends after every change. A client must be
 * able to fully reconstruct its UI from a single `GameView` — no client state is
 * load-bearing across messages. Optional collections may be omitted on the wire
 * and MUST be treated as their empty default (see {@link normalizeGameView}).
 */
export interface GameView {
  /**
   * The receiver's own seat entity id (the `p{N}` form used for players
   * throughout the view). The client uses this to identify itself rather than
   * inferring it from the zones. An older server may omit it on the wire, in
   * which case {@link normalizeGameView} defaults it to `''`.
   */
  you: PlayerId;
  /** Full card objects for the receiving player only. */
  my_hand: CardView[];
  /**
   * The receiver's own public stats (life total, library size) — see
   * {@link SelfView}. An older server may omit it; {@link normalizeGameView}
   * defaults it to a zero placeholder.
   */
  me: SelfView;
  /** Redacted views of every other player. */
  opponents: OpponentView[];
  /** All permanents in play. */
  battlefield: Permanent[];
  /** The stack, bottom first. */
  stack: StackItem[];
  /** Each player's graveyard. */
  graveyards: ZonePile[];
  /** Each player's exile zone. */
  exile: ZonePile[];
  /** The current turn step. */
  phase: Phase;
  /**
   * The current turn number (1-based; `0` only in an empty/pre-game state). The
   * server owns turn counting — the client renders this and never counts turns
   * itself. Defaulted to `0` by {@link normalizeGameView} when an older server
   * omits it.
   */
  turn: number;
  /**
   * The player whose turn it is (the active player), as a `p{N}` id. Distinct from
   * {@link GameView.priority_player}: the active player owns the turn even while an
   * opponent holds priority. Defaulted to `''` (unknown) when an older server omits
   * it.
   */
  active_player: PlayerId;
  /**
   * The table's seat order: every player id (`p0`, `p1`, …) in seat order, including
   * the receiver and any eliminated players (issue #345). The explicit ordering the
   * multiplayer table layout relies on. Defaulted to `[]` by {@link normalizeGameView}
   * when an older server omits it.
   */
  seat_order: PlayerId[];
  /** The receiving player's unspent mana, as pip strings (e.g. `["{G}"]`). */
  mana_pool: string[];
  /** The player who currently holds priority, if any. */
  priority_player?: PlayerId;
  /** The only source of interactivity: what the receiving player may do now. */
  valid_actions: ValidAction[];
  /** Seconds remaining for the pending decision, if a clock is running. */
  action_deadline?: number;
  /**
   * The terminal result once the game is over (winner/losers/reason, CR 104.2a).
   * Absent while the game is live (the empty-optional convention), so its presence
   * alone tells a client the game has ended; when present, `valid_actions` is empty.
   */
  result?: GameResult;
  /** Bounded structured log window; older servers may omit it. */
  log?: GameLogEntry[];
  /**
   * The receiver's own current **priority-stop preferences** (issue #264, ADR 0020):
   * the steps at which they want priority even when the engine reports no meaningful
   * action, so basic auto-pass does not skip them there. Carried on the view so the
   * per-phase stops UI is reconstructable from a single message and survives reconnect
   * (the preferences live on the server, not in client memory). The client renders
   * toggles from this and answers with a {@link SetStopsMessage}. Omitted (treated as
   * empty — "stop nowhere", the default) by the server when empty;
   * {@link normalizeGameView} defaults it to `[]`.
   */
  stops?: Phase[];
  /**
   * Whether reaching this state **auto-passed** priority on the receiver's behalf
   * (issue #264, ADR 0020): set on the broadcast that follows a settle in which the
   * server passed priority for this seat, so the client can show a display-only
   * "passed for you" indicator. Advisory and transient — the UI reconstructs fully
   * without it. Omitted (treated as `false`) when the seat was not auto-passed.
   */
  auto_passed?: boolean;
  /**
   * Whether this view answers a **rejected in-game action** by the receiver (issue
   * #265): a stale-view race meant the chosen action was no longer on offer, so the
   * server re-sent the current state unchanged and flagged that one re-send. Advisory
   * and transient like {@link auto_passed} — `valid_actions` already reflects the true
   * legal set, so the client shows only a brief, non-blaming "the game moved on" toast
   * (ephemeral presentation, never load-bearing). Omitted (treated as `false`) on every
   * normal broadcast and resync; {@link normalizeGameView} defaults it to `false`.
   */
  action_rejected?: boolean;
  /**
   * Public display names keyed by {@link PlayerId} (issue #294): every player who has
   * chosen a name maps to it, so any in-game surface (turn indicator, player tiles,
   * zone-browser titles, game-over verdict) can label any player — `you`, an opponent,
   * the active/priority player, a winner — without a lobby round-trip. Names never
   * replace the `p{N}` id an action echoes back. A player with no name has no entry;
   * the server omits the field entirely when empty and {@link normalizeGameView}
   * defaults it to `{}`, so an older server that never sends names keeps working.
   */
  player_names: Record<PlayerId, string>;
}

/**
 * The state a **spectator** connection receives (ADR 0022, issue #351): a non-seated
 * observer watching a live game with all hidden information redacted **by
 * construction**. It reuses {@link GameView}'s public component types but carries no
 * receiver fields — there is no `you`, `me`, `my_hand`, `mana_pool`, `valid_actions`,
 * `action_deadline`, or per-seat prompt, so the client's spectate mode can never even
 * read a hand or a decision surface. Every seat is a public {@link OpponentView}; a
 * spectator reconstructs the whole public board from a single `SpectatorView`.
 */
export interface SpectatorView {
  /** Every player at the table as public state — no privileged "self". */
  players: OpponentView[];
  /** All permanents in play. */
  battlefield: Permanent[];
  /** The stack, bottom first. */
  stack: StackItem[];
  /** Each player's public graveyard. */
  graveyards: ZonePile[];
  /** Each player's public exile zone. */
  exile: ZonePile[];
  /** The current turn step. */
  phase: Phase;
  /** The current turn number (1-based). */
  turn: number;
  /** The player whose turn it is. */
  active_player: PlayerId;
  /** Every seat's id in seat order, including eliminated players. */
  seat_order: PlayerId[];
  /** The player currently holding priority, if any (whose turn it is to act). */
  priority_player?: PlayerId;
  /** The terminal result once the game is over; absent while live. */
  result?: GameResult;
  /** Bounded structured public log window. */
  log?: GameLogEntry[];
  /** Public display names keyed by player id. */
  player_names: Record<PlayerId, string>;
}

/**
 * The player's answer to one choice slot — a {@link TargetRequirement} or a
 * {@link Prompt} — keyed back to the slot by `slot`. The same shape answers every
 * slot kind; each id must be one of that slot's advertised candidates / options /
 * items or the server treats the action as a no-op.
 */
export interface TargetChoice {
  /** The {@link TargetRequirement} or {@link Prompt} slot this answers. */
  slot: string;
  /**
   * The entity ids chosen for this slot: a target id; the chosen
   * {@link PromptOption.id} for an option; the selected ids for a select-from-zone;
   * or the full ordering for an order prompt.
   */
  chosen?: EntityId[];
}

/**
 * The client's chosen action, answered atomically: the `id` of one issued
 * `valid_actions` entry, its content-binding {@link ChooseAction.token} echoed
 * verbatim, and one {@link ChooseAction.targets} entry per requirement slot.
 * Serializes with a `type` discriminator (`{"type":"choose_action", ...}`),
 * matching the `ClientMessage::ChooseAction` variant. `token` and `targets` are
 * omitted when empty, so a plain action's message is just the id.
 */
export interface ChooseAction {
  /** Discriminator for the client→server message envelope. */
  type: 'choose_action';
  /** The `id` of the chosen {@link ValidAction}. */
  action_id: string;
  /** The chosen action's {@link ValidAction.token}, echoed verbatim (or omitted). */
  token?: string;
  /** One entry per {@link ValidAction.requirements} slot; omitted when empty. */
  targets?: TargetChoice[];
}

/**
 * Build the client→server envelope for choosing an issued action. `token` (the
 * chosen action's content-binding token) and `targets` (the assembled per-slot
 * selection) are included only when present, so a plain action stays a bare id —
 * this is pure envelope assembly, never legality or effect computation.
 */
export function chooseAction(
  actionId: string,
  token?: string,
  targets?: TargetChoice[],
): ChooseAction {
  const message: ChooseAction = { type: 'choose_action', action_id: actionId };
  if (token !== undefined && token !== '') message.token = token;
  if (targets !== undefined && targets.length > 0) message.targets = targets;
  return message;
}

/**
 * Set (or replace) this connection's **priority-stop preferences** (issue #264): the
 * steps at which the seat wants priority even when it has no meaningful action, so
 * basic auto-pass does not skip it there. Serializes with the same tagged envelope as
 * {@link ChooseAction} (`{"type":"set_stops", ...}`), matching the
 * `ClientMessage::SetStops` variant. The set replaces the seat's current one wholesale;
 * an empty set (omitted `stops`) clears all stops. Server-authoritative and
 * reconnect-durable — the server stores it per seat and reflects it in
 * {@link GameView.stops}; the client computes no legality here.
 */
export interface SetStopsMessage {
  /** Discriminator for the client→server message envelope. */
  type: 'set_stops';
  /** The steps to stop at; omitted when clearing all stops. */
  stops?: Phase[];
}

/** Build a `set_stops` message, eliding `stops` when the set is empty (clear all). */
export function setStopsMessage(stops: Phase[]): SetStopsMessage {
  const message: SetStopsMessage = { type: 'set_stops' };
  if (stops.length > 0) message.stops = stops;
  return message;
}

// ---------------------------------------------------------------------------
// Lobby protocol — the pre-game analogue of the two in-game messages
// (docs/protocol.md "Lobby phase"; docs/decisions/0012-lobby-protocol.md).
//
// The server pushes a full {@link LobbyView} on every change and the client
// rebuilds its entire pre-game UI (identity, room, seat roster, who is
// decked/ready) from that one message. {@link LobbyView.valid_commands} is the
// only source of interactivity, exactly as `valid_actions` is in `GameView`; the
// client computes no legality. Once a game is constructed the connection switches
// to the in-game `GameView`/`ChooseAction` contract for the life of that game.
//
// These shapes mirror the `rune-protocol` crate; any change is a contract change.
// ---------------------------------------------------------------------------

/**
 * Server-issued opaque session/reconnect token. The client stores it and echoes
 * it verbatim on a later {@link HelloCommand} (after a refresh or dropped socket).
 * It is an identity handle only — never parsed, never authentication of a human.
 */
export type SessionToken = string;

/** Opaque room id, issued on {@link CreateRoomCommand} and shared out-of-band. */
export type RoomId = string;

/** Opaque game-setup id carried in a {@link RoomConfig}; the server validates it. */
export type GameSetupId = string;

/**
 * Opaque card-identity handle in a submitted decklist. These are card
 * *identities*, never printings or images (project legal rules); the server
 * validates each against its card database and the client never parses them.
 */
export type CardIdentity = string;

/** A room's configuration, supplied by the creator and echoed in every view. */
export interface RoomConfig {
  /** Number of seats, validated server-side into the inclusive range `2..=8`. */
  seats: number;
  /** Opaque game-setup id naming which setup the room builds its game from. */
  game_setup: GameSetupId;
}

/**
 * One seat in a room's roster, as any connection sees it. Hidden information
 * stays redacted: a seat's decklist contents are never exposed, only that the
 * seat is decked.
 */
export interface SeatView {
  /** Zero-based seat index within the room. */
  seat: number;
  /** The player occupying this seat; absent when the seat is empty. */
  occupied_by?: PlayerId;
  /**
   * The occupant's chosen display name (issue #294), if set — public, display-only
   * text. The seat's identity is still its {@link SeatView.occupied_by} id. Absent for
   * an empty or unnamed seat, in which case the client falls back to a seat-derived
   * label (e.g. `"Player 2"`), so an older server that omits names keeps working.
   */
  name?: string;
  /** Whether this seat has submitted a server-validated deck (defaults `false`). */
  decked?: boolean;
  /** Whether this seat has declared itself ready (defaults `false`). */
  ready?: boolean;
}

/** The room a connection is in, with its config and full seat roster. */
export interface RoomView {
  /** The room's opaque id, shared to invite a second player. */
  room_id: RoomId;
  /** The room's configuration. */
  config: RoomConfig;
  /** Every seat in the room, in seat order. */
  seats: SeatView[];
}

/**
 * A room's lifecycle state in the lobby {@link LobbyView.directory} (issue #280):
 * `gathering` (pre-game, joinable while it has an open seat) or `in_progress` (its
 * game has started — visible for context but not joinable). A finished or emptied
 * room leaves the directory entirely. A client tolerates an unknown future value.
 */
export type RoomState = 'gathering' | 'in_progress';

/**
 * One room as it appears in the public room **directory** — enough to browse and
 * join an open game without an out-of-band id, and no more. It carries no seat
 * roster and no player-identifying info beyond the occupancy count, and never any
 * game state.
 */
export interface RoomSummary {
  /** The room's opaque id — the same id a `join_room` command carries. */
  room_id: RoomId;
  /** The room's configuration (seat count and game setup). */
  config: RoomConfig;
  /** How many of the room's seats are occupied; the total is `config.seats`. */
  filled: number;
  /**
   * How many observers are watching the room (issue #351). Spectators do not
   * consume seats, so this is independent of {@link RoomSummary.filled}; a count
   * only, never a spectator's identity. Defaults to `0` when the server omits it.
   */
  spectators: number;
  /** The room's lifecycle state (`gathering` or `in_progress`). */
  state: RoomState;
}

/**
 * The full pre-game state for one connection, pushed on every change — the
 * pre-game analogue of {@link GameView}. The client rebuilds its entire pre-game
 * UI from a single `LobbyView` (reconnect-safe by construction) and derives no
 * legality: {@link LobbyView.valid_commands} is the only source of interactivity.
 */
export interface LobbyView {
  /**
   * The connection's session/reconnect token (private — the client's own handle,
   * distinct from the public {@link LobbyView.you}). Always present on the wire;
   * defaulted to `''` if a payload omits it.
   */
  session: SessionToken;
  /**
   * The connection's public player identity, used to match itself against a
   * {@link SeatView.occupied_by}. Defaults to `''` when absent.
   */
  you: PlayerId;
  /**
   * The connection's own chosen display name (issue #294), if set via a
   * {@link SetNameCommand}. Lets the pre-game UI show the local player's name before a
   * seat exists; once seated, the same name also rides in the roster's
   * {@link SeatView.name}. Absent when unset.
   */
  name?: string;
  /** The room the connection is in, if any. Absent when not in a room. */
  room?: RoomView;
  /**
   * The public room **directory** (issue #280): every browsable room in the lobby,
   * so a player can discover and join an open game without an out-of-band id. Each
   * entry is a {@link RoomSummary} (id, config, occupancy, lifecycle state); no seat
   * roster or player-identifying info, and no game state. Pushed on every room
   * lifecycle change. Elided on the wire when empty; {@link normalizeLobbyView}
   * defaults it to an empty array.
   */
  directory: RoomSummary[];
  /**
   * The lobby command kinds currently legal for this connection (e.g.
   * `"create_room"`, `"join_room"`, `"submit_deck"`, `"ready"`, `"unready"`,
   * `"leave"`). Free-form strings; the client renders exactly these and tolerates
   * unknown kinds, computing no legality of its own.
   */
  valid_commands: string[];
}

/**
 * The current schema version carried in {@link CatalogView.catalog_version}. A single
 * frame carries the whole catalog today; the version leaves room to add paging later
 * without breaking older clients (issue #367).
 */
export const CATALOG_VERSION = 1;

/**
 * One supported card's public characteristics in the lobby {@link CatalogView} (issue
 * #367) — the browse-time counterpart of the in-game {@link CardView}. It carries the
 * card's stable identity and the same server-computed characteristics (including the
 * generated rules text) but no per-game entity id, since a catalog entry names a card by
 * identity, not a specific instance.
 */
export interface CatalogCard {
  /** Stable functional identity (ADR 0018 §3) — the same handle a decklist uses. */
  functional_id: CardIdentity;
  /** Display name. */
  name: string;
  /** Full type line, incl. any basic supertype, e.g. `"Basic Land — Forest"`. */
  type_line: string;
  /** Displayed mana cost string, e.g. `"{1}{G}"`. Absent for a card without one. */
  mana_cost?: string;
  /**
   * Rules text, generated by the server from the card's ability IR — identical to what
   * an in-game {@link CardView.rules_text} shows (ADR 0018). Omitted (treated as `""`)
   * for a vanilla card with no rules.
   */
  rules_text?: string;
  /** Displayed power (a string so `*` round-trips). Present only for creatures. */
  power?: string;
  /** Displayed toughness; see {@link CatalogCard.power}. Present only for creatures. */
  toughness?: string;
  /** Keyword abilities as lowercase wire names (e.g. `"flying"`). Omitted when empty. */
  keywords?: string[];
}

/**
 * One advertised format's public deck rules and seat range in the lobby
 * {@link CatalogView} (issue #367, ADR 0013 §4) — exactly the server-side deck-legality
 * policy a `submit_deck` is validated against, so a client can build a legal deck ahead
 * of time. A permissive format advertises its permissiveness honestly, as absent (`None`)
 * upper bounds rather than a sentinel number.
 */
export interface CatalogFormat {
  /** The `game_setup` id naming this format — the same id a {@link RoomConfig} carries. */
  game_setup: GameSetupId;
  /** Fewest cards a legal deck may hold (inclusive); `0` for no minimum. */
  min_deck_size: number;
  /** Most cards a legal deck may hold (inclusive); absent for no upper bound. */
  max_deck_size?: number;
  /** Most copies of any single non-exempt card; absent for **no copy limit**. */
  max_copies?: number;
  /** Whether basic lands are exempt from {@link CatalogFormat.max_copies} (CR 100.2a). */
  basic_land_exempt: boolean;
  /** Fewest seats a room using this format may have (inclusive). */
  min_seats: number;
  /** Most seats a room using this format may have (inclusive). */
  max_seats: number;
}

/**
 * The public card catalog and format deck rules — a lobby-phase server→client frame
 * answered to a {@link RequestCatalogCommand} (issue #367). A versioned single-frame
 * projection of the complete supported card pool and every advertised format, built
 * server-side from the one embedded card database and the format registry. Public data
 * only — never a deck, roster, or game state. It is distinguished on the wire from a
 * {@link LobbyView} by its `catalog_version` field and from a {@link GameView} /
 * {@link SpectatorView} by carrying no `phase`.
 */
export interface CatalogView {
  /** The projection's schema version ({@link CATALOG_VERSION}); also the wire discriminator. */
  catalog_version: number;
  /** Every supported card, in a stable order. */
  cards: CatalogCard[];
  /** Every advertised format's deck rules and seat range. */
  formats: CatalogFormat[];
}

/** First-contact / reconnect command; carries a prior token when reconnecting. */
export interface HelloCommand {
  /** Discriminator. */
  type: 'hello';
  /** A previously issued session token to reclaim a held-open seat (or omitted). */
  token?: SessionToken;
}

/** Create a new room with the given config; the reply carries the new room id. */
export interface CreateRoomCommand {
  /** Discriminator. */
  type: 'create_room';
  /** The configuration for the new room. */
  config: RoomConfig;
}

/** Join an existing room by id (no matchmaking or discovery). */
export interface JoinRoomCommand {
  /** Discriminator. */
  type: 'join_room';
  /** The opaque id of the room to join. */
  room_id: RoomId;
}

/**
 * Watch an in-progress room as a spectator (ADR 0022, issue #351): a non-seated
 * observer receiving redacted {@link SpectatorView}s. Unlike `join_room` it consumes
 * no seat and succeeds on a full room, but the room's game must already be running.
 */
export interface SpectateRoomCommand {
  /** Discriminator. */
  type: 'spectate_room';
  /** The opaque id of the room to spectate. */
  room_id: RoomId;
}

/** Submit a decklist for this connection's seat (server-validated). */
export interface SubmitDeckCommand {
  /** Discriminator. */
  type: 'submit_deck';
  /** The card identities, duplicates repeated; omitted when empty. */
  cards?: CardIdentity[];
}

/** Declare or retract readiness for this connection's seat. */
export interface ReadyCommand {
  /** Discriminator. */
  type: 'ready';
  /** `true` to ready up, `false` to un-ready. */
  ready: boolean;
}

/**
 * Set (or change) this connection's public display name (issue #294). The server
 * validates it (length bounds, printable characters) and rejects an invalid value
 * with the lobby's non-fatal error pattern (the current {@link LobbyView} is
 * re-sent). The name is bound to the session, so it survives a per-tab reconnect.
 */
export interface SetNameCommand {
  /** Discriminator. */
  type: 'set_name';
  /** The requested display name; the server trims and validates before storing. */
  name: string;
}

/**
 * Request the public card catalog and per-format deck rules (issue #367). The server
 * replies with a one-shot {@link CatalogView} and changes no lobby state, so a
 * connection can browse the supported card pool without joining or starting a game.
 */
export interface RequestCatalogCommand {
  /** Discriminator. */
  type: 'request_catalog';
}

/** Leave the current room, vacating the seat. */
export interface LeaveCommand {
  /** Discriminator. */
  type: 'leave';
}

/**
 * Everything a client can send in the lobby phase, a single tagged message
 * structurally parallel to {@link ChooseAction}. The server validates every
 * command against authoritative state and answers with a fresh {@link LobbyView};
 * an invalid command is rejected and the current `LobbyView` re-sent.
 */
export type LobbyCommand =
  | HelloCommand
  | CreateRoomCommand
  | JoinRoomCommand
  | SpectateRoomCommand
  | SubmitDeckCommand
  | ReadyCommand
  | SetNameCommand
  | RequestCatalogCommand
  | LeaveCommand;

/** Build a `hello` command, including a prior token only when present. */
export function helloCommand(token?: SessionToken): HelloCommand {
  const message: HelloCommand = { type: 'hello' };
  if (token !== undefined && token !== '') message.token = token;
  return message;
}

/** Build a `create_room` command for the given config. */
export function createRoomCommand(config: RoomConfig): CreateRoomCommand {
  return { type: 'create_room', config };
}

/** Build a `join_room` command for the given room id. */
export function joinRoomCommand(roomId: RoomId): JoinRoomCommand {
  return { type: 'join_room', room_id: roomId };
}

/** Build a `spectate_room` command for the given room id (issue #351). */
export function spectateRoomCommand(roomId: RoomId): SpectateRoomCommand {
  return { type: 'spectate_room', room_id: roomId };
}

/** Build a `submit_deck` command, eliding `cards` when the decklist is empty. */
export function submitDeckCommand(cards: CardIdentity[]): SubmitDeckCommand {
  const message: SubmitDeckCommand = { type: 'submit_deck' };
  if (cards.length > 0) message.cards = cards;
  return message;
}

/** Build a `ready` command declaring (`true`) or retracting (`false`) readiness. */
export function readyCommand(ready: boolean): ReadyCommand {
  return { type: 'ready', ready };
}

/** Build a `set_name` command requesting the given display name (issue #294). */
export function setNameCommand(name: string): SetNameCommand {
  return { type: 'set_name', name };
}

/** Build a `request_catalog` command (issue #367). */
export function requestCatalogCommand(): RequestCatalogCommand {
  return { type: 'request_catalog' };
}

/** Build a `leave` command. */
export function leaveCommand(): LeaveCommand {
  return { type: 'leave' };
}
