version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, area:engine]
  - package-ecosystem: npm
    directory: /clients/web
    schedule:
      interval: weekly
    labels: [dependencies, area:client]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
