/**
 * Deterministic synthesis of the Rune card-frame plates (issue #570).
 *
 * The frame is the one presentation surface that had no generated material
 * behind it: it was drawn entirely in CSS from tokens, so a card could only
 * ever be a flat rectangle with borders on it. This module produces the
 * material the frame is made of — bevel, edge, seam, and printed surface — as
 * nine-sliceable plates the DOM renderer composes.
 *
 * Three properties make these plates different from the illustrated asset sets
 * (environments, portraits, card art), and all three are deliberate:
 *
 * 1. **They are alpha light maps, not pictures.** A plate carries highlight,
 *    shadow, grain, and (on the frame edge only) the structural gold hairline —
 *    nothing else. Every body colour still arrives from `src/tokens.ts` through
 *    a CSS custom property and shows through the plate, so ADR 0019 holds, both
 *    environment themes are served by one set, and a future light mode needs no
 *    second set. It also means colour identity keeps its material instead of
 *    becoming the flat colour block `docs/design/card-representation.md` §3.4
 *    forbids: the identity weave is tinted by `--face-accent` at composite time.
 * 2. **They are generated by this committed script, not by a model.** Frame
 *    material is measured geometry — the bevel has to land exactly on
 *    `RUNE_FRAME.ruleInset`, at every tier — so the tool is arithmetic, and the
 *    provenance is ADR 0031 class 1 (original work created for RUNE) rather
 *    than class 2. Re-running the generator reproduces the same bytes.
 * 3. **They are authored against the token ratios, not against a pixel size.**
 *    Every plate declares the fraction of the card width `W` its nine-slice
 *    band occupies; the authoring scale `k` (authored px per unit of `W`) falls
 *    out as `slice ÷ band`, and every feature inside the plate is placed at
 *    `ratio · k`. That is what makes one asset survive the hand fan and the
 *    battlefield chip: `border-image-width` is a `calc()` on `W`, so the drawn
 *    bevel is the authored ratio at every tier and in all three silhouettes.
 *
 * Nine-slice invariant, held by construction and asserted in
 * `src/assets/framePlates.test.ts`: a plate's authored corner radius is always
 * smaller than its slice, so the edge patches are uniform along their axis and
 * stretching them cannot bend a corner.
 *
 * Pure — no filesystem, no encoding. `generateFramePlates.js` is the CLI.
 */

/**
 * The `RUNE_FRAME` ratios the plates are authored against, transcribed from
 * `src/tokens.ts`. `framePlates.test.ts` fails if the two ever disagree, so a
 * token change is caught rather than silently baked into a stale asset.
 */
export const PLATE_FRAME = Object.freeze({
  radius: 0.07,
  plateRadius: 0.035,
  edge: 0.037,
  edgeBottom: 0.057,
  rule: 0.01,
  ruleInset: 0.063,
});

/**
 * The one hue the plates bake: the frame's structural gold hairline
 * (`RUNE_GOLD`). It is not a theme or identity channel — §3.4 makes gold
 * structural and identity an accent — so it is safe to carry in the material.
 */
export const PLATE_GOLD = Object.freeze({ rule: '#C7A46A', ruleShade: '#8A7042' });

/** The implied key light: high and to the left (`visual-system.md` §3). */
const LIGHT = Object.freeze({ x: -Math.SQRT1_2, y: -Math.SQRT1_2 });

/** Grain amplitude, in alpha. Low enough to read as a surface, not as noise. */
const GRAIN = 0.028;

/**
 * The shipped plate set. `band` is the fraction of the card width `W` the
 * plate's nine-slice band occupies — the value `theme.ts` publishes as the
 * `border-image-width` — and `slice` is that same band in authored px, so the
 * authoring scale is `slice ÷ band` px per unit of `W`.
 *
 * `fill` marks the plates whose middle patch is painted (a printed surface the
 * text sits in); the ring plates leave it out so the card body shows through.
 */
export const PLATE_SPECS = Object.freeze([
  {
    key: 'frameEdge',
    id: 'frame-edge',
    title: 'Rune frame — layered edge and inner border',
    essence:
      "The card's slate edge as a plate: outer contour, lit top/left bevel, the thicker bottom paper edge, and the engraved gold hairline on its measured inset.",
    width: 128,
    height: 128,
    slice: 30,
    band: PLATE_FRAME.ruleInset + PLATE_FRAME.rule,
    fill: false,
    radius: PLATE_FRAME.radius,
    draw: drawFrameEdge,
  },
  {
    key: 'artSeam',
    id: 'art-seam',
    title: 'Rune frame — art window surround',
    essence:
      'The seam between the art window and the frame: a recessed lip, shadowed on the light side and catching light on the far side, so the window sits in the card rather than on it.',
    width: 72,
    height: 72,
    slice: 24,
    band: 0.04,
    fill: false,
    radius: PLATE_FRAME.plateRadius,
    draw: drawArtSeam,
  },
  {
    key: 'headerField',
    id: 'header-field',
    title: 'Rune frame — name/cost header field',
    essence:
      'A raised printed field for the title band: lit top rim, shaded lower rim, and a fine paper grain across the surface the name and cost sit in.',
    width: 96,
    height: 48,
    slice: 20,
    band: 0.04,
    fill: true,
    radius: PLATE_FRAME.plateRadius,
    draw: (canvas, k) => drawSurface(canvas, k, { raised: true, sweep: 0.07 }),
  },
  {
    key: 'infoStrip',
    id: 'info-strip',
    title: 'Rune frame — lower information strip',
    essence:
      'A recessed printed strip for the type line and rules area: shadowed upper rim, lit lower rim, paper grain — a surface the text sits in rather than on.',
    width: 96,
    height: 48,
    slice: 20,
    band: 0.04,
    fill: true,
    radius: PLATE_FRAME.plateRadius,
    draw: (canvas, k) => drawSurface(canvas, k, { raised: false, sweep: 0.05 }),
  },
  {
    key: 'statusStrip',
    id: 'status-strip',
    title: 'Rune frame — status band surface',
    essence:
      "A recessed slate channel for the battlefield permanent's status band, cut a shade deeper than the parchment strip so the glyph and P/T plates read as objects lying in it.",
    width: 96,
    height: 48,
    slice: 20,
    band: 0.04,
    fill: true,
    radius: PLATE_FRAME.plateRadius,
    draw: (canvas, k) => drawSurface(canvas, k, { raised: false, sweep: 0.1, depth: 1.35 }),
  },
  {
    key: 'ptPlate',
    id: 'pt-plate',
    title: 'Rune frame — P/T plate',
    essence:
      'The power/toughness plate as a distinct object: a small, strongly bevelled tile with a tight radius and a contact shadow, so it reads as fixed to the card rather than printed on it.',
    width: 64,
    height: 48,
    slice: 20,
    band: 0.04,
    fill: true,
    radius: PLATE_FRAME.plateRadius / 1.5,
    draw: (canvas, k) => drawSurface(canvas, k, { raised: true, sweep: 0.09, depth: 1.5 }),
  },
  {
    key: 'identityWeave',
    id: 'identity-weave',
    title: 'Rune frame — colour-identity material',
    essence:
      'A seamless woven material tile the identity surfaces are tinted through, so a colour identity carries a surface with a light source instead of reading as a flat colour block.',
    width: 64,
    height: 64,
    slice: 0,
    band: 0,
    fill: true,
    radius: 0,
    tile: 0.5,
    draw: drawIdentityWeave,
  },
]);

/* ── Raster primitives ────────────────────────────────────────────────────── */

/**
 * A premultiplied-alpha RGBA canvas. Premultiplied storage makes `over`
 * compositing a plain lerp, which keeps the shading passes below readable.
 */
class Canvas {
  constructor(width, height) {
    this.width = width;
    this.height = height;
    this.data = new Float64Array(width * height * 4);
  }

  /** Source-over a straight-alpha colour at one pixel. */
  over(x, y, r, g, b, a) {
    if (a <= 0) return;
    const alpha = Math.min(1, a);
    const i = (y * this.width + x) * 4;
    const keep = 1 - alpha;
    this.data[i] = this.data[i] * keep + r * alpha;
    this.data[i + 1] = this.data[i + 1] * keep + g * alpha;
    this.data[i + 2] = this.data[i + 2] * keep + b * alpha;
    this.data[i + 3] = this.data[i + 3] * keep + alpha;
  }

  /** Multiply every pixel's alpha — used to clip a finished plate to its shape. */
  maskAlpha(at) {
    for (let y = 0; y < this.height; y += 1) {
      for (let x = 0; x < this.width; x += 1) {
        const m = at(x, y);
        if (m >= 1) continue;
        const i = (y * this.width + x) * 4;
        this.data[i] *= m;
        this.data[i + 1] *= m;
        this.data[i + 2] *= m;
        this.data[i + 3] *= m;
      }
    }
  }

  /** Un-premultiply into the 8-bit RGBA buffer the PNG encoder writes. */
  toRgba8() {
    const out = new Uint8Array(this.width * this.height * 4);
    for (let p = 0; p < this.width * this.height; p += 1) {
      const i = p * 4;
      const a = this.data[i + 3];
      const scale = a > 0 ? 1 / a : 0;
      out[i] = byte(this.data[i] * scale);
      out[i + 1] = byte(this.data[i + 1] * scale);
      out[i + 2] = byte(this.data[i + 2] * scale);
      out[i + 3] = byte(a);
    }
    return out;
  }
}

function byte(value) {
  return Math.max(0, Math.min(255, Math.round(value * 255)));
}

/** `#rrggbb` to a 0..1 triple. */
export function parseHex(hex) {
  const n = Number.parseInt(hex.slice(1), 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

/** Signed distance to a rounded rectangle; negative inside. */
function sdRoundRect(px, py, width, height, radius) {
  const r = Math.min(radius, width / 2, height / 2);
  const qx = Math.abs(px - width / 2) - (width / 2 - r);
  const qy = Math.abs(py - height / 2) - (height / 2 - r);
  const ax = Math.max(qx, 0);
  const ay = Math.max(qy, 0);
  return Math.hypot(ax, ay) + Math.min(Math.max(qx, qy), 0) - r;
}

/** Outward unit normal of the distance field, by central difference. */
function normalAt(field, px, py) {
  const h = 0.5;
  const nx = field(px + h, py) - field(px - h, py);
  const ny = field(px, py + h) - field(px, py - h);
  const length = Math.hypot(nx, ny);
  return length === 0 ? [0, 0] : [nx / length, ny / length];
}

function smoothstep(edge0, edge1, value) {
  if (edge0 === edge1) return value < edge0 ? 0 : 1;
  const t = Math.max(0, Math.min(1, (value - edge0) / (edge1 - edge0)));
  return t * t * (3 - 2 * t);
}

/**
 * Deterministic value noise in `[0, 1)`. Integer hashing rather than a PRNG so
 * a pixel's grain depends only on its coordinates — the generator is
 * reproducible regardless of iteration order.
 */
function grainAt(x, y, seed) {
  let h = (Math.imul(x, 374761393) + Math.imul(y, 668265263) + Math.imul(seed, 1442695041)) >>> 0;
  h = (h ^ (h >>> 13)) >>> 0;
  h = Math.imul(h, 1274126177) >>> 0;
  h = (h ^ (h >>> 16)) >>> 0;
  return h / 4294967296;
}

/** Paint the shared paper/metal grain over a shaded pass. */
function applyGrain(canvas, x, y, seed, coverage, amplitude = GRAIN) {
  const n = grainAt(x, y, seed) - 0.5;
  const a = Math.abs(n) * 2 * amplitude * coverage;
  const tone = n > 0 ? 1 : 0;
  canvas.over(x, y, tone, tone, tone, a);
}

/**
 * The bevel pass every plate shares: within `depth` of the shape's boundary,
 * lift the surface toward the key light and drop it away from it.
 *
 * `sign` is `+1` for a raised surface (lit on the top/left run, as a plate
 * lying on the card) and `-1` for a recessed one (shadowed on the top/left run,
 * as a channel cut into it) — the whole difference between a header field the
 * text sits *on* and an information strip it sits *in*.
 */
function bevel(
  canvas,
  x,
  y,
  distance,
  normal,
  depth,
  coverage,
  { sign = 1, lit = 0.13, shade = 0.24 } = {},
) {
  const t = smoothstep(-depth, 0, distance);
  if (t <= 0) return;
  const facing = (normal[0] * LIGHT.x + normal[1] * LIGHT.y) * sign;
  const strength = t * t * Math.abs(facing) * coverage;
  if (facing > 0) canvas.over(x, y, 1, 1, 1, lit * strength);
  else canvas.over(x, y, 0, 0, 0, shade * strength);
}

/* ── The plates ───────────────────────────────────────────────────────────── */

/**
 * The card's layered edge (issue #570, first checklist item): the outer
 * contour, the slate bevel, the thicker bottom paper edge, and the gold
 * hairline engraved on `RUNE_FRAME.ruleInset` — everything the stylesheet
 * previously approximated with a border and two box-shadows.
 *
 * The band is exactly `ruleInset + rule` wide, so the plate's inner boundary
 * lands on the inner edge of the hairline and the card body takes over with no
 * seam. Composed over `--face-body`, which is why nothing here paints slate.
 */
function drawFrameEdge(canvas, k) {
  const { width, height } = canvas;
  const radius = PLATE_FRAME.radius * k;
  const edge = PLATE_FRAME.edge * k;
  const edgeBottom = PLATE_FRAME.edgeBottom * k;
  const inset = PLATE_FRAME.ruleInset * k;
  const rule = PLATE_FRAME.rule * k;
  const gold = parseHex(PLATE_GOLD.rule);
  const goldShade = parseHex(PLATE_GOLD.ruleShade);
  const field = (px, py) => sdRoundRect(px, py, width, height, radius);

  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const px = x + 0.5;
      const py = y + 0.5;
      const d = field(px, py);
      const coverage = Math.max(0, Math.min(1, 0.5 - d));
      if (coverage <= 0) continue;
      const n = normalAt(field, px, py);

      // The slate edge: a raised bevel from the outer contour inward.
      bevel(canvas, x, y, d, n, edge, coverage, { lit: 0.2, shade: 0.34 });

      // A hard outer contour so the silhouette survives against a light table.
      canvas.over(x, y, 0, 0, 0, 0.34 * smoothstep(-1.6, -0.2, d) * coverage);

      // Paper thickness: the bottom edge is thicker and one shade darker than
      // the other three (card-representation §3.11).
      const fromBottom = height - py;
      if (fromBottom < edgeBottom) {
        const t = smoothstep(edgeBottom, edgeBottom * 0.2, fromBottom);
        canvas.over(x, y, 0, 0, 0, 0.3 * t * coverage);
      }

      // The engraved gold hairline: a dark score just outside it, the metal
      // itself lit on the top/left run and shaded on the bottom/right one, and
      // a light catch on its inner lip.
      const depth = -d;
      const score = band(depth, inset - rule * 0.8, inset, 0.6);
      canvas.over(x, y, 0, 0, 0, 0.4 * score * coverage);
      const metal = band(depth, inset, inset + rule, 0.6);
      if (metal > 0) {
        const facing = n[0] * LIGHT.x + n[1] * LIGHT.y;
        const mix = smoothstep(-0.4, 0.4, facing);
        canvas.over(
          x,
          y,
          goldShade[0] + (gold[0] - goldShade[0]) * mix,
          goldShade[1] + (gold[1] - goldShade[1]) * mix,
          goldShade[2] + (gold[2] - goldShade[2]) * mix,
          metal * coverage,
        );
      }
      const lip = band(depth, inset + rule, inset + rule * 1.8, 0.6);
      canvas.over(x, y, 1, 1, 1, 0.16 * lip * coverage);

      applyGrain(canvas, x, y, 1, coverage * smoothstep(0, edge, depth));
    }
  }
}

/** Anti-aliased membership of `value` in `[low, high]`, softened by `feather`. */
function band(value, low, high, feather) {
  return (
    smoothstep(low - feather, low + feather, value) *
    smoothstep(high + feather, high - feather, value)
  );
}

/**
 * The art window's surround (second checklist item): the window is cut *into*
 * the card, so the seam is shadowed on the light side and catches light on the
 * far side — the inverse of the frame edge's raised bevel. Drawn as a ring so
 * the illustration (or the procedural identity field) shows through the middle.
 */
function drawArtSeam(canvas, k) {
  const { width, height } = canvas;
  const radius = PLATE_FRAME.plateRadius * k;
  const depth = 0.026 * k;
  const field = (px, py) => sdRoundRect(px, py, width, height, radius);

  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const px = x + 0.5;
      const py = y + 0.5;
      const d = field(px, py);
      const coverage = Math.max(0, Math.min(1, 0.5 - d));
      if (coverage <= 0) continue;
      const n = normalAt(field, px, py);

      // The lip: a recessed bevel, so the window reads as a hole in the card.
      bevel(canvas, x, y, d, n, depth, coverage, { sign: -1, lit: 0.15, shade: 0.34 });
      // The cut line itself, at the very edge of the aperture.
      canvas.over(x, y, 0, 0, 0, 0.3 * smoothstep(-1.4, -0.2, d) * coverage);
      applyGrain(canvas, x, y, 2, coverage * smoothstep(-depth, 0, d), GRAIN * 0.7);
    }
  }
}

/**
 * A printed surface — the header field, the lower information strip, the status
 * channel, and the P/T plate all come off this one pass (third and fourth
 * checklist items). `raised` decides whether the text sits on the surface or in
 * it; `sweep` is the vertical light gradient across the field the middle patch
 * stretches; `depth` scales the rim against the plate's own radius.
 */
function drawSurface(canvas, k, { raised, sweep, depth = 1 }) {
  const { width, height, radius, slice } = canvas;
  const rim = 0.02 * k * depth;
  const field = (px, py) => sdRoundRect(px, py, width, height, radius);
  const seed = raised ? 3 : 4;

  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const px = x + 0.5;
      const py = y + 0.5;
      const d = field(px, py);
      const coverage = Math.max(0, Math.min(1, 0.5 - d));
      if (coverage <= 0) continue;
      const n = normalAt(field, px, py);

      // The field's own light: brighter at the top, falling to the bottom, so
      // the surface carries the interface's key light rather than reading flat.
      const vertical = py / height;
      if (raised) canvas.over(x, y, 1, 1, 1, sweep * (1 - vertical) * coverage);
      canvas.over(x, y, 0, 0, 0, sweep * vertical * 0.9 * coverage);
      if (!raised) canvas.over(x, y, 0, 0, 0, sweep * (1 - vertical) * 0.55 * coverage);

      bevel(canvas, x, y, d, n, rim, coverage, {
        sign: raised ? 1 : -1,
        lit: 0.2,
        shade: 0.3,
      });
      canvas.over(x, y, 0, 0, 0, 0.22 * smoothstep(-1.3, -0.2, d) * coverage);

      // Grain fades out of the middle patch. The rims are drawn near 1:1, but
      // the middle is the patch `border-image` stretches over the whole field,
      // and stretched noise reads as streaks rather than as paper.
      const inMiddle = smoothstep(slice * 0.5, slice, -d);
      applyGrain(canvas, x, y, seed, coverage, GRAIN * (1 - 0.8 * inMiddle));
    }
  }
}

/**
 * The colour-identity material (fifth checklist item). Grayscale by design: the
 * DOM renderer tints it with `--face-accent` through `background-blend-mode`,
 * so every identity gets the same woven surface and none of them becomes the
 * flat colour block §3.4 rules out — one 64 px tile instead of an asset per
 * colour, which is what keeps the most budget-sensitive set in the project on
 * budget.
 *
 * Seamless: every frequency is an integer number of cycles across the tile.
 */
function drawIdentityWeave(canvas) {
  const { width, height } = canvas;
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const u = ((x + 0.5) / width) * Math.PI * 2;
      const v = ((y + 0.5) / height) * Math.PI * 2;
      // Two crossed threads plus a slow swell, all integer-period so the tile
      // repeats without a seam at any size.
      const weave = Math.sin(u * 4) * Math.cos(v * 4) * 0.5 + Math.sin(u * 2 + v * 2) * 0.25;
      const swell = Math.sin(u) * Math.cos(v) * 0.25;
      const value = (weave + swell) * 0.5;
      const tone = value > 0 ? 1 : 0;
      canvas.over(x, y, tone, tone, tone, Math.abs(value) * 0.2);
      applyGrain(canvas, x, y, 5, 1, GRAIN * 1.4);
    }
  }
}

/* ── Public surface ───────────────────────────────────────────────────────── */

/**
 * Render one plate spec to 8-bit RGBA. Pure and deterministic: the same spec
 * always produces the same bytes, which is what makes the content hash in the
 * filename meaningful.
 */
export function renderPlate(spec) {
  const canvas = new Canvas(spec.width, spec.height);
  // The authoring scale: authored px per unit of card width. Everything inside
  // a plate is placed at `ratio · k`, which is why one asset serves every tier.
  const k = spec.band > 0 ? spec.slice / spec.band : spec.width;
  canvas.radius = spec.radius * k;
  canvas.slice = spec.slice;
  spec.draw(canvas, k);
  if (spec.radius > 0) {
    const radius = spec.radius * k;
    canvas.maskAlpha((x, y) =>
      Math.max(
        0,
        Math.min(1, 0.5 - sdRoundRect(x + 0.5, y + 0.5, spec.width, spec.height, radius)),
      ),
    );
  }
  return { width: spec.width, height: spec.height, rgba: canvas.toRgba8() };
}

/**
 * The authoring scale of a plate: authored px per unit of card width `W`. A
 * plate is nine-slice-safe only while its authored corner radius stays inside
 * its slice, which this makes checkable.
 */
export function authoringScale(spec) {
  return spec.band > 0 ? spec.slice / spec.band : spec.width;
}

/* ── PNG ──────────────────────────────────────────────────────────────────── */

/*
 * The shipping encoder lives here, beside the synthesis and inside the pure
 * module, for one reason: **the committed bytes have to be checkable**.
 *
 * The first cut of this generator probed for `cwebp`, then ImageMagick, then
 * fell back to PNG. That produced a smaller file and an undeliverable promise:
 * three code paths, two file extensions, and encoder-version-dependent output,
 * all feeding a content hash that names the committed file and a ledger that
 * calls the result reproducible. Two contributors running the documented
 * command could leave the repository in different states, and no test could
 * tell, because none of the three encoders was available to one.
 *
 * So the plates ship as PNG from the encoder below — in-process, no external
 * tool, no probing — and `framePlates.test.js` re-encodes every plate and
 * compares it byte-for-byte against the file in the tree. Regeneration is a
 * checked no-op rather than a promise. (ADR 0031 prefers WebP for raster and
 * allows PNG "where a consumer requires it"; the consumer here is the ledger's
 * own reproducibility claim.)
 *
 * **Including the compressor.** The first attempt at this used
 * `zlib.deflateSync` with every parameter pinned, and left the zlib build
 * itself as a documented residual risk. CI then produced different bytes for
 * the one RGBA plate on the first run — the residual risk is real, and a
 * content hash that depends on the machine's zlib is not a content hash. So
 * DEFLATE is implemented here too: fixed Huffman codes (RFC 1951 §3.2.6) over
 * a greedy LZ77 with a bounded, fully specified match search. It gives up
 * perhaps a fifth of zlib's ratio on these images and buys the only property
 * that matters for a committed asset — the same input produces the same bytes,
 * on every machine, forever.
 */

/* ── A deterministic DEFLATE (RFC 1951, fixed Huffman) ────────────────────── */

/** LSB-first bit sink, as DEFLATE streams are written. */
class BitWriter {
  constructor() {
    this.bytes = [];
    this.bit = 0;
    this.acc = 0;
  }

  /** Write `count` bits of `value`, least-significant bit first. */
  write(value, count) {
    for (let i = 0; i < count; i += 1) {
      this.acc |= ((value >> i) & 1) << this.bit;
      this.bit += 1;
      if (this.bit === 8) {
        this.bytes.push(this.acc);
        this.acc = 0;
        this.bit = 0;
      }
    }
  }

  /** Write `count` bits of `value`, most-significant bit first (Huffman codes). */
  writeCode(value, count) {
    for (let i = count - 1; i >= 0; i -= 1) {
      this.acc |= ((value >> i) & 1) << this.bit;
      this.bit += 1;
      if (this.bit === 8) {
        this.bytes.push(this.acc);
        this.acc = 0;
        this.bit = 0;
      }
    }
  }

  finish() {
    if (this.bit > 0) this.bytes.push(this.acc);
    return Buffer.from(this.bytes);
  }
}

/** The fixed literal/length code for a symbol (RFC 1951 §3.2.6). */
function fixedLiteral(writer, symbol) {
  if (symbol < 144) writer.writeCode(0x30 + symbol, 8);
  else if (symbol < 256) writer.writeCode(0x190 + symbol - 144, 9);
  else if (symbol < 280) writer.writeCode(symbol - 256, 7);
  else writer.writeCode(0xc0 + symbol - 280, 8);
}

// Length codes 257..285 and distance codes 0..29, as the RFC tables define them.
const LENGTH_BASE = [
  3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115, 131,
  163, 195, 227, 258,
];
const LENGTH_EXTRA = [
  0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0,
];
const DIST_BASE = [
  1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537, 2049,
  3073, 4097, 6145, 8193, 12289, 16385, 24577,
];
const DIST_EXTRA = [
  0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13,
];

function codeFor(bases, value) {
  let index = bases.length - 1;
  while (bases[index] > value) index -= 1;
  return index;
}

function adler32(buffer) {
  let a = 1;
  let b = 0;
  for (const byte of buffer) {
    a = (a + byte) % 65521;
    b = (b + a) % 65521;
  }
  return ((b << 16) | a) >>> 0;
}

/** How far back the match search looks, and how many candidates it tries. Both
 * are part of the output, so they are constants of this format, not tuning. */
const WINDOW = 32768;
const MAX_MATCH = 258;
const MIN_MATCH = 3;
const MAX_CHAIN = 128;

/**
 * Compress to a zlib stream with fixed Huffman codes and greedy LZ77 matching.
 *
 * Deliberately simple: one pass, greedy (never lazy) matching, a bounded chain
 * walk, and no dynamic code tables. Every decision is in this function, so the
 * output is a pure function of the input — which is the entire point. A zlib
 * would compress these plates roughly 20% smaller and would not have that
 * property on someone else's machine.
 */
export function deflateFixed(raw) {
  const writer = new BitWriter();
  writer.write(1, 1); // BFINAL
  writer.write(1, 2); // BTYPE = 01, fixed Huffman

  // head[hash] = most recent position with this 3-byte prefix; prev[pos] = the
  // one before it. A plain hash chain, walked at most MAX_CHAIN deep.
  const head = new Int32Array(1 << 15).fill(-1);
  const prev = new Int32Array(raw.length).fill(-1);
  const hashAt = (i) => ((raw[i] << 10) ^ (raw[i + 1] << 5) ^ raw[i + 2]) & 0x7fff;

  let position = 0;
  while (position < raw.length) {
    let bestLength = 0;
    let bestDistance = 0;
    if (position + MIN_MATCH <= raw.length) {
      const key = hashAt(position);
      let candidate = head[key];
      let tries = 0;
      const limit = Math.min(MAX_MATCH, raw.length - position);
      while (candidate >= 0 && tries < MAX_CHAIN && position - candidate <= WINDOW) {
        let length = 0;
        while (length < limit && raw[candidate + length] === raw[position + length]) length += 1;
        if (length > bestLength) {
          bestLength = length;
          bestDistance = position - candidate;
          if (length === limit) break;
        }
        candidate = prev[candidate];
        tries += 1;
      }
    }

    if (bestLength >= MIN_MATCH) {
      const lengthCode = codeFor(LENGTH_BASE, bestLength);
      fixedLiteral(writer, 257 + lengthCode);
      writer.write(bestLength - LENGTH_BASE[lengthCode], LENGTH_EXTRA[lengthCode]);
      const distanceCode = codeFor(DIST_BASE, bestDistance);
      writer.writeCode(distanceCode, 5);
      writer.write(bestDistance - DIST_BASE[distanceCode], DIST_EXTRA[distanceCode]);
    } else {
      fixedLiteral(writer, raw[position]);
      bestLength = 1;
    }

    // Index every position the emitted run covers, so later matches can reach
    // back into it — this is what keeps the ratio respectable despite greed.
    for (let i = 0; i < bestLength; i += 1) {
      const at = position + i;
      if (at + MIN_MATCH > raw.length) break;
      const key = hashAt(at);
      prev[at] = head[key];
      head[key] = at;
    }
    position += bestLength;
  }

  fixedLiteral(writer, 256); // end of block
  const body = writer.finish();
  const checksum = Buffer.alloc(4);
  checksum.writeUInt32BE(adler32(raw), 0);
  // zlib header: deflate, 32 K window, no preset dictionary, (0x78 << 8 | 0x01) % 31 === 0.
  return Buffer.concat([Buffer.from([0x78, 0x01]), body, checksum]);
}

/* ── PNG chunks ───────────────────────────────────────────────────────────── */

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, body) {
  const head = Buffer.alloc(8);
  head.writeUInt32BE(body.length, 0);
  head.write(type, 4, 'ascii');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([head.subarray(4), body])), 0);
  return Buffer.concat([head, body, crc]);
}

/**
 * Whether every opaque pixel is neutral, so the plate can ship as greyscale +
 * alpha (PNG colour type 4) at half the samples. Six of the seven plates are —
 * they are light maps — and only the frame edge, which carries the structural
 * gold hairline, needs full colour.
 */
function isGreyscale(rgba) {
  for (let i = 0; i < rgba.length; i += 4) {
    if (rgba[i + 3] === 0) continue;
    if (rgba[i] !== rgba[i + 1] || rgba[i + 1] !== rgba[i + 2]) return false;
  }
  return true;
}

/** The PNG filter that costs the fewest bits on this scanline (the standard
 * minimum-sum-of-absolute-differences heuristic; deterministic, so the choice
 * is part of the reproducible output). */
function filterScanline(row, previous, bpp) {
  const width = row.length;
  let best = null;
  for (let type = 0; type < 5; type += 1) {
    const out = Buffer.alloc(width);
    let score = 0;
    for (let i = 0; i < width; i += 1) {
      const a = i >= bpp ? row[i - bpp] : 0;
      const b = previous[i];
      const c = i >= bpp ? previous[i - bpp] : 0;
      let predictor = 0;
      if (type === 1) predictor = a;
      else if (type === 2) predictor = b;
      else if (type === 3) predictor = (a + b) >> 1;
      else if (type === 4) predictor = paeth(a, b, c);
      const value = (row[i] - predictor) & 0xff;
      out[i] = value;
      score += value < 128 ? value : 256 - value;
    }
    if (best === null || score < best.score) best = { type, out, score };
  }
  return best;
}

function paeth(a, b, c) {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  return pb <= pc ? b : c;
}

/** Encode 8-bit RGBA as PNG, compressing with {@link deflateFixed}. */
export function encodePng(width, height, rgba) {
  const grey = isGreyscale(rgba);
  const bpp = grey ? 2 : 4;
  const stride = width * bpp;
  const raw = Buffer.alloc((stride + 1) * height);
  let previous = Buffer.alloc(stride);
  for (let y = 0; y < height; y += 1) {
    const row = Buffer.alloc(stride);
    for (let x = 0; x < width; x += 1) {
      const source = (y * width + x) * 4;
      if (grey) {
        row[x * 2] = rgba[source];
        row[x * 2 + 1] = rgba[source + 3];
      } else {
        row[x * 4] = rgba[source];
        row[x * 4 + 1] = rgba[source + 1];
        row[x * 4 + 2] = rgba[source + 2];
        row[x * 4 + 3] = rgba[source + 3];
      }
    }
    const { type, out } = filterScanline(row, previous, bpp);
    raw[y * (stride + 1)] = type;
    out.copy(raw, y * (stride + 1) + 1);
    previous = row;
  }
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header[8] = 8; // bit depth
  header[9] = grey ? 4 : 6; // colour type: greyscale+alpha or RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', deflateFixed(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/** The shipping filename of a plate, given the hash of its encoded bytes. */
export function plateFilename(spec, hash) {
  return `${spec.id}.${hash}.png`;
}
