//! Serving a built [`Position`]: one room, one loopback socket, and the built client.
//!
//! Everything here is the *same* machinery a real match runs on and none of it is a
//! shortcut around it. The room is [`sage_server::Room`], the AI is
//! [`sage_server::serve_ai_seat`], and seat 0's browser is bridged by
//! [`sage_server::serve_connection`] — so an action taken in the client is generated by the
//! engine, re-validated by the room, and applied by the engine, exactly as it is in a game
//! that started at turn one. The only thing a scenario replaces is *how the first state was
//! reached*.
//!
//! **This adds no protocol command and opens no door.** There is no wire message that
//! injects authoritative state; the position is decided by a file this process read before
//! it bound anything, and the socket refuses to bind to an address that is not loopback
//! ([`bind`]). A remote client cannot reach it, and a running `sage-server` has no idea
//! this crate exists.

use std::net::SocketAddr;
use std::path::{Path, PathBuf};

use sage_engine::CardDatabase;
use sage_server::{
    policy_for, serve_ai_seat, serve_connection, AutoPassPolicy, Room, RoomHandle, StopPolicy,
};
use tokio::net::TcpListener;
use tokio::sync::watch;
use tracing::{info, warn};

use crate::build::Position;

/// The loopback address the scenario socket binds when nothing says otherwise. Distinct
/// from `sage-server`'s own 9000 so a scenario can run beside a real server.
pub const DEFAULT_ADDR: &str = "127.0.0.1:9010";

/// The address the built client is served on when nothing says otherwise — the port
/// `vite preview` uses, and the one the e2e suite already runs on.
pub const DEFAULT_CLIENT_ADDR: &str = "127.0.0.1:4173";

/// Why a scenario could not be served, as against being wrong about its position.
#[derive(Debug)]
pub enum ServeError {
    /// The address did not parse, or did not resolve.
    BadAddress {
        /// The address as written.
        addr: String,
        /// What went wrong resolving it.
        source: std::io::Error,
    },
    /// The address resolved to something that is not loopback. Refused: this tool serves an
    /// authoritative position built from a local file and has no business being reachable.
    NotLoopback(SocketAddr),
    /// The socket could not be bound (the port is in use, most likely).
    Bind {
        /// The address that could not be bound.
        addr: SocketAddr,
        /// The underlying error.
        source: std::io::Error,
    },
    /// The built web client is not where it should be, so there is nothing to launch.
    NoClientBuild(PathBuf),
    /// The client's own toolchain is not installed, so there is nothing to launch it with.
    NoClientTooling(PathBuf),
    /// Launching the client failed.
    Client(std::io::Error),
}

impl std::fmt::Display for ServeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::BadAddress { addr, source } => {
                write!(f, "could not resolve the address {addr:?}: {source}")
            }
            Self::NotLoopback(addr) => write!(
                f,
                "{addr} is not a loopback address. A scenario serves an authoritative \
                 position built from a local file and is deliberately unreachable from \
                 anywhere else; bind 127.0.0.1 or [::1]"
            ),
            Self::Bind { addr, source } => write!(f, "could not bind {addr}: {source}"),
            Self::NoClientBuild(path) => write!(
                f,
                "there is no built client at {}. Build it (`cd clients/web && npm ci && \
                 npm run build`), or pass --no-client and point a client you are already \
                 running at the printed address",
                path.display()
            ),
            Self::NoClientTooling(path) => write!(
                f,
                "the client's toolchain is not installed at {} (`cd clients/web && npm \
                 ci`), or pass --no-client",
                path.display()
            ),
            Self::Client(error) => write!(f, "could not start the client: {error}"),
        }
    }
}

impl std::error::Error for ServeError {}

/// A running scenario: the room, the bound socket, and the URL to open.
pub struct Running {
    /// The room every connection and AI seat talks to.
    room: RoomHandle,
    /// The bound loopback listener seat 0's browser connects to.
    listener: TcpListener,
    /// The address the listener actually bound (an ephemeral port is already resolved).
    addr: SocketAddr,
    /// The child serving the built client, when this process started one. Killed on drop,
    /// which is what makes the whole thing disposable.
    client: Option<tokio::process::Child>,
    /// The URL to open, ready to print.
    url: String,
}

impl Running {
    /// The URL a browser should open — the built client, pointed at this socket.
    #[must_use]
    pub fn url(&self) -> &str {
        &self.url
    }

    /// The address the scenario socket is bound to.
    #[must_use]
    pub fn addr(&self) -> SocketAddr {
        self.addr
    }
}

/// Build the room for `position` and start every seat but seat 0, which is left for the
/// browser.
///
/// The room is configured exactly as a lobby-started game is (issue #264/#455): priority
/// automation on, humans stopped at their own main phases. A scenario that behaved
/// differently from a real game at the one seam a player feels most — how often they are
/// asked — would be testing something other than the game.
fn start_room(position: &Position, db: CardDatabase) -> RoomHandle {
    let names: Vec<Option<String>> = position
        .seats
        .iter()
        .map(|seat| seat.name.clone())
        .collect();
    let ai_seats: Vec<bool> = position
        .seats
        .iter()
        .map(|seat| seat.ai.is_some())
        .collect();
    let (room, _task) = Room::new(position.state.clone(), db)
        .with_player_names(names)
        .with_ai_seats(ai_seats)
        .with_auto_pass(AutoPassPolicy::On)
        .with_stop_policy(StopPolicy::HumanMainPhases)
        .spawn();

    for (seat, plan) in position.seats.iter().enumerate() {
        let Some(kind) = plan.ai else { continue };
        // The same per-seat sub-seed the lobby derives, so a scenario replays its AI
        // identically under a pinned seed and two AI seats never share a stream.
        let seed = position.seed
            ^ (seat as u64)
                .wrapping_add(1)
                .wrapping_mul(0x9E37_79B9_7F4A_7C15);
        tokio::spawn(serve_ai_seat(
            seat,
            room.clone(),
            policy_for(kind, seed),
            std::future::pending::<()>(),
        ));
    }
    room
}

/// Resolve `addr`, refuse it if it is not loopback, and bind it.
///
/// # Errors
/// Returns [`ServeError::BadAddress`], [`ServeError::NotLoopback`], or
/// [`ServeError::Bind`].
async fn bind(addr: &str) -> Result<(TcpListener, SocketAddr), ServeError> {
    let listener = {
        let resolved = tokio::net::lookup_host(addr)
            .await
            .map_err(|source| ServeError::BadAddress {
                addr: addr.to_string(),
                source,
            })?
            .next()
            .ok_or_else(|| ServeError::BadAddress {
                addr: addr.to_string(),
                source: std::io::Error::new(
                    std::io::ErrorKind::AddrNotAvailable,
                    "resolved to no address",
                ),
            })?;
        if !resolved.ip().is_loopback() {
            return Err(ServeError::NotLoopback(resolved));
        }
        TcpListener::bind(resolved)
            .await
            .map_err(|source| ServeError::Bind {
                addr: resolved,
                source,
            })?
    };
    let bound = listener.local_addr().map_err(|source| ServeError::Bind {
        addr: "0.0.0.0:0"
            .parse()
            .unwrap_or(SocketAddr::from(([0, 0, 0, 0], 0))),
        source,
    })?;
    Ok((listener, bound))
}

/// Where the runner looks for the built client and its toolchain, relative to a client
/// directory (`clients/web`).
struct ClientPaths {
    dist: PathBuf,
    vite: PathBuf,
}

impl ClientPaths {
    fn of(dir: &Path) -> Self {
        Self {
            dist: dir.join("dist"),
            vite: dir.join("node_modules").join(".bin").join("vite"),
        }
    }
}

/// Serve the built client on `client_addr` from `client_dir`, as a child of this process.
///
/// It runs `vite preview` over the **built** bundle rather than the dev server, so what a
/// maintainer plays is the artifact that ships — the same choice `playwright.config.ts`
/// makes and for the same reason. `kill_on_drop` is what makes the whole run disposable:
/// when the runner exits, the client goes with it.
///
/// # Errors
/// Returns [`ServeError::NoClientBuild`], [`ServeError::NoClientTooling`], or
/// [`ServeError::Client`].
fn start_client(
    client_dir: &Path,
    client_addr: &SocketAddr,
) -> Result<tokio::process::Child, ServeError> {
    let paths = ClientPaths::of(client_dir);
    if !paths.dist.is_dir() {
        return Err(ServeError::NoClientBuild(paths.dist));
    }
    if !paths.vite.is_file() {
        return Err(ServeError::NoClientTooling(paths.vite));
    }
    tokio::process::Command::new(&paths.vite)
        .arg("preview")
        .arg("--host")
        .arg(client_addr.ip().to_string())
        .arg("--port")
        .arg(client_addr.port().to_string())
        .arg("--strictPort")
        .current_dir(client_dir)
        .kill_on_drop(true)
        .spawn()
        .map_err(ServeError::Client)
}

/// Everything the runner was asked to do beyond the position itself.
pub struct Options {
    /// The loopback address the scenario socket binds.
    pub addr: String,
    /// The address the built client is served on.
    pub client_addr: String,
    /// The client directory (`clients/web`), or `None` to serve no client.
    pub client_dir: Option<PathBuf>,
}

/// Start a scenario: bind the socket, spawn the room and its AI seats, and (unless asked
/// not to) start the built client, returning the URL to open.
///
/// # Errors
/// Returns a [`ServeError`] if the address is unusable or the client cannot be started.
/// Nothing is left running when this returns an error: the listener is dropped with it.
pub async fn start(
    position: &Position,
    db: CardDatabase,
    options: &Options,
) -> Result<Running, ServeError> {
    let (listener, addr) = bind(&options.addr).await?;
    let client_addr = {
        let mut resolved = tokio::net::lookup_host(&options.client_addr)
            .await
            .map_err(|source| ServeError::BadAddress {
                addr: options.client_addr.clone(),
                source,
            })?;
        resolved.next().ok_or_else(|| ServeError::BadAddress {
            addr: options.client_addr.clone(),
            source: std::io::Error::new(
                std::io::ErrorKind::AddrNotAvailable,
                "resolved to no address",
            ),
        })?
    };
    let client = match &options.client_dir {
        Some(dir) => Some(start_client(dir, &client_addr)?),
        None => None,
    };
    let room = start_room(position, db);
    let url = format!("http://{client_addr}/?server=ws://{addr}");
    Ok(Running {
        room,
        listener,
        addr,
        client,
        url,
    })
}

/// Accept browser connections for **seat 0** until `shutdown` resolves.
///
/// Exactly one connection is live at a time, and that is deliberate. A reload opens a new
/// socket while the old one is still closing, and the room holds a seat open by clearing it
/// on `Leave` — so a late `Leave` from the socket that just went away would blank the outbox
/// of the one that just arrived. Retiring the previous connection *and waiting for it* before
/// joining the new one removes the race entirely, which is what makes a refresh land back in
/// the same live game every time.
pub async fn accept<F>(running: Running, shutdown: F)
where
    F: std::future::Future<Output = ()>,
{
    let Running {
        room,
        listener,
        client,
        ..
    } = running;
    // Held so the client child stays alive for the run and is killed when it ends.
    let _client = client;
    let mut current: Option<(watch::Sender<bool>, tokio::task::JoinHandle<()>)> = None;

    tokio::pin!(shutdown);
    loop {
        tokio::select! {
            () = &mut shutdown => break,
            accepted = listener.accept() => match accepted {
                Ok((stream, peer)) => {
                    // Retire the previous browser first, so its `Leave` cannot land after
                    // the new connection's `Join`.
                    if let Some((close, task)) = current.take() {
                        let _ = close.send(true);
                        let _ = task.await;
                    }
                    let ws = match tokio_tungstenite::accept_async(stream).await {
                        Ok(ws) => ws,
                        Err(error) => {
                            warn!(%peer, %error, "websocket handshake failed");
                            continue;
                        }
                    };
                    info!(%peer, "browser connected to the scenario seat");
                    let (close, mut closed) = watch::channel(false);
                    let room = room.clone();
                    let task = tokio::spawn(async move {
                        serve_connection(0, room, ws, async move {
                            while closed.changed().await.is_ok() {
                                if *closed.borrow() {
                                    return;
                                }
                            }
                        })
                        .await;
                    });
                    current = Some((close, task));
                }
                Err(error) => warn!(%error, "failed to accept a scenario connection"),
            },
        }
    }

    if let Some((close, task)) = current.take() {
        let _ = close.send(true);
        let _ = task.await;
    }
    info!("scenario stopped");
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;

    #[tokio::test]
    async fn a_non_loopback_address_is_refused_before_anything_binds() {
        // The whole "development-only" guarantee in one check: this process serves an
        // authoritative position and must not be reachable from off the machine.
        let error = bind("0.0.0.0:0").await.expect_err("refused");
        assert!(matches!(error, ServeError::NotLoopback(_)), "got {error:?}");
        assert!(error.to_string().contains("loopback"));
    }

    #[tokio::test]
    async fn a_loopback_address_binds_and_reports_its_resolved_port() {
        let (_listener, addr) = bind("127.0.0.1:0").await.expect("loopback binds");
        assert!(addr.ip().is_loopback());
        assert_ne!(addr.port(), 0, "the ephemeral port is resolved");
    }

    #[tokio::test]
    async fn an_unresolvable_address_names_itself() {
        let error = bind("this is not an address").await.expect_err("refused");
        assert!(
            matches!(error, ServeError::BadAddress { .. }),
            "got {error:?}"
        );
    }

    #[test]
    fn a_missing_client_build_says_how_to_make_one() {
        let dir = Path::new("/nonexistent/clients/web");
        let addr: SocketAddr = "127.0.0.1:4173".parse().unwrap();
        let error = start_client(dir, &addr).expect_err("there is no build there");
        assert!(
            matches!(error, ServeError::NoClientBuild(_)),
            "got {error:?}"
        );
        assert!(error.to_string().contains("npm run build"));
        assert!(error.to_string().contains("--no-client"));
    }
}
