/**
 * Card and board representations: cards, permanents, zones, and player views.
 */

import type { EntityId, PlayerId } from './index.js';

/**
 * A card object, shown only to a player entitled to see it. All characteristics
 * are server-computed; the client never derives them.
 */
export interface CardView {
  /** Entity id of this card instance. */
  id: EntityId;
  /** Display name. */
  name: string;
  /** e.g. `"Creature — Elf Warrior"`. */
  type_line: string;
  /** Displayed mana cost string, e.g. `"{1}{G}"`. Absent for cards without one. */
  mana_cost?: string;
  /**
   * The card's rules text, generated by the server from the card's ability IR
   * (ADR 0018). Never computed here: the client renders this string and never
   * derives, formats, or infers a card's rules. Omitted (defaults to `""`) when the
   * card has no rules.
   */
  rules_text?: string;
  /**
   * The card's stable presentation identity — the same string for every copy of a
   * card, in every game, across server rebuilds (unlike {@link CardView.id}, which is
   * a per-game entity handle). Reserved for a future *client-local* cache that could
   * enrich presentation by identity; nothing renders from it today, and a client that
   * ignores it presents the card completely from `rules_text`.
   */
  functional_id?: string;
  /** Displayed power (a string so `*` round-trips). Present only for creatures. */
  power?: string;
  /** Displayed toughness; see {@link CardView.power}. Present only for creatures. */
  toughness?: string;
  /**
   * The card's keyword abilities as lowercase wire names (e.g. `"flying"`,
   * `"first_strike"`), server-computed for display. The client renders badges and
   * never derives them. Omitted (treated as empty) when the card has none.
   */
  keywords?: string[];
}

/**
 * What the receiving player may know about an opponent: hidden zones are reduced
 * to counts, public state is exact.
 */
export interface OpponentView {
  /** Which opponent this describes. */
  player_id: PlayerId;
  /** Number of cards in hand (contents hidden). */
  hand_size: number;
  /** Current life total. */
  life: number;
  /** Number of cards left in library. */
  library_size: number;
  /** Number of cards in the graveyard. */
  graveyard_size: number;
  /** Free-form status labels (e.g. `"monarch"`) for display only. */
  statuses?: string[];
  /** Whether this opponent has been eliminated — they left the game (CR 800.4a,
   * issue #342/#345). Omitted (treated as `false`) in a two-player game. */
  eliminated?: boolean;
  /**
   * Whether this seat currently has a live connection (issue #553). The server holds
   * a disconnected seat open — the game does not end and the seat is never conceded —
   * so this says "waiting on a disconnected player", not "gone".
   *
   * **Absent means `true`.** This is the one flag on the wire whose omitted value is
   * `true`: it rides the wire only as `false`, so an older server (and every
   * connected seat) reads as connected. Test `=== false`, never falsiness.
   */
  connected?: boolean;
  /**
   * Whether this seat is played by a server-side AI (issue #415/#553) rather than a
   * human — the lobby's `SeatView.ai` carried into the match, so the marker is not
   * lost at the hand-off. Public presentation information; nothing about the AI's
   * decisions is exposed. Omitted (treated as `false`, i.e. human).
   */
  ai?: boolean;
}

/**
 * The receiver's own public stats — the self-counterpart of {@link OpponentView}.
 * Hand contents ride in {@link GameView.my_hand} and mana in
 * {@link GameView.mana_pool}; this carries the two public numbers those omit — the
 * receiver's life total and library size — so a player can read their own life, not
 * only their opponents'. No hidden information (a player's own life and library size
 * are public). An older server may omit it; {@link normalizeGameView} defaults it.
 */
export interface SelfView {
  /** The receiver's current life total. */
  life: number;
  /** Number of cards left in the receiver's library. */
  library_size: number;
  /**
   * Whether the receiver has been eliminated — they lost while two or more players
   * remained, so the game continues without them (CR 800.4a, issue #553). The
   * self-counterpart of {@link OpponentView.eliminated}, and the **only**
   * authoritative source for a local elimination: `result` arrives at game over,
   * which can be many turns later, and the bounded `log` window is not
   * reconstructable. Omitted (treated as `false`).
   */
  eliminated?: boolean;
  /**
   * Whether the receiver's own seat has a live connection (issue #553) — see
   * {@link OpponentView.connected}, including its absent-means-`true` rule. Trivially
   * true for the connection reading it; present so a seat-cluster surface reads the
   * same field for every seat instead of special-casing itself.
   */
  connected?: boolean;
  /**
   * Whether the receiver's own seat is AI-controlled (issue #553) — see
   * {@link OpponentView.ai}. True only for the server's in-process AI driver, which
   * receives the same view a human would. Omitted (treated as `false`).
   */
  ai?: boolean;
}

/** A named counter on a permanent. */
export interface Counter {
  /** Counter name, e.g. `"+1/+1"` or `"loyalty"`. */
  kind: string;
  /** How many of this counter are present. */
  count: number;
}

/** A permanent on the battlefield with its server-computed characteristics. */
export interface Permanent {
  /** Entity id of this permanent. */
  id: EntityId;
  /** Player who currently controls it. */
  controller: PlayerId;
  /** Player who owns it (matters when control changes). */
  owner: PlayerId;
  /** The permanent's current (computed) card face. */
  card: CardView;
  /** Whether the permanent is tapped. Omitted (defaults to `false`) when untapped. */
  tapped?: boolean;
  /**
   * Whether this permanent is currently attacking — declared as an attacker this
   * combat (CR 508). Server-computed; the client displays it and never derives it.
   * Omitted (treated as `false`) when it is not attacking.
   */
  attacking?: boolean;
  /**
   * The defending player this permanent is attacking (CR 508.1a) as their
   * {@link EntityId} — the multiplayer generalization of {@link attacking} (issue
   * #341/#345). Omitted when not attacking; a two-player client may ignore it since
   * the sole opponent is the only defender. Server-computed; never derived.
   */
  attacking_player?: EntityId;
  /**
   * The permanent this one is blocking, if it was declared as a blocker this combat
   * (CR 509): the attacker's {@link EntityId}. Omitted when it is not blocking.
   * Several blockers may name the same attacker. Server-computed; the client renders
   * the relationship and derives no legality from it.
   */
  blocking?: EntityId;
  /**
   * Marked combat damage on this permanent this turn (CR 120.3), the value the
   * server compares against toughness. Server-computed; the client displays it
   * verbatim and never predicts it. Omitted (treated as `0`) when none is marked.
   */
  damage?: number;
  /**
   * The host permanent this one is attached to, if any (CR 303.4): an Aura names
   * the object it enchants, as that host's {@link EntityId} — the same reference
   * shape {@link Permanent.blocking} uses. Omitted for an unattached permanent.
   * The client clusters the attachment with its host and derives no rules from it.
   */
  attached_to?: EntityId;
  /**
   * Whether this permanent **is** its controller's commander (CR 903.3, issue #553):
   * the server-computed marker the commander crown renders from. The client must not
   * infer it — a commander on the battlefield is an ordinary permanent, and
   * "legendary creature" is neither necessary (a commander may be a planeswalker) nor
   * sufficient (most legends are not commanders). Omitted (treated as `false`) for
   * every other permanent and in every non-Commander game.
   */
  is_commander?: boolean;
  /** Named counters and their quantities. */
  counters?: Counter[];
}

/**
 * Every {@link StackItemKind} value, mirroring the `StackItemKind` enum's
 * snake_case serde encoding in `crates/rune-protocol/src/card.rs`. This is the
 * single source of truth: the {@link StackItemKind} union is derived from it and
 * {@link isStackItemKind} validates a wire value against it, so a kind added here
 * can never drift out of the type (and vice versa).
 */
export const STACK_ITEM_KINDS = ['spell', 'ability'] as const;

/**
 * What an object on the stack is (issue #550); one of {@link STACK_ITEM_KINDS}:
 * - `spell` — a card cast onto the stack (CR 601); its `card` is the card being cast.
 * - `ability` — an ability on the stack (CR 113.3), activated *or* triggered; the
 *   server does not distinguish the two today, so neither may the client.
 *
 * Server-stated: the client never derives a kind from the presence of
 * {@link StackItem.source}. The union widens additively when the engine can prove a
 * finer distinction, so an unrecognized future value must be treated as
 * "unclassified" (see {@link normalizeGameView}) and rendered from `description`.
 */
export type StackItemKind = (typeof STACK_ITEM_KINDS)[number];

/** Whether a wire value is a known {@link StackItemKind}. */
export function isStackItemKind(value: unknown): value is StackItemKind {
  return typeof value === 'string' && (STACK_ITEM_KINDS as readonly string[]).includes(value);
}

/**
 * One target chosen for an object on the stack (CR 601.2c), typed at the source.
 *
 * The `kind` discriminator states what is targeted, so the client never classifies a
 * target by testing which collection its id appears in — that classification is rules
 * interpretation and belongs to the server. A `player` target carries a
 * {@link PlayerId} (the key `controller`, `seat_order`, and `player_names` share);
 * every other kind carries an {@link EntityId} from the matching collection.
 */
export type StackTarget =
  | { kind: 'player'; player: PlayerId }
  | { kind: 'permanent'; id: EntityId }
  | { kind: 'card'; id: EntityId }
  | { kind: 'stack'; id: EntityId };

/** Every {@link StackTarget} `kind` tag, for runtime validation of the wire. */
export const STACK_TARGET_KINDS = ['player', 'permanent', 'card', 'stack'] as const;

/**
 * One object on the stack — a spell or an ability. Ability entries carry their
 * source permanent so the client can point back at it.
 *
 * `description` is the authoritative human-readable text; `kind`, `targets`, and
 * `card` are additive structure for presentation geometry (issue #550). The client
 * must never parse one to recover the other.
 */
export interface StackItem {
  /** Entity id of this stack object. */
  id: EntityId;
  /** Player who controls it (chooses targets/resolution). */
  controller: PlayerId;
  /** Spell name or ability text as it should be displayed. */
  description: string;
  /** Source permanent for an ability; absent for a spell. */
  source?: EntityId;
  /**
   * What this object is. Server-stated and never inferred from `source`. Absent when
   * the entry is unclassified — an older server that omits the field, or a future
   * kind this client does not know; render such an entry generically.
   */
  kind?: StackItemKind;
  /**
   * The targets this object named, in the order its effects consume them (CR
   * 601.2c) — the ordering the client's target numerals (①②③) come from. Omitted on
   * the wire when empty; {@link normalizeGameView} materializes it to `[]`, and a
   * targetless entry is normal, not an error.
   *
   * The list is as it currently stands: a target that has become illegal stays named
   * until the object resolves or fizzles (CR 608.2b), so a client that reconnects
   * mid-resolution rebuilds exactly the relationships the game holds.
   */
  targets?: StackTarget[];
  /**
   * The card face to render: for a `spell` the card being cast, for an `ability` the
   * current face of its source permanent (the entry's thumbnail). Absent when there
   * is no face to show — notably an ability whose source has already left the
   * battlefield (CR 608.2) — or when omitted by an older server.
   */
  card?: CardView;
}

/** A public, ordered pile owned by one player (graveyard or exile). */
export interface ZonePile {
  /** Player who owns the pile. */
  player_id: PlayerId;
  /** Cards in zone order (top last). */
  cards: CardView[];
}
