/**
 * Card and board representations: cards, permanents, zones, and player views.
 */

import type { EntityId, PlayerId } from './index.js';

/**
 * A card object, shown only to a player entitled to see it. All characteristics
 * are server-computed; the client never derives them.
 */
export interface CardView {
  /** Entity id of this card instance. */
  id: EntityId;
  /** Display name. */
  name: string;
  /** e.g. `"Creature — Elf Warrior"`. */
  type_line: string;
  /** Displayed mana cost string, e.g. `"{1}{G}"`. Absent for cards without one. */
  mana_cost?: string;
  /**
   * The card's rules text, generated by the server from the card's ability IR
   * (ADR 0018). Never computed here: the client renders this string and never
   * derives, formats, or infers a card's rules. Omitted (defaults to `""`) when the
   * card has no rules.
   */
  rules_text?: string;
  /**
   * The card's stable presentation identity — the same string for every copy of a
   * card, in every game, across server rebuilds (unlike {@link CardView.id}, which is
   * a per-game entity handle). Reserved for a future *client-local* cache that could
   * enrich presentation by identity; nothing renders from it today, and a client that
   * ignores it presents the card completely from `rules_text`.
   */
  functional_id?: string;
  /** Displayed power (a string so `*` round-trips). Present only for creatures. */
  power?: string;
  /** Displayed toughness; see {@link CardView.power}. Present only for creatures. */
  toughness?: string;
  /**
   * The card's keyword abilities as lowercase wire names (e.g. `"flying"`,
   * `"first_strike"`), server-computed for display. The client renders badges and
   * never derives them. Omitted (treated as empty) when the card has none.
   */
  keywords?: string[];
}

/**
 * What the receiving player may know about an opponent: hidden zones are reduced
 * to counts, public state is exact.
 */
export interface OpponentView {
  /** Which opponent this describes. */
  player_id: PlayerId;
  /** Number of cards in hand (contents hidden). */
  hand_size: number;
  /** Current life total. */
  life: number;
  /** Number of cards left in library. */
  library_size: number;
  /** Number of cards in the graveyard. */
  graveyard_size: number;
  /** Free-form status labels (e.g. `"monarch"`) for display only. */
  statuses?: string[];
  /** Whether this opponent has been eliminated — they left the game (CR 800.4a,
   * issue #342/#345). Omitted (treated as `false`) in a two-player game. */
  eliminated?: boolean;
}

/**
 * The receiver's own public stats — the self-counterpart of {@link OpponentView}.
 * Hand contents ride in {@link GameView.my_hand} and mana in
 * {@link GameView.mana_pool}; this carries the two public numbers those omit — the
 * receiver's life total and library size — so a player can read their own life, not
 * only their opponents'. No hidden information (a player's own life and library size
 * are public). An older server may omit it; {@link normalizeGameView} defaults it.
 */
export interface SelfView {
  /** The receiver's current life total. */
  life: number;
  /** Number of cards left in the receiver's library. */
  library_size: number;
}

/** A named counter on a permanent. */
export interface Counter {
  /** Counter name, e.g. `"+1/+1"` or `"loyalty"`. */
  kind: string;
  /** How many of this counter are present. */
  count: number;
}

/** A permanent on the battlefield with its server-computed characteristics. */
export interface Permanent {
  /** Entity id of this permanent. */
  id: EntityId;
  /** Player who currently controls it. */
  controller: PlayerId;
  /** Player who owns it (matters when control changes). */
  owner: PlayerId;
  /** The permanent's current (computed) card face. */
  card: CardView;
  /** Whether the permanent is tapped. Omitted (defaults to `false`) when untapped. */
  tapped?: boolean;
  /**
   * Whether this permanent is currently attacking — declared as an attacker this
   * combat (CR 508). Server-computed; the client displays it and never derives it.
   * Omitted (treated as `false`) when it is not attacking.
   */
  attacking?: boolean;
  /**
   * The defending player this permanent is attacking (CR 508.1a) as their
   * {@link EntityId} — the multiplayer generalization of {@link attacking} (issue
   * #341/#345). Omitted when not attacking; a two-player client may ignore it since
   * the sole opponent is the only defender. Server-computed; never derived.
   */
  attacking_player?: EntityId;
  /**
   * The permanent this one is blocking, if it was declared as a blocker this combat
   * (CR 509): the attacker's {@link EntityId}. Omitted when it is not blocking.
   * Several blockers may name the same attacker. Server-computed; the client renders
   * the relationship and derives no legality from it.
   */
  blocking?: EntityId;
  /**
   * Marked combat damage on this permanent this turn (CR 120.3), the value the
   * server compares against toughness. Server-computed; the client displays it
   * verbatim and never predicts it. Omitted (treated as `0`) when none is marked.
   */
  damage?: number;
  /**
   * The host permanent this one is attached to, if any (CR 303.4): an Aura names
   * the object it enchants, as that host's {@link EntityId} — the same reference
   * shape {@link Permanent.blocking} uses. Omitted for an unattached permanent.
   * The client clusters the attachment with its host and derives no rules from it.
   */
  attached_to?: EntityId;
  /** Named counters and their quantities. */
  counters?: Counter[];
}

/**
 * One object on the stack — a spell or an ability. Ability entries carry their
 * source permanent so the client can point back at it.
 */
export interface StackItem {
  /** Entity id of this stack object. */
  id: EntityId;
  /** Player who controls it (chooses targets/resolution). */
  controller: PlayerId;
  /** Spell name or ability text as it should be displayed. */
  description: string;
  /** Source permanent for an ability; absent for a spell. */
  source?: EntityId;
}

/** A public, ordered pile owned by one player (graveyard or exile). */
export interface ZonePile {
  /** Player who owns the pile. */
  player_id: PlayerId;
  /** Cards in zone order (top last). */
  cards: CardView[];
}
