/**
 * Public card catalog and format deck rules for deck-building.
 */

import type { CardIdentity, GameSetupId } from './lobby.js';

/**
 * The current schema version carried in {@link CatalogView.catalog_version}. A single
 * frame carries the whole catalog today; the version leaves room to add paging later
 * without breaking older clients (issue #367).
 */
export const CATALOG_VERSION = 1;

/**
 * One supported card's public characteristics in the lobby {@link CatalogView} (issue
 * #367) — the browse-time counterpart of the in-game {@link CardView}. It carries the
 * card's stable identity and the same server-computed characteristics (including the
 * generated rules text) but no per-game entity id, since a catalog entry names a card by
 * identity, not a specific instance.
 */
export interface CatalogCard {
  /** Stable functional identity (ADR 0018 §3) — the same handle a decklist uses. */
  functional_id: CardIdentity;
  /** Display name. */
  name: string;
  /** Full type line, incl. any basic supertype, e.g. `"Basic Land — Forest"`. */
  type_line: string;
  /** Displayed mana cost string, e.g. `"{1}{G}"`. Absent for a card without one. */
  mana_cost?: string;
  /**
   * Rules text, generated by the server from the card's ability IR — identical to what
   * an in-game {@link CardView.rules_text} shows (ADR 0018). Omitted (treated as `""`)
   * for a vanilla card with no rules.
   */
  rules_text?: string;
  /** Displayed power (a string so `*` round-trips). Present only for creatures. */
  power?: string;
  /** Displayed toughness; see {@link CatalogCard.power}. Present only for creatures. */
  toughness?: string;
  /** Keyword abilities as lowercase wire names (e.g. `"flying"`). Omitted when empty. */
  keywords?: string[];
}

/**
 * One advertised format's public deck rules and seat range in the lobby
 * {@link CatalogView} (issue #367, ADR 0013 §4) — exactly the server-side deck-legality
 * policy a `submit_deck` is validated against, so a client can build a legal deck ahead
 * of time. A permissive format advertises its permissiveness honestly, as absent (`None`)
 * upper bounds rather than a sentinel number.
 */
export interface CatalogFormat {
  /** The `game_setup` id naming this format — the same id a {@link RoomConfig} carries. */
  game_setup: GameSetupId;
  /** Fewest cards a legal deck may hold (inclusive); `0` for no minimum. */
  min_deck_size: number;
  /** Most cards a legal deck may hold (inclusive); absent for no upper bound. */
  max_deck_size?: number;
  /** Most copies of any single non-exempt card; absent for **no copy limit**. */
  max_copies?: number;
  /** Whether basic lands are exempt from {@link CatalogFormat.max_copies} (CR 100.2a). */
  basic_land_exempt: boolean;
  /**
   * Whether a legal deck must designate a **commander** (CR 903.3), advertised so a
   * client learns the requirement from format metadata instead of hardcoding the format
   * name (issue #394). Default-elided on the wire; normalized to `false` when absent.
   */
  requires_commander: boolean;
  /**
   * Whether the format enforces **color-identity containment** — every card's color
   * identity must fit within the commander's (CR 903.4, issue #394). Meaningful only
   * alongside {@link CatalogFormat.requires_commander}. Default-elided; `false` when absent.
   */
  enforce_color_identity: boolean;
  /** Fewest seats a room using this format may have (inclusive). */
  min_seats: number;
  /** Most seats a room using this format may have (inclusive). */
  max_seats: number;
}

/**
 * One selectable AI opponent kind a host may seat (issue #415), as listed in a
 * {@link CatalogView}. A stable {@link AiOption.id} the {@link AddAiCommand} carries plus
 * display metadata; the set is server-owned, so a client learns the available kinds from
 * this list rather than hardcoding them.
 */
export interface AiOption {
  /** The stable id of the AI kind — the value {@link AddAiCommand.kind} carries and a
   * {@link SeatView.ai} reports (e.g. `"random"`). */
  id: string;
  /** A short human-readable name for the kind (e.g. `"Random"`). */
  name: string;
  /** A one-line description of how the kind plays, for the seating UI. Absent when empty. */
  description?: string;
}

/**
 * The public card catalog and format deck rules — a lobby-phase server→client frame
 * answered to a {@link RequestCatalogCommand} (issue #367). A versioned single-frame
 * projection of the complete supported card pool and every advertised format, built
 * server-side from the one embedded card database and the format registry. Public data
 * only — never a deck, roster, or game state. It is distinguished on the wire from a
 * {@link LobbyView} by its `catalog_version` field and from a {@link GameView} /
 * {@link SpectatorView} by carrying no `phase`.
 */
export interface CatalogView {
  /** The projection's schema version ({@link CATALOG_VERSION}); also the wire discriminator. */
  catalog_version: number;
  /** Every supported card, in a stable order. */
  cards: CatalogCard[];
  /** Every advertised format's deck rules and seat range. */
  formats: CatalogFormat[];
  /**
   * Every AI opponent kind a host may seat (issue #415), so a client can present the
   * choices for {@link AddAiCommand} from server metadata rather than a hardcoded list.
   * Additive; a client treats a missing field as an empty list.
   */
  ai_opponents: AiOption[];
}
