//! The lobby card-catalog projection (issue #367): the complete public card pool and
//! each advertised format's deck rules, built for a lobby-phase connection to browse
//! before any game exists.
//!
//! There is **one source of truth** in both halves. The cards are projected from the
//! single embedded [`CardDatabase`] the server already owns — no bundled catalog copy —
//! and each card's rules text is generated by [`crate::view::full_card_view`], the SAME
//! projection an in-game `CardView` uses, so a catalog entry and the in-game card of the
//! same identity can never disagree (ADR 0018 §7). The formats are projected from the
//! server's [`FormatRegistry`], the same registry the pre-game deck gate validates a
//! submitted deck against (ADR 0013 §4).
//!
//! The projection carries **public data only**: a card's characteristics and a format's
//! deck rules. It never reads a deck, a roster, a session, or any game state — there is
//! no seat or connection input to this module at all.

use rune_engine::{CardData, CardDatabase, CardId};
use rune_protocol::{CatalogCard, CatalogFormat, CatalogView, CATALOG_VERSION};

use crate::format::{Format, FormatRegistry};
use crate::view::full_card_view;

/// Project one engine [`CardData`] onto its public [`CatalogCard`].
///
/// Built via [`full_card_view`] so every server-computed characteristic — the generated
/// rules text, the type line (incl. basic supertype), keywords, P/T, mana cost — is
/// byte-for-byte what an in-game `CardView` of the same card shows. A catalog entry names
/// a card by its stable `functional_id`, not a per-game instance, so the placeholder
/// entity id `full_card_view` requires is discarded.
fn catalog_card(data: &CardData) -> CatalogCard {
    let view = full_card_view(String::new(), data);
    CatalogCard {
        functional_id: data.functional_id.to_string(),
        name: view.name,
        type_line: view.type_line,
        mana_cost: view.mana_cost,
        rules_text: view.rules_text,
        power: view.power,
        toughness: view.toughness,
        keywords: view.keywords,
    }
}

/// Project one server-side [`Format`] onto its public [`CatalogFormat`].
///
/// The internal `usize::MAX` "no copy limit" sentinel is advertised **honestly** as
/// `None` rather than a meaningless huge number, so a permissive format reads as
/// permissive (ADR 0013 §4); the deck-size upper bound is likewise `None` when unbounded.
fn catalog_format(game_setup: &str, format: &Format) -> CatalogFormat {
    let rules = &format.deck_rules;
    CatalogFormat {
        game_setup: game_setup.to_string(),
        min_deck_size: u32::try_from(rules.min_size).unwrap_or(u32::MAX),
        max_deck_size: rules
            .max_size
            .map(|max| u32::try_from(max).unwrap_or(u32::MAX)),
        max_copies: (rules.max_copies != usize::MAX)
            .then(|| u32::try_from(rules.max_copies).unwrap_or(u32::MAX)),
        basic_land_exempt: rules.basic_land_exempt,
        min_seats: *format.seats.start(),
        max_seats: *format.seats.end(),
    }
}

/// Build the full public catalog projection (issue #367) from the one embedded
/// [`CardDatabase`] and the [`FormatRegistry`].
///
/// The cards are every entry of the database, in [`CardId`] order (deterministic, since
/// ids are interned from the catalog's sort order); the formats are every registered
/// format, sorted by `game_setup` id for a stable wire order. Public data only.
pub(crate) fn build_catalog(db: &CardDatabase, formats: &FormatRegistry) -> CatalogView {
    let cards = (0..db.len() as u64)
        .map(CardId)
        .filter_map(|id| db.card(id))
        .map(catalog_card)
        .collect();
    let mut formats: Vec<CatalogFormat> = formats
        .iter()
        .map(|(id, format)| catalog_format(id, format))
        .collect();
    formats.sort_by(|a, b| a.game_setup.cmp(&b.game_setup));
    CatalogView {
        catalog_version: CATALOG_VERSION,
        cards,
        formats,
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use std::collections::BTreeSet;

    use super::*;
    use crate::rules_text::rules_text;
    use rune_engine::{scripted_rules_text, FunctionalId};

    fn db() -> CardDatabase {
        CardDatabase::bundled().expect("bundled cards")
    }

    fn catalog() -> CatalogView {
        build_catalog(&db(), &FormatRegistry::with_defaults())
    }

    #[test]
    fn covers_exactly_the_card_database() {
        // The projection is the whole database and nothing invented: one entry per card,
        // and the set of advertised identities equals the database's own set.
        let db = db();
        let catalog = build_catalog(&db, &FormatRegistry::with_defaults());
        assert_eq!(catalog.cards.len(), db.len());

        let advertised: BTreeSet<String> = catalog
            .cards
            .iter()
            .map(|card| card.functional_id.clone())
            .collect();
        let actual: BTreeSet<String> = (0..db.len() as u64)
            .map(CardId)
            .filter_map(|id| db.card(id))
            .map(|data| data.functional_id.to_string())
            .collect();
        assert_eq!(advertised, actual);
        // No duplicates snuck in (every identity is distinct).
        assert_eq!(advertised.len(), catalog.cards.len());
    }

    #[test]
    fn rules_text_matches_the_in_game_generator() {
        // The acceptance guarantee: a catalog entry's rules text is byte-for-byte what the
        // in-game generator produces for the same card, for every card in the database.
        let db = db();
        let catalog = build_catalog(&db, &FormatRegistry::with_defaults());
        for card in &catalog.cards {
            let id = db
                .card_id(&FunctionalId::try_from(card.functional_id.clone()).unwrap())
                .expect("every advertised identity resolves");
            let data = db.card(id).unwrap();
            let expected = rules_text(data, scripted_rules_text(&data.functional_id));
            assert_eq!(
                card.rules_text, expected,
                "{} rules text drifted from the in-game generator",
                card.functional_id
            );
            // The other characteristics also mirror the in-game projection.
            assert_eq!(card.name, data.name);
            assert_eq!(card.type_line, data.type_line());
            assert_eq!(card.power, data.power.map(|p| p.to_string()));
            assert_eq!(card.toughness, data.toughness.map(|t| t.to_string()));
        }
    }

    #[test]
    fn advertises_each_registered_format_with_its_deck_rules_and_seats() {
        let catalog = catalog();
        let find = |id: &str| {
            catalog
                .formats
                .iter()
                .find(|f| f.game_setup == id)
                .unwrap_or_else(|| panic!("format {id} is advertised"))
                .clone()
        };

        // The competitive starter format enforces real deck legality and duels two seats.
        let starter = find("starter-1v1");
        assert_eq!(starter.min_deck_size, 40);
        assert_eq!(starter.max_deck_size, None);
        assert_eq!(starter.max_copies, Some(4));
        assert!(starter.basic_land_exempt);
        assert_eq!((starter.min_seats, starter.max_seats), (2, 2));

        // The free-for-all format seats 3–4 (issue #349).
        let ffa = find("standard_ffa");
        assert_eq!((ffa.min_seats, ffa.max_seats), (3, 4));

        // The commander format advertises its 100-card singleton rules and 2–4 seats
        // honestly (issue #372).
        let commander = find("commander");
        assert_eq!(commander.min_deck_size, 100);
        assert_eq!(commander.max_deck_size, Some(100));
        assert_eq!(commander.max_copies, Some(1));
        assert!(commander.basic_land_exempt);
        assert_eq!((commander.min_seats, commander.max_seats), (2, 4));

        // Every registered id is advertised, sorted deterministically by id.
        let ids: Vec<&str> = catalog
            .formats
            .iter()
            .map(|f| f.game_setup.as_str())
            .collect();
        assert_eq!(
            ids,
            [
                "1v1",
                "commander",
                "ffa-4",
                "standard_2p",
                "standard_ffa",
                "starter-1v1"
            ]
        );
    }

    #[test]
    fn a_permissive_format_advertises_its_permissiveness_honestly() {
        // The catch-all default imposes no size or copy limit; that reads as `None`
        // upper bounds and a zero minimum, never a `usize::MAX` sentinel leaking onto
        // the wire as a huge number.
        let open = catalog()
            .formats
            .into_iter()
            .find(|f| f.game_setup == "standard_2p")
            .expect("standard_2p is advertised");
        assert_eq!(open.min_deck_size, 0);
        assert_eq!(open.max_deck_size, None);
        assert_eq!(open.max_copies, None);
    }

    #[test]
    fn catalog_is_versioned() {
        assert_eq!(catalog().catalog_version, CATALOG_VERSION);
    }
}
