//! Card data: resolving a [`CardId`] to its immutable characteristics.
//!
//! The engine performs no I/O. The card snapshot is a JSON file embedded at
//! compile time with [`include_str!`] and parsed in memory; there is no
//! filesystem or network access here. serde is permitted for exactly this
//! purpose — see `docs/decisions/0006-serde-in-engine.md`.
//!
//! A card is a **functional definition** ([`CardData`], ADR 0018 §2): the
//! printing-independent rules object for one card, authored by hand under a stable
//! [`FunctionalId`] and versioned by [`SCHEMA_VERSION`]. It holds only what the
//! engine executes or a presentation layer derives from — never an upstream
//! presentation asset (flavor text, image URI, artist, frame), and **no rules prose
//! of any kind**: the text a player reads is generated by the server from the ability
//! IR below (ADR 0018 §7), so it cannot drift from what the card actually does. That
//! prohibition is structural, not a convention: [`CardData`] and [`PrintingEntry`]
//! both reject unknown fields, so such a field fails the load instead of being
//! ignored. The authored schema is documented in `docs/card-schema.md`.

use std::collections::HashMap;
use std::fmt;

use serde::Deserialize;

use crate::ability::{Ability, Effect, TargetSpec};
use crate::card_type::{CardType, Supertype};
use crate::catalog::{check_printings, validate_definition, Violation};
use crate::id::{CardId, FunctionalId, OracleId};
use crate::mana::Color;
use crate::scripted::{is_scripted, scripted_abilities};
use crate::state::Permanent;

pub use crate::catalog::SCHEMA_VERSION;

/// One functional definition embedded at compile time (ADR 0018 §4).
///
/// The build script pairs each `data/catalog/<functional_id>.json` with the [`CardId`]
/// it interned for it, so the handle is assigned by the catalog rather than written
/// into the card file by hand (ADR 0018 §3).
struct CatalogEntry {
    /// The handle this definition interned to in *this build* — its index in
    /// [`CATALOG`], which is sorted by [`FunctionalId`] byte value.
    id: CardId,
    /// The definition's authored identity, which is also its file name. Carried here
    /// so the loader can re-check the file-name rule that `build.rs` enforced.
    functional_id: &'static str,
    /// The embedded JSON: one functional definition.
    json: &'static str,
}

/// One embedded set snapshot: a set code paired with its printing records.
///
/// The set code comes from the file name (`FIX.json` → `FIX`), so adding a set is
/// adding a file — there is no hand-written list to forget to update.
struct SetSnapshot {
    /// The set's code, used as the first half of every printing key.
    code: &'static str,
    /// The embedded JSON: an array of printing records for this set.
    json: &'static str,
}

// The generated catalog manifest: `const CATALOG: &[CatalogEntry]` and
// `const SET_MANIFEST: &[SetSnapshot]`, both `include_str!`-embedding the files under
// `data/` (ADR 0018 §4). `build.rs` writes it; nothing here is hand-maintained, so
// adding a card edits zero existing lines. The engine still does zero runtime I/O:
// this is the same compile-time embedding ADR 0006 sanctioned, with the build script
// — not a human — authoring the `include_str!` list.
include!(concat!(env!("OUT_DIR"), "/catalog_manifest.rs"));

/// A keyword ability printed on a card (CR 702). Closed set, deserialized from
/// lowercase names (e.g. `"flying"`, `"first_strike"`).
///
/// This is the printed keyword representation the layer system seeds from; a
/// permanent's *current* keywords are the printed [`CardData::keywords`] unioned
/// with any granted by continuous effects at CR 613 layer 6 (see
/// [`characteristics`](crate::characteristics::characteristics)). All eight variants are
/// enforced: [`Flying`](Keyword::Flying), [`Reach`](Keyword::Reach),
/// [`Vigilance`](Keyword::Vigilance), and [`Haste`](Keyword::Haste) at
/// combat-declaration time (keywords I), and
/// [`FirstStrike`](Keyword::FirstStrike), [`Trample`](Keyword::Trample),
/// [`Deathtouch`](Keyword::Deathtouch), and [`Lifelink`](Keyword::Lifelink) at
/// combat-damage time (keywords II — see [`crate::combat::combat_damage`]).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Keyword {
    /// Flying (CR 702.9): can be blocked only by creatures with flying or reach.
    Flying,
    /// Reach (CR 702.17): can block creatures with flying.
    Reach,
    /// Vigilance (CR 702.20): attacking doesn't cause the creature to tap.
    Vigilance,
    /// Haste (CR 702.10): ignores the summoning-sickness restriction on attacking.
    Haste,
    /// First strike (CR 702.7): deals combat damage in a first combat-damage step.
    FirstStrike,
    /// Trample (CR 702.19): a blocked creature assigns excess combat damage to the
    /// player it is attacking.
    Trample,
    /// Deathtouch (CR 702.2): any nonzero damage it deals is lethal.
    Deathtouch,
    /// Lifelink (CR 702.15): damage it deals also gains its controller that much
    /// life.
    Lifelink,
}

/// The enchant ability and static power/toughness grant of an Aura (CR 303.4).
///
/// An Aura is an Enchantment that enters the battlefield attached to another
/// object (CR 303.4). This value bundles the two things the engine needs to model
/// one at the scope of issue #152: its **enchant restriction** (CR 303.4a) — the
/// [`TargetSpec`] the Aura chooses a target for as it is cast (CR 601.2c) and the
/// class of object it may legally stay attached to — and the continuous
/// power/toughness modification it applies to that object at CR 613 layer 7c.
///
/// The modification is stored as raw signed printed data; the *contribution* to a
/// host's current characteristics is derived on demand from the attachment via
/// [`characteristics`](crate::characteristics::characteristics), never stored
/// (ADR 0010). Enchant-creature Auras that grant power/toughness (CR 613.7c) and/or
/// keyword abilities (CR 613.1f, layer 6) are modeled here; enchant-player/land and
/// Aura movement are out of scope.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize)]
pub struct AuraGrant {
    /// The enchant restriction (CR 303.4a): what this Aura may be attached to,
    /// expressed as the [`TargetSpec`] a target is chosen for at cast (CR 601.2c)
    /// and re-checked by the CR 704.5m state-based action while it stays attached.
    pub enchant: TargetSpec,
    /// The signed amount this Aura adds to the enchanted object's power at CR 613
    /// layer 7c. Negative shrinks (e.g. a `-2/-2` Aura). Defaults to `0`.
    #[serde(default)]
    pub power: i32,
    /// The signed amount this Aura adds to the enchanted object's toughness at CR
    /// 613 layer 7c. Negative shrinks — enough can drop toughness to 0 or less and
    /// let the CR 704.5f state-based action put the host into its graveyard.
    /// Defaults to `0`.
    #[serde(default)]
    pub toughness: i32,
    /// The keyword abilities this Aura grants the enchanted object at CR 613 layer 6
    /// (CR 613.1f) — e.g. an Aura granting flying. Empty for a P/T-only Aura. Each
    /// granted keyword is folded into the host's computed keyword set while the Aura
    /// is attached and is indistinguishable from a printed keyword; the grant
    /// vanishes the instant the Aura leaves. Redundant grants are idempotent.
    #[serde(default)]
    pub keywords: Vec<Keyword>,
}

/// One functional definition: the static, printing-independent rules object for a
/// card (ADR 0018 §2).
///
/// This is the immutable data the engine reasons about. It holds no zone, no
/// battlefield identity, and no per-game state — those live on
/// [`crate::GameState`]. Current characteristics (after continuous effects) are
/// computed by the layer system, never stored here.
///
/// `deny_unknown_fields` is what keeps the schema *functional*: an upstream
/// presentation asset — `flavor_text`, `image_uris`, `artist`, a frame or watermark
/// — is a parse error rather than a silently ignored field, so no such data can
/// enter the catalog by accident (ADR 0018 §2, `docs/brief.md` Legal
/// Considerations). It is also why this type, not a wrapper, is the direct
/// deserialization target: serde does not enforce `deny_unknown_fields` through a
/// `flatten`ed field.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CardData {
    /// The schema version this definition is authored against; must be
    /// [`SCHEMA_VERSION`] (ADR 0018 §2).
    pub schema_version: u32,
    /// This definition's authored, stable identity (ADR 0018 §3) — what printings
    /// and decklists reference, and what survives a rebuild, unlike the [`CardId`]
    /// it is interned to.
    pub functional_id: FunctionalId,
    /// The card's name (e.g. `"Thornback Boar"`).
    pub name: String,
    /// Printed supertypes (e.g. `Basic`, `Legendary`); empty for most cards. Part
    /// of the structured type line the engine reasons about — the display string
    /// is rendered by [`CardData::type_line`], never parsed back.
    #[serde(default)]
    pub supertypes: Vec<Supertype>,
    /// Printed card types (e.g. `Creature`, `Land`). Every card has at least one.
    pub types: Vec<CardType>,
    /// Printed subtypes (e.g. `"Elf"`, `"Scout"`, `"Forest"`); empty for many
    /// cards. Open-ended, so kept as strings rather than an enum.
    #[serde(default)]
    pub subtypes: Vec<String>,
    /// The mana cost in curly-brace notation (e.g. `"{2}{G}"`); empty for cards
    /// with no mana cost, such as basic lands.
    pub mana_cost: String,
    /// The card's colors (CR 105.2); empty for a colorless card.
    ///
    /// Authored explicitly rather than re-derived by parsing [`Self::mana_cost`]'s
    /// pips (ADR 0018 §2) — the same "structured, never parsed back" discipline
    /// [`CardData::type_line`] uses. A colorless-cost-but-colored card is therefore
    /// representable without the cost string having to imply it.
    #[serde(default)]
    pub colors: Vec<Color>,
    /// Printed power, for creatures; `None` for non-creatures.
    #[serde(default)]
    pub power: Option<i32>,
    /// Printed toughness, for creatures; `None` for non-creatures.
    #[serde(default)]
    pub toughness: Option<i32>,
    /// The card's abilities as declarative data. Empty for vanilla cards. Cards
    /// whose behavior the data IR cannot express instead register abilities in
    /// [`crate::scripted`]; use [`abilities_of`] to read both sources together.
    #[serde(default)]
    pub abilities: Vec<Ability>,
    /// The effects this card's **spell ability** produces on resolution — the
    /// instant/sorcery analogue of an ability's effects (CR 608.2c). Empty for a
    /// vanilla card and for a permanent spell whose only "effect" is entering the
    /// battlefield. A targeting spell effect declares its [`crate::TargetSpec`]
    /// here exactly as an ability's effect does, so a spell chooses targets as it
    /// is cast (CR 601.2c); read them with [`spell_effects_of`].
    #[serde(default)]
    pub spell_effects: Vec<Effect>,
    /// The Aura ability of an Aura card (CR 303.4): its enchant restriction and
    /// static power/toughness grant. `None` for every non-Aura card. When present,
    /// the card is castable only with a legal enchant target (CR 303.4c/601.2c),
    /// enters attached to that target (CR 303.4d), and contributes its P/T grant to
    /// the host while attached (CR 613.7c) — see [`AuraGrant`].
    #[serde(default)]
    pub aura: Option<AuraGrant>,
    /// The card's printed keyword abilities (CR 702), e.g. flying or haste. Empty
    /// for a card with none. Read with [`CardData::has_keyword`] for the *printed*
    /// set; a permanent's *current* keywords fold these together with any granted by
    /// continuous effects (CR 613.1f, layer 6) via
    /// [`characteristics`](crate::characteristics::characteristics), which the combat
    /// and summoning-sickness code consults.
    #[serde(default)]
    pub keywords: Vec<Keyword>,
    /// Whether this card's behavior is (also) defined in code rather than data
    /// (ADR 0018 §2; the escape hatch of ADR 0007).
    ///
    /// `true` means [`crate::scripted`] carries an arm for this definition's
    /// interned [`CardId`]. Authored explicitly so the two tiers are declared, not
    /// inferred: today the flag is `false` on every bundled card, and no card's
    /// behavior lives in code.
    #[serde(default)]
    pub scripted: bool,
}

impl CardData {
    /// Render the printed type line for display, e.g. `"Basic Land — Forest"` or
    /// `"Creature — Elf Scout"`. Supertypes and types are joined with spaces;
    /// subtypes, if any, follow an em dash. This is the single source for the
    /// display string — it is never parsed back into types.
    #[must_use]
    pub fn type_line(&self) -> String {
        let mut head: Vec<&str> = Vec::new();
        head.extend(self.supertypes.iter().map(|s| s.display()));
        head.extend(self.types.iter().map(|t| t.display()));
        let mut line = head.join(" ");
        if !self.subtypes.is_empty() {
            line.push_str(" — ");
            line.push_str(&self.subtypes.join(" "));
        }
        line
    }

    /// Whether the card has printed card type `card_type`.
    #[must_use]
    pub fn has_type(&self, card_type: CardType) -> bool {
        self.types.contains(&card_type)
    }

    /// Whether this is a permanent card — one that enters the battlefield when
    /// it resolves. True when any printed [`CardType`] is a permanent type
    /// (land, creature, artifact, enchantment, planeswalker, or battle); false
    /// for an instant/sorcery-only card, which resolves to a graveyard instead
    /// (CR 608.3). Keyed off the structured types, never a parsed string, and
    /// matched exhaustively so a new [`CardType`] must be classified here.
    #[must_use]
    pub fn is_permanent(&self) -> bool {
        self.types.iter().any(|t| match t {
            CardType::Land
            | CardType::Creature
            | CardType::Artifact
            | CardType::Enchantment
            | CardType::Planeswalker
            | CardType::Battle => true,
            CardType::Instant | CardType::Sorcery => false,
        })
    }

    /// Whether the card has printed subtype `subtype` (case-sensitive, as printed).
    #[must_use]
    pub fn has_subtype(&self, subtype: &str) -> bool {
        self.subtypes.iter().any(|s| s == subtype)
    }

    /// The ordered [`TargetSpec`]s a player chooses a target for when **casting**
    /// this card as a spell (CR 601.2c), in slot order.
    ///
    /// An Aura contributes its enchant restriction (CR 303.4a) as the first slot —
    /// the object it will be attached to — and every card contributes the target
    /// specs of its spell-ability effects ([`Self::spell_effects`]). The two are
    /// disjoint in practice (an Aura has no spell effects), but both are honored so
    /// a single accessor drives casting legality ([`crate::valid_actions`]), the
    /// per-slot candidate enumeration, and the on-resolution fizzle re-check
    /// (CR 608.2b). Empty for a spell that chooses no targets.
    #[must_use]
    pub fn cast_target_specs(&self) -> Vec<TargetSpec> {
        let mut specs: Vec<TargetSpec> =
            self.aura.as_ref().map(|a| a.enchant).into_iter().collect();
        specs.extend(self.spell_effects.iter().filter_map(Effect::target_spec));
        specs
    }

    /// Whether the card has printed keyword ability `keyword` (CR 702). Reads only
    /// the printed [`CardData::keywords`]. A permanent's *current* keywords also
    /// include those granted by continuous effects at CR 613 layer 6; read those
    /// through [`characteristics`](crate::characteristics::characteristics).
    #[must_use]
    pub fn has_keyword(&self, keyword: Keyword) -> bool {
        self.keywords.contains(&keyword)
    }
}

/// Everything that can go wrong loading the catalog or a set (ADR 0018 §2, §5).
///
/// Every variant is a *load-time* failure: a malformed or inconsistent catalog
/// never half-loads into a database the engine would then query and find `None` in
/// mid-game. Errors are returned, not panicked on — the engine forbids panicking
/// APIs (`docs/coding-standards.md`).
#[derive(Debug)]
pub enum CatalogError {
    /// The snapshot is not valid JSON, or an entry violates the schema — including
    /// an unknown field (a presentation asset) rejected by `deny_unknown_fields`,
    /// and an effect that needs a [`TargetSpec`] and has none, which the IR makes
    /// unrepresentable rather than merely invalid.
    Json(serde_json::Error),
    /// A definition breaks one of the authored-schema rules in [`crate::Violation`] —
    /// the same checks `build.rs` runs over `data/` at compile time (ADR 0018 §5), run
    /// here over whatever snapshot was handed to the loader.
    Schema(Violation),
    /// Two definitions claim the same [`FunctionalId`]; an authored identity is
    /// never reused (ADR 0018 §3).
    DuplicateFunctionalId {
        /// The identity claimed twice.
        functional_id: FunctionalId,
    },
    /// Two definitions intern to the same [`CardId`], so one would shadow the other.
    DuplicateCardId {
        /// The handle claimed twice.
        id: CardId,
    },
    /// A definition declares `scripted: true` but [`crate::scripted`] holds no arm for
    /// it — so its behavior would be missing and no rules text could be generated for
    /// it (ADR 0018 §5, §7).
    ScriptedWithoutCode {
        /// The definition that declared the escape hatch.
        functional_id: FunctionalId,
    },
    /// [`crate::scripted`] holds an arm for a card whose definition does not declare
    /// `scripted: true` — the other direction of the same rule: the data tier and the
    /// code tier may not disagree about which cards are scripted (ADR 0018 §5).
    UndeclaredScriptedCard {
        /// The definition with a code arm it does not admit to.
        functional_id: FunctionalId,
    },
    /// A printing references a functional definition the catalog does not contain.
    UnknownFunctionalId {
        /// The set the printing was loaded from.
        set_code: String,
        /// The printing's collector number within that set.
        collector_number: String,
        /// The identity it references.
        functional_id: FunctionalId,
    },
}

impl fmt::Display for CatalogError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Json(err) => write!(f, "card data does not match the schema: {err}"),
            Self::Schema(violation) => write!(f, "{violation}"),
            Self::DuplicateFunctionalId { functional_id } => {
                write!(f, "two definitions claim the functional id {functional_id}")
            }
            Self::DuplicateCardId { id } => {
                write!(f, "two definitions intern to {id:?}")
            }
            Self::ScriptedWithoutCode { functional_id } => write!(
                f,
                "{functional_id} declares scripted: true, but crates/rune-engine/src/scripted.rs \
                 has no arm for it (it needs both its abilities and its rules text)"
            ),
            Self::UndeclaredScriptedCard { functional_id } => write!(
                f,
                "crates/rune-engine/src/scripted.rs has an arm for {functional_id}, \
                 which does not declare scripted: true"
            ),
            Self::UnknownFunctionalId {
                set_code,
                collector_number,
                functional_id,
            } => write!(
                f,
                "printing {set_code} #{collector_number} references {functional_id}, \
                 which is not in the catalog"
            ),
        }
    }
}

impl std::error::Error for CatalogError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Json(err) => Some(err),
            _ => None,
        }
    }
}

impl From<serde_json::Error> for CatalogError {
    fn from(err: serde_json::Error) -> Self {
        Self::Json(err)
    }
}

impl From<Violation> for CatalogError {
    fn from(violation: Violation) -> Self {
        Self::Schema(violation)
    }
}

/// An immutable, `CardId`-keyed database of functional definitions.
///
/// Built from a JSON snapshot (the bundled one via [`CardDatabase::bundled`], or
/// any snapshot via [`CardDatabase::from_json`]). Lookups are pure: the database
/// never mutates and holds no game state. It also indexes each definition's
/// authored [`FunctionalId`], which is how a printing (and, later, a decklist)
/// resolves to the interned [`CardId`] every rules read goes through.
#[derive(Clone, Debug, Default)]
pub struct CardDatabase {
    cards: HashMap<CardId, CardData>,
    interned: HashMap<FunctionalId, CardId>,
}

impl CardDatabase {
    /// Load the database from the compile-time-embedded catalog (ADR 0018 §4).
    ///
    /// Reads the manifest `build.rs` generated: one entry per
    /// `data/catalog/<functional_id>.json`, already interned in sorted
    /// [`FunctionalId`] order. No filesystem access happens here — every definition is
    /// an `include_str!`ed `&'static str` by the time this runs.
    ///
    /// # Errors
    /// Returns a [`CatalogError`] if an embedded definition does not parse or does not
    /// validate. `build.rs` ran the same schema checks at compile time, so the only
    /// failure this can still surface is the one it cannot see: a `scripted` flag that
    /// disagrees with [`crate::scripted`] (ADR 0018 §5). It is returned rather than
    /// panicked on because the engine forbids panicking APIs.
    pub fn bundled() -> Result<Self, CatalogError> {
        let mut db = Self::default();
        for entry in CATALOG {
            let data = parse_definition(Some(entry.functional_id), entry.json)?;
            db.insert(entry.id, data)?;
        }
        Ok(db)
    }

    /// Parse a JSON snapshot (an array of functional definitions) into a database,
    /// interning a [`CardId`] for each exactly as `build.rs` does.
    ///
    /// The in-memory counterpart of [`Self::bundled`], for tests and any caller holding
    /// a snapshot rather than the bundled catalog. It applies the *same* interning rule
    /// — sort by [`FunctionalId`] byte value, assign `CardId(0..n)` (ADR 0018 §3) — so a
    /// snapshot and a build agree on handles, and no caller hand-writes one.
    ///
    /// # Errors
    /// Returns a [`CatalogError`] if `json` is not a valid snapshot: malformed JSON, an
    /// unknown (presentation) field, a schema violation ([`crate::Violation`]), a
    /// duplicated identity, or a `scripted` flag that disagrees with the code.
    pub fn from_json(json: &str) -> Result<Self, CatalogError> {
        let entries: Vec<serde_json::Value> = serde_json::from_str(json)?;
        let mut cards = Vec::with_capacity(entries.len());
        for entry in entries {
            cards.push(parse_value(None, entry)?);
        }

        // The one interning rule, shared with `build.rs`: sorted authored identity in,
        // `CardId(0..n)` out. Nothing hand-assigns a handle (ADR 0018 §3).
        cards.sort_by(|a, b| a.functional_id.cmp(&b.functional_id));

        let mut db = Self::default();
        for (index, data) in cards.into_iter().enumerate() {
            db.insert(CardId(index as u64), data)?;
        }
        Ok(db)
    }

    /// Validate one definition against the code tier and index it under both its handle
    /// and its authored identity.
    ///
    /// The schema itself was already checked by [`validate_definition`]; what is left is
    /// the rule that needs compiled Rust to answer, and so cannot live in `build.rs`.
    fn insert(&mut self, id: CardId, data: CardData) -> Result<(), CatalogError> {
        // The escape hatch is declared in data and implemented in code; the two tiers
        // must agree in both directions, or a card silently loses its behavior (and its
        // generated rules text) or silently gains behavior nobody declared (ADR 0018 §5).
        // Keyed on the authored identity, so the check does not depend on how this build
        // happened to intern the handle.
        match (data.scripted, is_scripted(&data.functional_id)) {
            (true, false) => {
                return Err(CatalogError::ScriptedWithoutCode {
                    functional_id: data.functional_id,
                })
            }
            (false, true) => {
                return Err(CatalogError::UndeclaredScriptedCard {
                    functional_id: data.functional_id,
                })
            }
            (true, true) | (false, false) => {}
        }
        if self.cards.contains_key(&id) {
            return Err(CatalogError::DuplicateCardId { id });
        }
        if self.interned.contains_key(&data.functional_id) {
            return Err(CatalogError::DuplicateFunctionalId {
                functional_id: data.functional_id,
            });
        }
        self.interned.insert(data.functional_id.clone(), id);
        self.cards.insert(id, data);
        Ok(())
    }

    /// Resolve a [`CardId`] to its characteristics, or `None` if the id is not
    /// in the database.
    #[must_use]
    pub fn card(&self, id: CardId) -> Option<&CardData> {
        self.cards.get(&id)
    }

    /// Resolve an authored [`FunctionalId`] to the [`CardId`] it is interned under
    /// in this build, or `None` if the catalog holds no such definition.
    ///
    /// The one direction that crosses from authored identity to engine handle:
    /// printings resolve through it at load time, so no runtime lookup can find a
    /// dangling reference.
    #[must_use]
    pub fn card_id(&self, functional_id: &FunctionalId) -> Option<CardId> {
        self.interned.get(functional_id).copied()
    }

    /// The number of cards in the database.
    #[must_use]
    pub fn len(&self) -> usize {
        self.cards.len()
    }

    /// Whether the database holds no cards.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.cards.is_empty()
    }
}

/// Parse one functional definition from its JSON text, validating it first.
///
/// `file_stem` is the catalog file the definition came from, so the file-name rule can
/// be checked; `None` for a snapshot with no file behind it.
fn parse_definition(file_stem: Option<&str>, json: &str) -> Result<CardData, CatalogError> {
    parse_value(file_stem, serde_json::from_str(json)?)
}

/// Validate an already-parsed definition and deserialize it into [`CardData`].
///
/// Two tiers, and both are load-bearing:
///
/// 1. [`validate_definition`] — the schema rules, run from the same source file
///    `build.rs` runs them from, so build time and load time cannot disagree.
/// 2. `serde_json::from_value` — the type system. `deny_unknown_fields` rejects a
///    presentation asset, and every targeting [`Effect`] declares its [`TargetSpec`] as
///    a required field, so an effect that needs a target and lacks one fails *here*, as
///    a parse error. That is why no validator restates it (ADR 0018 §5).
///
/// [`CardData`] is the direct deserialization target rather than a field of a wrapper,
/// because serde does not enforce `deny_unknown_fields` through a `flatten`ed field.
fn parse_value(
    file_stem: Option<&str>,
    value: serde_json::Value,
) -> Result<CardData, CatalogError> {
    validate_definition(file_stem, &value)?;
    Ok(serde_json::from_value(value)?)
}

/// A card's rarity in a given printing (ADR 0013 §1).
///
/// A purely bibliographic property of the printing, not a rule the engine reasons
/// about. Serialized lowercase to mirror Scryfall's data shape.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Rarity {
    /// Common.
    Common,
    /// Uncommon.
    Uncommon,
    /// Rare.
    Rare,
    /// Mythic rare.
    Mythic,
}

/// A purely bibliographic printing record (ADR 0013 §1).
///
/// A printing is a specific appearance of a card in a set: the functional
/// definition it prints, a collector number, and a rarity. It carries **no** name,
/// cost, types, or abilities — everything mechanical is read through its
/// [`OracleId`] against the [`CardDatabase`] — and **no** art, frame, artist, or
/// branding. That prohibition is structural: the deserializer rejects unknown
/// fields, so an `image_uris`-style field fails to parse rather than being
/// silently ignored (ADR 0013 §6, `docs/brief.md` Legal Considerations).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Printing {
    /// The card this record prints, as the handle it interned to. All rules read
    /// through this id. The record itself names the card by [`FunctionalId`]; the
    /// loader resolves that to this handle, so an unresolvable reference fails the
    /// load rather than surfacing as a `None` mid-game.
    pub oracle: OracleId,
    /// The collector number within its set (a string, e.g. `"12"` or `"100a"`).
    pub collector_number: String,
    /// The printing's rarity.
    pub rarity: Rarity,
}

/// The wire form of a [`Printing`]: strictly the bibliographic fields.
///
/// `deny_unknown_fields` is what makes the art/branding prohibition structural —
/// any field beyond these three (e.g. `image_uris`, `artist`, `frame`) is a parse
/// error (ADR 0013 §1, §6).
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct PrintingEntry {
    /// The functional definition this printing prints, by its authored identity —
    /// the identity that survives a rebuild, unlike the interned handle (ADR 0018 §3).
    functional_id: FunctionalId,
    /// The collector number within its set.
    collector_number: String,
    /// The printing's rarity.
    rarity: Rarity,
}

/// The key identifying a single printing: its set code and collector number.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct PrintingKey {
    /// The set code (the [`SetSnapshot::code`] the printing was loaded from).
    set_code: String,
    /// The collector number within that set.
    collector_number: String,
}

/// An immutable database of printing records, keyed by set code + collector
/// number, each referencing an [`OracleId`] (ADR 0013 §2).
///
/// The parallel of [`CardDatabase`] for bibliographic data. It holds **no** rules
/// logic: a printing resolves to characteristics only by looking its
/// [`Printing::oracle`] up in the oracle [`CardDatabase`]. Built from the
/// compile-time [`SET_MANIFEST`] via [`PrintingDatabase::bundled`], or from a
/// single set's JSON via [`PrintingDatabase::from_json`].
#[derive(Clone, Debug, Default)]
pub struct PrintingDatabase {
    printings: HashMap<PrintingKey, Printing>,
}

impl PrintingDatabase {
    /// Load every printing in the compile-time-embedded [`SET_MANIFEST`], resolving
    /// each record's [`FunctionalId`] against `cards`.
    ///
    /// # Errors
    /// Returns a [`CatalogError`] if any embedded set file fails to parse or
    /// references a definition `cards` does not hold. The snapshots are committed
    /// and tested, so this is not expected in practice; it is surfaced rather than
    /// panicked on because the engine forbids panicking APIs.
    pub fn bundled(cards: &CardDatabase) -> Result<Self, CatalogError> {
        let mut db = Self::default();
        for set in SET_MANIFEST {
            db.load_set(set.code, set.json, cards)?;
        }
        Ok(db)
    }

    /// Parse one set's JSON (an array of printing records) into a fresh database
    /// under `set_code`, resolving each record's [`FunctionalId`] against `cards`.
    ///
    /// # Errors
    /// Returns a [`CatalogError`] if `json` is not a valid set snapshot — including
    /// when a record carries a field beyond the bibliographic three, which is
    /// rejected by `deny_unknown_fields` — or when a record references a functional
    /// definition the catalog does not contain.
    pub fn from_json(
        set_code: &str,
        json: &str,
        cards: &CardDatabase,
    ) -> Result<Self, CatalogError> {
        let mut db = Self::default();
        db.load_set(set_code, json, cards)?;
        Ok(db)
    }

    /// Parse `json` and insert every printing under `set_code`, resolving authored
    /// identities to this build's interned handles.
    fn load_set(
        &mut self,
        set_code: &str,
        json: &str,
        cards: &CardDatabase,
    ) -> Result<(), CatalogError> {
        let entries: Vec<PrintingEntry> = serde_json::from_str(json)?;
        // Printings are keyed by (set, collector number), so a repeat would silently
        // shadow the earlier record instead of failing (ADR 0018 §5).
        check_printings(
            set_code,
            entries.iter().map(|e| e.collector_number.as_str()),
        )?;
        for entry in entries {
            let oracle = cards.card_id(&entry.functional_id).ok_or_else(|| {
                CatalogError::UnknownFunctionalId {
                    set_code: set_code.to_string(),
                    collector_number: entry.collector_number.clone(),
                    functional_id: entry.functional_id.clone(),
                }
            })?;
            let key = PrintingKey {
                set_code: set_code.to_string(),
                collector_number: entry.collector_number.clone(),
            };
            let printing = Printing {
                oracle,
                collector_number: entry.collector_number,
                rarity: entry.rarity,
            };
            self.printings.insert(key, printing);
        }
        Ok(())
    }

    /// Resolve a set code + collector number to its [`Printing`], or `None` if no
    /// such printing is embedded.
    #[must_use]
    pub fn printing(&self, set_code: &str, collector_number: &str) -> Option<&Printing> {
        self.printings.get(&PrintingKey {
            set_code: set_code.to_string(),
            collector_number: collector_number.to_string(),
        })
    }

    /// The number of printings in the database.
    #[must_use]
    pub fn len(&self) -> usize {
        self.printings.len()
    }

    /// Whether the database holds no printings.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.printings.is_empty()
    }
}

/// All abilities of a card: its data-driven [`CardData::abilities`] plus any
/// code-defined ones from [`crate::scripted`].
///
/// Returns an empty list if the id is unknown and has no scripted abilities. This
/// is the single accessor the pipeline uses so both authoring tiers are always
/// considered together.
#[must_use]
pub fn abilities_of(db: &CardDatabase, card: CardId) -> Vec<Ability> {
    let Some(data) = db.card(card) else {
        // An unknown handle has no data tier, and the code tier is keyed on the authored
        // identity this handle would have resolved to — so there is nothing to union.
        return Vec::new();
    };
    let mut abilities = data.abilities.clone();
    abilities.extend(scripted_abilities(&data.functional_id));
    abilities
}

/// The effects a spell of printed card `card` produces on resolution
/// ([`CardData::spell_effects`]), or an empty list for an unknown id or a card
/// with no spell ability.
///
/// The spell-side counterpart of [`abilities_of`]: the resolve path reads these
/// to apply a spell's effects (pairing targeting effects with the targets chosen
/// at cast), and [`crate::valid_actions`] reads them to enumerate a targeted
/// cast's requirement slots — the same effect IR, whether it rides an ability or
/// a spell.
#[must_use]
pub(crate) fn spell_effects_of(db: &CardDatabase, card: CardId) -> Vec<Effect> {
    db.card(card)
        .map(|c| c.spell_effects.clone())
        .unwrap_or_default()
}

/// Apply `perm`'s own **enters-the-battlefield self-replacement effects**
/// (CR 614.1c) to the freshly built [`Permanent`] as it enters, *before* it is
/// placed on the battlefield.
///
/// This is the replacement seam for [`Ability::EntersTapped`] and
/// [`Ability::EntersWithCounters`]: because a replacement modifies the entry
/// *event* rather than acting after it (CR 614.12), the tapped state and counters
/// must already be on `perm` at the moment it joins the battlefield — before the
/// state-based-action loop (so a 0/0 entering with two `+1/+1` counters is a 2/2
/// and survives CR 704.5f) and before any enters-the-battlefield trigger is
/// collected (so the trigger observes the replaced state). It is therefore called
/// at every battlefield-entry site (a land played, [`crate::apply_action`]; a
/// permanent spell resolving, [`crate::resolve::resolve_stack_object`]), never as
/// a post-action pipeline stage. Only the permanent's *own* replacements apply
/// here (CR 614.13 ordering among multiple external replacements is out of scope).
/// Both authoring tiers are honored via [`abilities_of`]; non-replacement
/// abilities are ignored.
pub(crate) fn apply_enters_replacements(db: &CardDatabase, perm: &mut Permanent) {
    for ability in abilities_of(db, perm.card) {
        match ability {
            Ability::EntersTapped => perm.tapped = true,
            Ability::EntersWithCounters { counter, count } => {
                *perm.counters.entry(counter).or_insert(0) += count;
            }
            Ability::Activated { .. } | Ability::Triggered { .. } => {}
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::panic)]

    use std::fmt::Write as _;
    use std::time::{Duration, Instant};

    use super::*;
    use crate::ability::{Effect, TriggerCondition};
    use crate::card_type::{CardType, Supertype};

    /// The number of functional definitions in `data/catalog/`.
    const CATALOG_SIZE: usize = 35;

    /// Every handle the bundled catalog interned: `CardId(0..n)` (ADR 0018 §3).
    fn every_id() -> impl Iterator<Item = CardId> {
        (0..CATALOG_SIZE as u64).map(CardId)
    }

    /// Resolve a card by its **authored identity**, the way every caller should.
    ///
    /// Tests name cards by `functional_id` rather than by handle because the handle is
    /// interned at build time and shifts whenever the catalog changes — hard-coding one
    /// would make an unrelated new card break this file (ADR 0018 §3).
    fn id_of(db: &CardDatabase, slug: &str) -> CardId {
        let functional_id = FunctionalId::try_from(slug.to_string()).unwrap();
        db.card_id(&functional_id)
            .unwrap_or_else(|| panic!("{slug} is not in the bundled catalog"))
    }

    /// The bundled definition of the card authored under `slug`.
    fn card_named<'a>(db: &'a CardDatabase, slug: &str) -> &'a CardData {
        db.card(id_of(db, slug)).unwrap()
    }

    #[test]
    fn bundled_snapshot_parses() {
        let db = CardDatabase::bundled().unwrap();
        assert!(!db.is_empty());
        assert_eq!(db.len(), CATALOG_SIZE);
    }

    #[test]
    fn known_id_resolves_to_expected_characteristics() {
        let db = CardDatabase::bundled().unwrap();
        let ogre = card_named(&db, "onakke_ogre");
        assert_eq!(ogre.name, "Onakke Ogre");
        assert_eq!(ogre.types, vec![CardType::Creature]);
        assert_eq!(
            ogre.subtypes,
            vec!["Ogre".to_string(), "Warrior".to_string()]
        );
        assert_eq!(ogre.type_line(), "Creature — Ogre Warrior");
        assert_eq!(ogre.mana_cost, "{2}{R}");
        assert_eq!(ogre.power, Some(4));
        assert_eq!(ogre.toughness, Some(2));
    }

    #[test]
    fn basic_land_has_no_power_or_toughness() {
        let db = CardDatabase::bundled().unwrap();
        let forest = card_named(&db, "forest");
        assert_eq!(forest.name, "Forest");
        assert_eq!(forest.supertypes, vec![Supertype::Basic]);
        assert_eq!(forest.types, vec![CardType::Land]);
        assert_eq!(forest.type_line(), "Basic Land — Forest");
        assert_eq!(forest.mana_cost, "");
        assert_eq!(forest.power, None);
        assert_eq!(forest.toughness, None);
    }

    #[test]
    fn unknown_id_resolves_to_none() {
        let db = CardDatabase::bundled().unwrap();
        assert!(db.card(CardId(9999)).is_none());
    }

    #[test]
    fn handles_are_interned_in_sorted_functional_id_order() {
        // ADR 0018 §3: `build.rs` sorts every `FunctionalId` by byte value and assigns
        // CardId(0..n) in that order. This is the whole contract between the build
        // script and the loader, so it is asserted directly rather than assumed.
        let db = CardDatabase::bundled().unwrap();

        let mut slugs: Vec<String> = every_id()
            .map(|id| db.card(id).unwrap().functional_id.to_string())
            .collect();
        let interned_order = slugs.clone();
        slugs.sort();
        assert_eq!(
            interned_order, slugs,
            "the catalog's handles are not in sorted functional-id order"
        );

        // The mapping is a bijection: every handle round-trips through its identity.
        for id in every_id() {
            assert_eq!(db.card_id(&db.card(id).unwrap().functional_id), Some(id));
        }
    }

    #[test]
    fn no_definition_carries_a_hand_written_handle() {
        // ADR 0018 §3: `CardId`s are interned, never authored. The `id` field the old
        // monolithic `oracle.json` carried is now an unknown field, so a definition that
        // tries to pin its own handle fails to parse rather than being quietly honored.
        let json = r#"[{"schema_version":1,"id":7,"functional_id":"test_boar","name":"Test Boar",
                        "types":["creature"],"mana_cost":"{G}","colors":["green"],
                        "power":1,"toughness":1}]"#;
        let err = CardDatabase::from_json(json).unwrap_err();
        assert!(
            matches!(err, CatalogError::Json(_)),
            "a hand-written `id` should be rejected as an unknown field, got {err:?}"
        );
    }

    #[test]
    fn from_json_rejects_malformed_input() {
        assert!(CardDatabase::from_json("not json").is_err());
    }

    #[test]
    fn from_json_parses_a_minimal_snapshot() {
        let json = r#"[{"schema_version":1,"functional_id":"test_wisp","name":"Test Wisp","types":["creature"],"subtypes":["Spirit"],"mana_cost":"{U}","power":1,"toughness":1}]"#;
        let db = CardDatabase::from_json(json).unwrap();
        assert_eq!(db.len(), 1);
        let wisp = card_named(&db, "test_wisp");
        assert_eq!(wisp.name, "Test Wisp");
        assert_eq!(wisp.type_line(), "Creature — Spirit");
    }

    #[test]
    fn type_line_renders_supertypes_types_and_subtypes() {
        let db = CardDatabase::bundled().unwrap();
        // Multiple subtypes are space-joined after the em dash.
        assert_eq!(
            card_named(&db, "tolarian_scholar").type_line(),
            "Creature — Human Wizard"
        );
        // A supertype precedes the card type; the land subtype follows the dash.
        assert_eq!(card_named(&db, "forest").type_line(), "Basic Land — Forest");
    }

    #[test]
    fn has_type_and_has_subtype_query_structured_types() {
        let db = CardDatabase::bundled().unwrap();
        let elves = card_named(&db, "llanowar_elves");
        assert!(elves.has_type(CardType::Creature));
        assert!(!elves.has_type(CardType::Land));
        assert!(elves.has_subtype("Elf"));
        assert!(!elves.has_subtype("Goblin"));
    }

    #[test]
    fn is_permanent_splits_permanent_types_from_instants_and_sorceries() {
        let db = CardDatabase::bundled().unwrap();
        // Creature and land are permanent cards.
        assert!(card_named(&db, "onakke_ogre").is_permanent());
        assert!(card_named(&db, "forest").is_permanent());
        // An instant-only card is not.
        let json = r#"[{"schema_version":1,"functional_id":"test_bolt","name":"Test Bolt","types":["instant"],"mana_cost":"{R}"}]"#;
        let bolt = CardDatabase::from_json(json).unwrap();
        assert!(!card_named(&bolt, "test_bolt").is_permanent());
    }

    #[test]
    fn vanilla_cards_deserialize_with_no_abilities() {
        let db = CardDatabase::bundled().unwrap();
        assert!(card_named(&db, "onakke_ogre").abilities.is_empty());
    }

    #[test]
    fn forest_has_one_activated_mana_ability() {
        let db = CardDatabase::bundled().unwrap();
        let forest = card_named(&db, "forest");
        assert_eq!(forest.abilities.len(), 1);
        assert!(crate::ability::is_mana_ability(&forest.abilities[0]));
    }

    #[test]
    fn skyscanner_has_an_etb_draw_trigger() {
        let db = CardDatabase::bundled().unwrap();
        let skyscanner = card_named(&db, "skyscanner");
        assert_eq!(
            skyscanner.abilities,
            vec![Ability::Triggered {
                event: TriggerCondition::SelfEntersBattlefield,
                effects: vec![Effect::DrawCard { count: 1 }],
            }]
        );
    }

    #[test]
    fn issue_155_etb_replacement_fixtures_carry_their_self_replacements() {
        // The bundled tapland authors an `enters_tapped` self-replacement (CR 614.1c)
        // alongside its two mana abilities. The `enters_with_counters` self-replacement
        // (CR 614.12) has no clean representative in the real M19 catalog, so it is
        // exercised through an inline definition — the sanctioned pattern for an IR
        // shape the shipped set does not use (ADR 0026).
        use crate::ability::Ability;
        use crate::state::CounterKind;
        let db = CardDatabase::bundled().unwrap();

        let land = card_named(&db, "tranquil_expanse");
        assert_eq!(land.name, "Tranquil Expanse");
        assert_eq!(land.types, vec![CardType::Land]);
        assert_eq!(
            land.abilities
                .iter()
                .filter(|a| matches!(a, Ability::EntersTapped))
                .count(),
            1,
            "the tapland enters tapped (CR 614.1c)"
        );
        // Its two tap-for-mana abilities are still present and activatable.
        assert_eq!(
            land.abilities
                .iter()
                .filter(|a| crate::ability::is_mana_ability(a))
                .count(),
            2
        );

        let json = r#"[{"schema_version":1,"functional_id":"test_broodling","name":"Test Broodling",
            "types":["creature"],"subtypes":["Insect"],"mana_cost":"{1}{G}","colors":["green"],
            "power":0,"toughness":0,
            "abilities":[{"type":"enters_with_counters","counter":"plus_one_plus_one","count":2}]}]"#;
        let inline = CardDatabase::from_json(json).unwrap();
        let broodling = card_named(&inline, "test_broodling");
        assert_eq!(broodling.power, Some(0));
        assert_eq!(broodling.toughness, Some(0));
        assert_eq!(
            broodling.abilities,
            vec![Ability::EntersWithCounters {
                counter: CounterKind::PlusOnePlusOne,
                count: 2,
            }]
        );
    }

    #[test]
    fn cancel_carries_a_counter_spell_effect() {
        // The counterspell is a vanilla-abilities instant whose spell effect counters
        // a spell on the stack (CR 701.5).
        use crate::ability::TargetSpec;
        let db = CardDatabase::bundled().unwrap();
        let cancel = card_named(&db, "cancel");
        assert_eq!(cancel.name, "Cancel");
        assert_eq!(cancel.types, vec![CardType::Instant]);
        assert!(cancel.abilities.is_empty());
        assert_eq!(
            cancel.spell_effects,
            vec![Effect::CounterSpell {
                target: TargetSpec::SpellOnStack,
            }]
        );
        assert_eq!(
            spell_effects_of(&db, id_of(&db, "cancel")),
            cancel.spell_effects
        );
        // A card with no spell ability reports none.
        assert!(spell_effects_of(&db, id_of(&db, "onakke_ogre")).is_empty());
    }

    #[test]
    fn issue_149_effect_ir_wave_fixtures_carry_their_verbs() {
        use crate::ability::{PlayerRef, TargetSpec};
        use crate::state::CounterKind;
        let db = CardDatabase::bundled().unwrap();

        // A burn instant: deal 2 to any target.
        let shock = card_named(&db, "shock");
        assert_eq!(shock.name, "Shock");
        assert_eq!(
            shock.spell_effects,
            vec![Effect::DealDamage {
                target: TargetSpec::AnyTarget,
                amount: 2
            }]
        );
        // A burn instant restricted to a creature: deal 4 to target creature.
        assert_eq!(
            card_named(&db, "electrify").spell_effects,
            vec![Effect::DealDamage {
                target: TargetSpec::AnyCreature,
                amount: 4
            }]
        );
        // A destroy instant.
        let murder = card_named(&db, "murder");
        assert_eq!(
            murder.spell_effects,
            vec![Effect::Destroy {
                target: TargetSpec::AnyCreature
            }]
        );
        // A two-effect spell: gain life, then draw.
        assert_eq!(
            card_named(&db, "revitalize").spell_effects,
            vec![
                Effect::GainLife {
                    player_ref: PlayerRef::Controller,
                    amount: 3
                },
                Effect::DrawCard { count: 1 },
            ]
        );

        // Effects the real M19 catalog does not use — a +1/+1 ETB counter, life loss,
        // and a -1/-1 counter — are exercised inline (ADR 0026).
        use crate::ability::{Ability, TriggerCondition};
        let json = r#"[
            {"schema_version":1,"functional_id":"test_sprite","name":"Test Sprite",
             "types":["creature"],"subtypes":["Faerie"],"mana_cost":"{1}{G}","colors":["green"],
             "power":1,"toughness":1,
             "abilities":[{"type":"triggered","event":"self_enters_battlefield",
               "effects":[{"kind":"put_counters","target":"any_creature","counter":"plus_one_plus_one","count":1}]}]},
            {"schema_version":1,"functional_id":"test_drain","name":"Test Drain",
             "types":["instant"],"mana_cost":"{B}","colors":["black"],
             "spell_effects":[{"kind":"lose_life","player_ref":"controller","amount":2}]},
            {"schema_version":1,"functional_id":"test_wither","name":"Test Wither",
             "types":["sorcery"],"mana_cost":"{B}","colors":["black"],
             "spell_effects":[{"kind":"put_counters","target":"any_creature","counter":"minus_one_minus_one","count":1}]}
        ]"#;
        let inline = CardDatabase::from_json(json).unwrap();
        assert_eq!(
            card_named(&inline, "test_sprite").abilities,
            vec![Ability::Triggered {
                event: TriggerCondition::SelfEntersBattlefield,
                effects: vec![Effect::PutCounters {
                    target: TargetSpec::AnyCreature,
                    counter: CounterKind::PlusOnePlusOne,
                    count: 1,
                }],
            }]
        );
        assert_eq!(
            card_named(&inline, "test_drain").spell_effects,
            vec![Effect::LoseLife {
                player_ref: PlayerRef::Controller,
                amount: 2
            }]
        );
        assert_eq!(
            card_named(&inline, "test_wither").spell_effects,
            vec![Effect::PutCounters {
                target: TargetSpec::AnyCreature,
                counter: CounterKind::MinusOneMinusOne,
                count: 1,
            }]
        );
    }

    #[test]
    fn issue_153_keyword_fixtures_carry_their_printed_keywords() {
        // CR 702: the keywords the combat-declaration step enforces, each deserialized
        // from its snake_case name off a real M19 card, and a vanilla creature prints
        // none.
        let db = CardDatabase::bundled().unwrap();

        let flyer = card_named(&db, "snapping_drake");
        assert_eq!(flyer.name, "Snapping Drake");
        assert!(flyer.has_keyword(Keyword::Flying));
        assert!(!flyer.has_keyword(Keyword::Reach));

        assert!(card_named(&db, "giant_spider").has_keyword(Keyword::Reach));
        assert!(card_named(&db, "serra_angel").has_keyword(Keyword::Vigilance));
        assert!(card_named(&db, "volcanic_dragon").has_keyword(Keyword::Haste));

        // A vanilla creature prints no keywords.
        assert!(card_named(&db, "onakke_ogre").keywords.is_empty());
        assert!(!card_named(&db, "onakke_ogre").has_keyword(Keyword::Flying));
    }

    #[test]
    fn issue_154_damage_keyword_fixtures_carry_their_printed_keywords() {
        // CR 702: the keywords II enforces at combat-damage time. Trample and lifelink
        // ride real M19 cards; first strike and deathtouch have no clean M19
        // representative, so they are exercised inline (ADR 0026).
        let db = CardDatabase::bundled().unwrap();

        assert!(card_named(&db, "colossal_dreadmaw").has_keyword(Keyword::Trample));
        assert!(card_named(&db, "child_of_night").has_keyword(Keyword::Lifelink));

        let json = r#"[
            {"schema_version":1,"functional_id":"test_duelist","name":"Test Duelist",
             "types":["creature"],"subtypes":["Human","Knight"],"mana_cost":"{1}{W}","colors":["white"],
             "power":2,"toughness":2,"keywords":["first_strike"]},
            {"schema_version":1,"functional_id":"test_baneclaw","name":"Test Baneclaw",
             "types":["creature"],"subtypes":["Beast"],"mana_cost":"{2}{B}{G}","colors":["black","green"],
             "power":4,"toughness":4,"keywords":["trample","deathtouch"]}
        ]"#;
        let inline = CardDatabase::from_json(json).unwrap();

        let duelist = card_named(&inline, "test_duelist");
        assert!(duelist.has_keyword(Keyword::FirstStrike));
        assert!(!duelist.has_keyword(Keyword::Deathtouch));

        // A creature can print more than one keyword (trample + deathtouch).
        let baneclaw = card_named(&inline, "test_baneclaw");
        assert!(baneclaw.has_keyword(Keyword::Trample));
        assert!(baneclaw.has_keyword(Keyword::Deathtouch));
    }

    #[test]
    fn issue_151_dies_fixture_carries_a_self_dies_draw_trigger() {
        // A creature whose triggered ability fires when it dies (CR 700.4 / 603.6c)
        // and draws its controller a card. No clean M19 card carries a bare dies-draw,
        // so the shape is exercised inline (ADR 0026).
        let json = r#"[{"schema_version":1,"functional_id":"test_lurker","name":"Test Lurker",
            "types":["creature"],"subtypes":["Horror"],"mana_cost":"{1}{B}","colors":["black"],
            "power":2,"toughness":2,
            "abilities":[{"type":"triggered","event":"self_dies",
              "effects":[{"kind":"draw_card","count":1}]}]}]"#;
        let db = CardDatabase::from_json(json).unwrap();
        let lurker = card_named(&db, "test_lurker");
        assert_eq!(lurker.types, vec![CardType::Creature]);
        assert_eq!(lurker.power, Some(2));
        assert_eq!(lurker.toughness, Some(2));
        assert_eq!(
            lurker.abilities,
            vec![Ability::Triggered {
                event: TriggerCondition::SelfDies,
                effects: vec![Effect::DrawCard { count: 1 }],
            }]
        );
    }

    #[test]
    fn issue_150_pump_fixture_carries_its_until_end_of_turn_verb() {
        // Titanic Growth is a vanilla-abilities instant whose spell effect pumps a
        // target creature +4/+4 until end of turn.
        use crate::ability::TargetSpec;
        let db = CardDatabase::bundled().unwrap();
        let growth = card_named(&db, "titanic_growth");
        assert_eq!(growth.name, "Titanic Growth");
        assert_eq!(growth.types, vec![CardType::Instant]);
        assert!(growth.abilities.is_empty());
        assert_eq!(
            growth.spell_effects,
            vec![Effect::Pump {
                target: TargetSpec::AnyCreature,
                power: 4,
                toughness: 4,
            }]
        );
        assert_eq!(
            spell_effects_of(&db, id_of(&db, "titanic_growth")),
            growth.spell_effects
        );
    }

    #[test]
    fn issue_152_aura_fixtures_carry_their_enchant_and_pt_grant() {
        // CR 303.4: an Aura is an Enchantment — Aura card carrying an enchant-creature
        // restriction and a static P/T grant. P/T-only Auras have no clean M19
        // representative, so they are exercised inline (ADR 0026): one buffs (+2/+2),
        // one shrinks (-2/-2); both surface their enchant slot via cast_target_specs.
        use crate::ability::TargetSpec;
        let json = r#"[
            {"schema_version":1,"functional_id":"test_aegis","name":"Test Aegis",
             "types":["enchantment"],"subtypes":["Aura"],"mana_cost":"{1}{G}","colors":["green"],
             "aura":{"enchant":"any_creature","power":2,"toughness":2}},
            {"schema_version":1,"functional_id":"test_curse","name":"Test Curse",
             "types":["enchantment"],"subtypes":["Aura"],"mana_cost":"{B}","colors":["black"],
             "aura":{"enchant":"any_creature","power":-2,"toughness":-2}}
        ]"#;
        let db = CardDatabase::from_json(json).unwrap();

        let aegis = card_named(&db, "test_aegis");
        assert_eq!(aegis.types, vec![CardType::Enchantment]);
        assert!(aegis.has_subtype("Aura"));
        assert_eq!(
            aegis.aura,
            Some(AuraGrant {
                enchant: TargetSpec::AnyCreature,
                power: 2,
                toughness: 2,
                keywords: vec![],
            })
        );
        // An Aura chooses its enchant target as it is cast (CR 601.2c): one slot.
        assert_eq!(aegis.cast_target_specs(), vec![TargetSpec::AnyCreature]);

        let curse = card_named(&db, "test_curse");
        assert!(curse.has_subtype("Aura"));
        assert_eq!(
            curse.aura,
            Some(AuraGrant {
                enchant: TargetSpec::AnyCreature,
                power: -2,
                toughness: -2,
                keywords: vec![],
            })
        );

        // A non-Aura card has no aura ability and no cast target slots.
        let bundled = CardDatabase::bundled().unwrap();
        assert!(card_named(&bundled, "onakke_ogre").aura.is_none());
        assert!(card_named(&bundled, "onakke_ogre")
            .cast_target_specs()
            .is_empty());
    }

    #[test]
    fn all_eight_keyword_variants_deserialize_from_snake_case() {
        // The closed keyword set round-trips from its wire names, including the
        // four data-only variants keywords II will enforce (CR 702).
        let json = r#"[{"schema_version":1,"functional_id":"every_keyword","name":"Every Keyword","types":["creature"],
            "mana_cost":"","power":1,"toughness":1,
            "keywords":["flying","reach","vigilance","haste","first_strike",
                        "trample","deathtouch","lifelink"]}]"#;
        let db = CardDatabase::from_json(json).unwrap();
        let card = card_named(&db, "every_keyword");
        for kw in [
            Keyword::Flying,
            Keyword::Reach,
            Keyword::Vigilance,
            Keyword::Haste,
            Keyword::FirstStrike,
            Keyword::Trample,
            Keyword::Deathtouch,
            Keyword::Lifelink,
        ] {
            assert!(card.has_keyword(kw), "expected keyword {kw:?}");
        }
    }

    #[test]
    fn bundled_printings_load_from_the_set_manifest() {
        let cards = CardDatabase::bundled().unwrap();
        let printings = PrintingDatabase::bundled(&cards).unwrap();
        // M19 prints the thirty-five cards; PM19 reprints one — thirty-six printings total.
        assert_eq!(printings.len(), 36);
        assert!(!printings.is_empty());
        let ogre = printings.printing("M19", "15").unwrap();
        // The record names onakke_ogre; the loader resolved that to its handle.
        assert_eq!(ogre.oracle, id_of(&cards, "onakke_ogre"));
        assert_eq!(ogre.rarity, Rarity::Common);
        // A collector number absent from a set does not resolve.
        assert!(printings.printing("M19", "999").is_none());
        // Neither does an unknown set code.
        assert!(printings.printing("ZZZ", "1").is_none());
    }

    #[test]
    fn adding_a_reprint_changes_no_logic() {
        // Skyscanner is printed in M19 (#19) and reprinted in PM19 (#1). The
        // two printings differ only bibliographically; everything the engine
        // reasons about is read through the shared OracleId, so it is identical.
        let cards = CardDatabase::bundled().unwrap();
        let printings = PrintingDatabase::bundled(&cards).unwrap();

        let first = printings.printing("M19", "19").unwrap();
        let reprint = printings.printing("PM19", "1").unwrap();

        // The printings are distinct bibliographic records...
        assert_ne!(first.collector_number, reprint.collector_number);
        assert_ne!(first.rarity, reprint.rarity);
        // ...but they reference the same oracle identity.
        assert_eq!(first.oracle, reprint.oracle);

        // The oracle record is byte-identical between printings.
        let oracle_a = cards.card(first.oracle).unwrap();
        let oracle_b = cards.card(reprint.oracle).unwrap();
        assert_eq!(oracle_a, oracle_b);

        // The abilities IR (ADR 0007) is identical between printings...
        assert_eq!(
            abilities_of(&cards, first.oracle),
            abilities_of(&cards, reprint.oracle),
        );
        // ...and it is the real ETB-draw behavior, not an empty coincidence.
        assert_eq!(
            abilities_of(&cards, first.oracle),
            vec![Ability::Triggered {
                event: TriggerCondition::SelfEntersBattlefield,
                effects: vec![Effect::DrawCard { count: 1 }],
            }],
        );
    }

    #[test]
    fn printing_deserializes_only_bibliographic_fields() {
        let cards = CardDatabase::bundled().unwrap();
        let json = r#"[{"functional_id":"onakke_ogre","collector_number":"1","rarity":"common"}]"#;
        let db = PrintingDatabase::from_json("TST", json, &cards).unwrap();
        assert_eq!(db.len(), 1);
        let p = db.printing("TST", "1").unwrap();
        assert_eq!(p.oracle, id_of(&cards, "onakke_ogre"));
        assert_eq!(p.rarity, Rarity::Common);
    }

    #[test]
    fn printing_rejects_art_and_branding_fields() {
        // An image_uris-style field must fail to parse: the art/branding
        // prohibition is structural via deny_unknown_fields (ADR 0013 §6).
        let cards = CardDatabase::bundled().unwrap();
        let json = r#"[{"functional_id":"onakke_ogre","collector_number":"1","rarity":"common","image_uris":{"small":"x"}}]"#;
        assert!(PrintingDatabase::from_json("TST", json, &cards).is_err());
        // An artist credit is likewise rejected.
        let json = r#"[{"functional_id":"onakke_ogre","collector_number":"1","rarity":"common","artist":"Someone"}]"#;
        assert!(PrintingDatabase::from_json("TST", json, &cards).is_err());
    }

    #[test]
    fn printing_rejects_malformed_input() {
        let cards = CardDatabase::bundled().unwrap();
        assert!(PrintingDatabase::from_json("TST", "not json", &cards).is_err());
    }

    #[test]
    fn printing_referencing_an_absent_card_fails_the_load() {
        // ADR 0018 §3: a printing names a card by its authored identity, and an
        // unresolvable reference is a load-time error — never a database that
        // resolves to None mid-game.
        let cards = CardDatabase::bundled().unwrap();
        let json = r#"[{"functional_id":"no_such_card","collector_number":"1","rarity":"common"}]"#;
        let err = PrintingDatabase::from_json("TST", json, &cards).unwrap_err();
        assert!(
            matches!(&err, CatalogError::UnknownFunctionalId { functional_id, set_code, .. }
                if functional_id.as_str() == "no_such_card" && set_code == "TST"),
            "expected an unresolved-reference error, got {err:?}"
        );
        assert!(err.to_string().contains("not in the catalog"), "{err}");
    }

    #[test]
    fn every_fixture_carries_a_unique_functional_id_matching_its_name() {
        // ADR 0018 §3: each definition's authored identity is a lowercase snake_case
        // slug of its name, unique across the catalog, and resolves back to the
        // handle the engine interned it under.
        let db = CardDatabase::bundled().unwrap();
        let mut seen = std::collections::HashSet::new();
        for id in every_id() {
            let card = db.card(id).unwrap();
            let expected: String = card
                .name
                .to_lowercase()
                .chars()
                .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
                .collect();
            assert_eq!(
                card.functional_id.as_str(),
                expected,
                "{} should be slugged from its name",
                card.name
            );
            assert!(
                seen.insert(card.functional_id.clone()),
                "{} is claimed twice",
                card.functional_id
            );
            assert_eq!(db.card_id(&card.functional_id), Some(id));
        }
        assert_eq!(seen.len(), CATALOG_SIZE);
        // An identity no definition claims resolves to nothing.
        let absent = FunctionalId::try_from("nonexistent_card".to_string()).unwrap();
        assert!(db.card_id(&absent).is_none());
    }

    #[test]
    fn every_definition_lives_in_a_file_named_for_its_identity() {
        // ADR 0018 §4: one card per file, the file name *is* the identity. `build.rs`
        // enforces this over `data/`; asserting it here means a stale or mis-generated
        // manifest cannot slip through `cargo test` either.
        let db = CardDatabase::bundled().unwrap();
        for entry in CATALOG {
            let functional_id = FunctionalId::try_from(entry.functional_id.to_string())
                .unwrap_or_else(|err| panic!("{err}"));
            let card = db.card(entry.id).unwrap();
            assert_eq!(
                card.functional_id, functional_id,
                "the manifest files {} under the wrong identity",
                entry.functional_id
            );
        }
        assert_eq!(CATALOG.len(), CATALOG_SIZE);
    }

    #[test]
    fn definition_rejects_presentation_assets() {
        // ADR 0018 §2: the functional schema is closed. Upstream presentation data
        // is structurally rejected, so it cannot enter the catalog by accident.
        for field in [
            r#""flavor_text":"A boar with a bad temper.""#,
            r#""image_uris":{"small":"https://example.test/boar.png"}"#,
            r#""artist":"Someone""#,
            r#""frame":"2015""#,
            r#""watermark":"guild""#,
        ] {
            let json = format!(
                r#"[{{"schema_version":1,"functional_id":"test_boar","name":"Test Boar",
                     "types":["creature"],"mana_cost":"{{G}}","colors":["green"],
                     "power":1,"toughness":1,{field}}}]"#
            );
            let err = CardDatabase::from_json(&json).unwrap_err();
            assert!(
                matches!(err, CatalogError::Json(_)),
                "{field} should be rejected as an unknown field, got {err:?}"
            );
        }
    }

    #[test]
    fn unrecognized_schema_version_fails_loudly() {
        // ADR 0018 §2: an unknown version is a hard error naming the offender, not a
        // silent skip that would leave the card missing from a running game. The check
        // is the same code `build.rs` runs over `data/` (ADR 0018 §5).
        let json = r#"[{"schema_version":99,"functional_id":"test_boar","name":"Test Boar",
                        "types":["creature"],"mana_cost":"{G}","colors":["green"],
                        "power":1,"toughness":1}]"#;
        let err = CardDatabase::from_json(json).unwrap_err();
        assert!(
            matches!(&err, CatalogError::Schema(Violation::UnsupportedSchemaVersion { functional_id, found })
                if functional_id == "test_boar" && *found == 99),
            "expected an unsupported-version error, got {err:?}"
        );
        let message = err.to_string();
        assert!(
            message.contains("test_boar") && message.contains("99"),
            "{message}"
        );
        // Every bundled definition declares the version this engine understands.
        let db = CardDatabase::bundled().unwrap();
        assert!(every_id().all(|id| db.card(id).unwrap().schema_version == SCHEMA_VERSION));
    }

    #[test]
    fn a_duplicated_identity_fails_the_load() {
        // Two definitions claiming one authored identity would make the catalog
        // ambiguous; the second is an error, not a silent overwrite. (In the sharded
        // catalog this is also impossible by construction — the identity is the file
        // name — but a snapshot handed to `from_json` has no filesystem to enforce it.)
        let entry = |functional_id: &str| {
            format!(
                r#"{{"schema_version":1,"functional_id":"{functional_id}","name":"Test Boar",
                    "types":["creature"],"mana_cost":"{{G}}","colors":["green"],
                    "power":1,"toughness":1}}"#
            )
        };
        let json = format!("[{},{}]", entry("test_boar"), entry("test_boar"));
        assert!(matches!(
            CardDatabase::from_json(&json).unwrap_err(),
            CatalogError::DuplicateFunctionalId { .. }
        ));
        // Two *distinct* identities cannot collide on a handle, because nobody assigns
        // one: they intern to consecutive integers in sorted order.
        let json = format!("[{},{}]", entry("test_boar"), entry("other_boar"));
        let db = CardDatabase::from_json(&json).unwrap();
        assert_eq!(db.len(), 2);
        assert_eq!(id_of(&db, "other_boar"), CardId(0));
        assert_eq!(id_of(&db, "test_boar"), CardId(1));
    }

    #[test]
    fn an_ill_formed_functional_id_fails_the_load() {
        let json = r#"[{"schema_version":1,"functional_id":"Thornback Boar","name":"Test Boar",
                        "types":["creature"],"mana_cost":"{G}","colors":["green"],
                        "power":1,"toughness":1}]"#;
        assert!(matches!(
            CardDatabase::from_json(json).unwrap_err(),
            CatalogError::Schema(Violation::MalformedFunctionalId { .. })
        ));
    }

    #[test]
    fn colors_are_authored_not_derived_from_the_cost() {
        // ADR 0018 §2: colors are an explicit field. For the current fixtures they
        // agree with the pips of their cost (this test is that authoring check), but
        // nothing derives them at runtime — so a card whose colors do not follow from
        // its cost is representable.
        let db = CardDatabase::bundled().unwrap();
        for id in every_id() {
            let card = db.card(id).unwrap();
            let cost = crate::mana::parse_mana_cost(&card.mana_cost);
            let from_pips: Vec<Color> = [
                (cost.white, Color::White),
                (cost.blue, Color::Blue),
                (cost.black, Color::Black),
                (cost.red, Color::Red),
                (cost.green, Color::Green),
            ]
            .into_iter()
            .filter(|(pips, _)| *pips > 0)
            .map(|(_, color)| color)
            .collect();
            assert_eq!(
                card.colors, from_pips,
                "{}'s authored colors disagree with its cost",
                card.name
            );
        }

        // A colorless cost with an authored color — the case pip-parsing could not
        // express — round-trips.
        let json = r#"[{"schema_version":1,"functional_id":"void_thing","name":"Void Thing",
                        "types":["creature"],"mana_cost":"{2}","colors":["black"],
                        "power":2,"toughness":2}]"#;
        let db = CardDatabase::from_json(json).unwrap();
        assert_eq!(card_named(&db, "void_thing").colors, vec![Color::Black]);
    }

    #[test]
    fn scripted_is_an_explicit_flag_defaulting_to_false() {
        // ADR 0018 §2: the escape hatch is declared on the card, not inferred. No
        // bundled card is scripted today, and every bundled card is therefore fully
        // describable from its IR alone.
        let db = CardDatabase::bundled().unwrap();
        assert!(every_id().all(|id| !db.card(id).unwrap().scripted));
        assert!(every_id()
            .all(|id| crate::scripted_rules_text(&db.card(id).unwrap().functional_id).is_none()));
    }

    /// A definition under `functional_id`, scripted or not, in the schema's current shape.
    fn scripted_fixture(functional_id: &str, scripted: bool) -> String {
        format!(
            r#"[{{"schema_version":1,"functional_id":"{functional_id}","name":"Bespoke Thing",
                 "types":["creature"],"mana_cost":"{{B}}","colors":["black"],
                 "power":1,"toughness":1,"scripted":{scripted}}}]"#
        )
    }

    #[test]
    fn the_scripted_flag_and_the_code_arm_must_agree_in_both_directions() {
        // ADR 0018 §5: the data tier and the code tier cannot silently disagree about
        // which cards are scripted. This is the one catalog rule `build.rs` cannot check
        // — the code tier is compiled Rust, which does not exist when it runs — so the
        // loader owns it, and these are the tests that hold it up.
        //
        // A card that claims the escape hatch without a code arm would lose its behavior
        // *and* have no rules text to show...
        let err = CardDatabase::from_json(&scripted_fixture("no_such_arm", true)).unwrap_err();
        assert!(
            matches!(&err, CatalogError::ScriptedWithoutCode { functional_id }
                if functional_id.as_str() == "no_such_arm"),
            "expected a scripted-without-code error, got {err:?}"
        );
        assert!(err.to_string().contains("scripted.rs"), "{err}");

        // ...and a card with a code arm that does not declare it would gain behavior
        // nobody authored in the catalog.
        let scripted_card = crate::scripted::TEST_SCRIPTED_CARD;
        let err = CardDatabase::from_json(&scripted_fixture(scripted_card, false)).unwrap_err();
        assert!(
            matches!(&err, CatalogError::UndeclaredScriptedCard { functional_id }
                if functional_id.as_str() == scripted_card),
            "expected an undeclared-scripted error, got {err:?}"
        );

        // Declared on both sides, it loads, and its hand-authored text is available for
        // the server to present in place of generated text (ADR 0018 §7).
        let db = CardDatabase::from_json(&scripted_fixture(scripted_card, true)).unwrap();
        let card = card_named(&db, scripted_card);
        assert!(card.scripted);
        assert!(crate::scripted_rules_text(&card.functional_id).is_some());
    }

    #[test]
    fn catalog_parsing_meets_its_startup_budget_at_catalog_scale() {
        // ADR 0018 §6: `CardDatabase::bundled()` must parse a 10,000-card catalog well
        // under 200ms on CI hardware. The bundled catalog is a few dozen cards, far too
        // small to measure that, so the budget is exercised against a synthetic catalog of the
        // size the target actually names.
        //
        // Measured when this landed: 53ms for 10,000 definitions in release, 206ms
        // unoptimized — so the §6 target holds with roughly 4x of headroom.
        //
        // What the assertion guards, though, is the loader's *shape*, not that number.
        // Tests run unoptimized and CI machines are noisy and shared, so the ceiling is
        // deliberately loose: an accidentally quadratic loader (a linear scan per insert
        // — easy to introduce, since interning and duplicate detection both want a
        // lookup) overshoots it by orders of magnitude at this size, while ordinary
        // machine-to-machine variance never comes close.
        const CARDS: usize = 10_000;
        const CEILING: Duration = Duration::from_secs(10);

        let mut json = String::from("[");
        for i in 0..CARDS {
            if i > 0 {
                json.push(',');
            }
            // Shaped like a real definition: a creature with a keyword and an ETB trigger.
            let _ = write!(
                json,
                r#"{{"schema_version":1,"functional_id":"synthetic_card_{i}",
                     "name":"Synthetic Card {i}","types":["creature"],"subtypes":["Spirit"],
                     "mana_cost":"{{2}}{{G}}","colors":["green"],"power":2,"toughness":2,
                     "keywords":["flying"],
                     "abilities":[{{"type":"triggered","event":"self_enters_battlefield",
                                   "effects":[{{"kind":"draw_card","count":1}}]}}]}}"#
            );
        }
        json.push(']');

        let start = Instant::now();
        let db = CardDatabase::from_json(&json).unwrap();
        let elapsed = start.elapsed();

        assert_eq!(db.len(), CARDS);
        assert!(
            elapsed < CEILING,
            "parsing {CARDS} definitions took {elapsed:?}, over the {CEILING:?} ceiling — \
             the loader is likely no longer linear in catalog size"
        );

        // And the catalog the engine actually ships stays trivial to load.
        let start = Instant::now();
        CardDatabase::bundled().unwrap();
        let bundled = start.elapsed();
        assert!(
            bundled < Duration::from_secs(1),
            "the {CATALOG_SIZE}-card bundled catalog took {bundled:?} to load"
        );
    }

    #[test]
    fn abilities_of_unions_data_and_scripted_sources() {
        let db = CardDatabase::bundled().unwrap();
        // Forest's ability comes from data; no scripted card is registered, so
        // the accessor returns exactly the data-driven ability.
        let forest = id_of(&db, "forest");
        assert_eq!(
            abilities_of(&db, forest),
            db.card(forest).unwrap().abilities
        );
        // An unknown id with no scripted abilities yields nothing.
        assert!(abilities_of(&db, CardId(9999)).is_empty());
    }

    #[test]
    fn bundled_spells_carry_their_functions() {
        use crate::ability::{Ability, Cost, Effect, TargetSpec, TriggerCondition};
        let db = CardDatabase::bundled().unwrap();

        // Lightning Strike: a {1}{R} bolt dealing 3 to any target — distinct from
        // Shock's 2, so it is its own definition rather than a reprint of one identity.
        let strike = card_named(&db, "lightning_strike");
        assert_eq!(strike.types, vec![CardType::Instant]);
        assert_eq!(
            strike.spell_effects,
            vec![Effect::DealDamage {
                target: TargetSpec::AnyTarget,
                amount: 3,
            }]
        );
        assert_ne!(
            strike.spell_effects,
            card_named(&db, "shock").spell_effects,
            "a byte-identical twin should be a reprint, not a second definition"
        );

        // Divination: a {2}{U} sorcery drawing two.
        let divination = card_named(&db, "divination");
        assert_eq!(divination.types, vec![CardType::Sorcery]);
        assert_eq!(
            divination.spell_effects,
            vec![Effect::DrawCard { count: 2 }]
        );

        // Viashino Pyromancer: a creature whose ETB trigger deals 2 to a target player.
        let pyromancer = card_named(&db, "viashino_pyromancer");
        assert_eq!(
            pyromancer.abilities,
            vec![Ability::Triggered {
                event: TriggerCondition::SelfEntersBattlefield,
                effects: vec![Effect::DealDamage {
                    target: TargetSpec::AnyPlayer,
                    amount: 2,
                }],
            }]
        );

        // A mana dork: {T}: Add {G} is a mana ability (CR 605.1a).
        let elves = card_named(&db, "llanowar_elves");
        assert_eq!(
            elves.abilities,
            vec![Ability::Activated {
                cost: vec![Cost::Tap],
                effects: vec![Effect::AddMana {
                    color: Color::Green,
                    amount: 1,
                }],
            }]
        );
        assert!(crate::ability::is_mana_ability(&elves.abilities[0]));

        // The colorless-mana verb ({T}: Add {C}) has no clean M19 representative,
        // so a mana rock is exercised inline (ADR 0026).
        let json = r#"[{"schema_version":1,"functional_id":"test_lodestone","name":"Test Lodestone",
            "types":["artifact"],"mana_cost":"{1}","colors":[],
            "abilities":[{"type":"activated","cost":[{"kind":"tap"}],
              "effects":[{"kind":"add_colorless_mana","amount":1}]}]}]"#;
        let inline = CardDatabase::from_json(json).unwrap();
        let lodestone = card_named(&inline, "test_lodestone");
        assert_eq!(lodestone.types, vec![CardType::Artifact]);
        assert_eq!(
            lodestone.abilities,
            vec![Ability::Activated {
                cost: vec![Cost::Tap],
                effects: vec![Effect::AddColorlessMana { amount: 1 }],
            }]
        );
        assert!(crate::ability::is_mana_ability(&lodestone.abilities[0]));
    }

    #[test]
    fn issue_256_no_bundled_card_is_a_functionless_shell() {
        // A castable *spell* that resolves doing nothing renders as blank generated
        // rules text (ADR 0018 §7) — the exact failure mode issue #256 fixed. This guard
        // keeps every bundled card meaningful and fails on any future functionless one:
        //
        // - a land must have an ability (its mana ability);
        // - an instant, sorcery, or noncreature permanent (artifact/enchantment) must
        //   have at least one of spell_effects / abilities / aura;
        // - a creature is inherently functional — a body with power/toughness — so a
        //   vanilla creature is not a shell, and needs no IR to prove it.
        //
        // The `scripted` escape hatch (behavior in code) also counts as function.
        let db = CardDatabase::bundled().unwrap();
        for id in every_id() {
            let card = db.card(id).unwrap();
            let has_ir = !card.spell_effects.is_empty()
                || !abilities_of(&db, id).is_empty()
                || card.aura.is_some()
                || !card.keywords.is_empty()
                || card.scripted;

            if card.has_type(CardType::Land) {
                assert!(
                    !abilities_of(&db, id).is_empty(),
                    "the land {} has no ability",
                    card.name
                );
            } else if !card.has_type(CardType::Creature) {
                assert!(
                    has_ir,
                    "{} is a functionless shell — no spell effect, ability, or aura",
                    card.name
                );
            }
        }
    }
}
