//! RUNE rules engine — layer 3.
//!
//! Invariants (see AGENTS.md in this crate):
//! - `GameState` is an immutable value type; `apply_action` returns a new state.
//! - No I/O, no async, no globals, no time. Pure functions only.
//! - Everything derivable is computed on demand (pull-based), never cached on objects.

mod id;
mod phase;
mod player;
mod state;
mod zone;

pub use id::{CardId, PermanentId, PlayerId};
pub use phase::Step;
pub use player::{Player, STARTING_LIFE};
pub use state::{GameState, Permanent};
pub use zone::Zone;

/// Placeholder action. Real actions are generated by the engine and validated here.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Action {
    /// Yield priority without taking any other action.
    PassPriority,
}

/// The single entry point of the engine: pure state transition.
#[must_use]
pub fn apply_action(state: &GameState, _action: &Action) -> GameState {
    // Pipeline (to implement): validate -> clone -> apply -> replacements ->
    // state-based actions loop -> collect triggers -> return.
    state.clone()
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;

    #[test]
    fn apply_action_does_not_mutate_input() {
        let before = GameState::new_two_player();
        let after = apply_action(&before, &Action::PassPriority);
        assert_eq!(before, after);
        assert_eq!(before.turn, 1);
    }

    #[test]
    fn new_two_player_initial_invariants() {
        let state = GameState::new_two_player();
        assert_eq!(state.turn, 1);
        assert_eq!(state.active_player, PlayerId(0));
        assert_eq!(state.step, Step::Untap);
        assert_eq!(state.players.len(), 2);
        assert!(state.battlefield.is_empty());

        for player in &state.players {
            assert_eq!(player.life, STARTING_LIFE);
            assert!(player.library.is_empty());
            assert!(player.hand.is_empty());
            assert!(player.graveyard.is_empty());
            assert!(player.exile.is_empty());
        }

        // The active player resolves to an actual seat.
        let active = state.active_player().unwrap();
        assert_eq!(active.life, STARTING_LIFE);
    }

    #[test]
    fn default_state_is_empty() {
        let state = GameState::default();
        assert_eq!(state.turn, 0);
        assert_eq!(state.step, Step::Untap);
        assert!(state.players.is_empty());
        // No seats, so there is no active player to borrow.
        assert!(state.active_player().is_none());
    }

    #[test]
    fn step_next_cycles_through_the_turn() {
        // Twelve steps, wrapping back to Untap.
        let mut step = Step::Untap;
        let sequence = [
            Step::Upkeep,
            Step::Draw,
            Step::PrecombatMain,
            Step::BeginCombat,
            Step::DeclareAttackers,
            Step::DeclareBlockers,
            Step::CombatDamage,
            Step::EndCombat,
            Step::PostcombatMain,
            Step::End,
            Step::Cleanup,
            Step::Untap,
        ];
        for expected in sequence {
            step = step.next();
            assert_eq!(step, expected);
        }
    }

    #[test]
    fn player_zone_accessor_matches_fields() {
        let mut player = Player::new();
        player.hand.push(CardId(7));
        player.graveyard.push(CardId(9));
        assert_eq!(player.zone(Zone::Hand), &vec![CardId(7)]);
        assert_eq!(player.zone(Zone::Graveyard), &vec![CardId(9)]);
        assert!(player.zone(Zone::Library).is_empty());
        assert!(player.zone(Zone::Exile).is_empty());
    }
}
