//! RUNE rules engine — layer 3.
//!
//! Invariants (see AGENTS.md in this crate):
//! - `GameState` is an immutable value type; `apply_action` returns a new state.
//! - No I/O, no async, no globals, no time. Pure functions only.
//! - Everything derivable is computed on demand (pull-based), never cached on objects.

/// Placeholder game state. Grows per docs/brief.md ("Rules Engine Design").
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GameState {
    pub turn: u32,
}

/// Placeholder action. Real actions are generated by the engine and validated here.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Action {
    PassPriority,
}

/// The single entry point of the engine: pure state transition.
#[must_use]
pub fn apply_action(state: &GameState, _action: &Action) -> GameState {
    // Pipeline (to implement): validate -> clone -> apply -> replacements ->
    // state-based actions loop -> collect triggers -> return.
    state.clone()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn apply_action_does_not_mutate_input() {
        let before = GameState { turn: 3 };
        let _after = apply_action(&before, &Action::PassPriority);
        assert_eq!(before.turn, 3);
    }
}
