/**
 * GameView → table scene mapping (fixed-shell anatomy, ADR 0023).
 * Re-exports from focused scene-model modules.
 */
export {
  type Rect,
  type SurfaceTier,
  type PanelFrame,
  type SceneGeometry,
  type RenderedCard,
  type BandRowKind,
  type BandRow,
  type TargetingScene,
  type ZoneCounts,
  type Band,
  type HandRegion,
  type CombatLink,
  type AttackTarget,
  type TableScene,
  M,
  DEFAULT_VIEWPORT_WIDTH,
  defaultSceneGeometry,
  cellSize,
  tappedFootprint,
  localPlayerIdOf,
  orderedOpponentIds,
  bandLabel,
  zoneCountsOf,
  toDisplayData,
  hasActivatedAbilityText,
  rowKindForType,
  basicLandGlyph,
  actionFingerprint,
  groupStacks,
  actionsFor,
  declarationFor,
  tiersForSurface,
  stepDown,
  flowRow,
  layPanel,
  layHand,
  buildTableScene,
} from './scene/index';
